LLVM: lib/Target/X86/X86MCInstLower.cpp File Reference
X86MCInstLower.cpp File Reference
#include "MCTargetDesc/X86ATTInstPrinter.h"
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86InstComments.h"
#include "MCTargetDesc/X86ShuffleDecode.h"
#include "MCTargetDesc/X86TargetStreamer.h"
#include "X86AsmPrinter.h"
#include "X86RegisterInfo.h"
#include "X86ShuffleDecodeConstantPool.h"
#include "X86Subtarget.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
#include "llvm/Transforms/Instrumentation/AddressSanitizerCommon.h"
#include <string>
Classes
struct NoAutoPaddingScope
A RAII helper which defines a region of instructions which can't have padding added between them for correctness.
Macros
#define MOV_CASE(Prefix, Suffix)
#define MOV_AVX512_CASE(Suffix)
#define CASE_ALL_MOV_RM()
Functions
static void emitX86Nops (MCStreamer &OS, unsigned NumBytes, const X86Subtarget *Subtarget)
Emit the optimal amount of multi-byte nops on X86.
static void SimplifyShortImmForm (MCInst &Inst, unsigned Opcode)
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
static void SimplifyMOVSX (MCInst &Inst)
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
static void SimplifyShortMoveForm (X86AsmPrinter &Printer, MCInst &Inst, unsigned Opcode)
Simplify things like MOV32rm to MOV32o32a.
static unsigned getRetOpcode (const X86Subtarget &Subtarget)
static unsigned convertTailJumpOpcode (unsigned Opcode)
static unsigned emitNop (MCStreamer &OS, unsigned NumBytes, const X86Subtarget *Subtarget)
Emit the largest nop instruction smaller than or equal to NumBytes bytes.
static MachineBasicBlock::const_iterator PrevCrossBBInst (MachineBasicBlock::const_iterator MBBI)
static const Constant * getConstantFromPool (const MachineInstr &MI, const MachineOperand &Op)
static std::string getShuffleComment (const MachineInstr *MI, unsigned SrcOp1Idx, unsigned SrcOp2Idx, ArrayRef< int > Mask)
static void printConstant (const APInt &Val, raw_ostream &CS)
static void printConstant (const APFloat &Flt, raw_ostream &CS)
static void printConstant (const Constant *COp, raw_ostream &CS)
static unsigned getRegisterWidth (const MCOperandInfo &Info)
static void addConstantComments (const MachineInstr *MI, MCStreamer &OutStreamer)
Macro Definition Documentation
CASE_ALL_MOV_RM
#define CASE_ALL_MOV_RM ()
Value:
  MOV_CASE(, )   /* SSE */                                                     \
  MOV_CASE(V, )  /* AVX-128 */                                                 \
  MOV_CASE(V, Y) /* AVX-256 */                                                 \
  MOV_AVX512_CASE(Z)                                                           \
  MOV_AVX512_CASE(Z256)                                                        \
  MOV_AVX512_CASE(Z128)
Referenced by addConstantComments().
MOV_AVX512_CASE
#define MOV_AVX512_CASE (Suffix)
Value:
  case X86::VMOVDQA64##Suffix##rm:                                             \
  case X86::VMOVDQA32##Suffix##rm:                                             \
  case X86::VMOVDQU64##Suffix##rm:                                             \
  case X86::VMOVDQU32##Suffix##rm:                                             \
  case X86::VMOVDQU16##Suffix##rm:                                             \
  case X86::VMOVDQU8##Suffix##rm:                                              \
  case X86::VMOVAPS##Suffix##rm:                                               \
  case X86::VMOVAPD##Suffix##rm:                                               \
  case X86::VMOVUPS##Suffix##rm:                                               \
  case X86::VMOVUPD##Suffix##rm:
MOV_CASE
#define MOV_CASE (Prefix, Suffix)
Value:
  case X86::Prefix##MOVAPD##Suffix##rm:                                        \
  case X86::Prefix##MOVAPS##Suffix##rm:                                        \
  case X86::Prefix##MOVUPD##Suffix##rm:                                        \
  case X86::Prefix##MOVUPS##Suffix##rm:                                        \
  case X86::Prefix##MOVDQA##Suffix##rm:                                        \
  case X86::Prefix##MOVDQU##Suffix##rm:
Function Documentation
addConstantComments()
static void addConstantComments (const MachineInstr * MI, MCStreamer & OutStreamer) static
Definition at line 2042 of file X86MCInstLower.cpp.
References llvm::MCStreamer::AddComment(), llvm::X86::AddrDisp, llvm::X86::AddrNumOperands, assert(), llvm::CallingConv::C, CASE_ALL_MOV_RM, llvm::DecodePSHUFBMask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPPERMMask(), llvm::dyn_cast(), getConstantFromPool(), llvm::MachineOperand::getImm(), llvm::DstOp::getReg(), llvm::X86ATTInstPrinter::getRegisterName(), getRegisterWidth(), getShuffleComment(), llvm::MachineOperand::isImm(), llvm::X86II::isKMasked(), llvm::X86II::isKMergeMasked(), llvm_unreachable, MI, printConstant(), llvm::raw_string_ostream::str(), and llvm::dwarf::toString().
Referenced by llvm::X86AsmPrinter::emitInstruction().
convertTailJumpOpcode()
static unsigned convertTailJumpOpcode (unsigned Opcode) static
Definition at line 466 of file X86MCInstLower.cpp.
emitNop()
static unsigned emitNop (MCStreamer & OS, unsigned NumBytes, const X86Subtarget * Subtarget) static
Emit the largest nop instruction smaller than or equal to NumBytes bytes.
Return the size of nop emitted.
Definition at line 1101 of file X86MCInstLower.cpp.
References assert(), llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitInstruction(), and llvm_unreachable.
Referenced by emitX86Nops().
emitX86Nops()
static void emitX86Nops (MCStreamer & OS, unsigned NumBytes, const X86Subtarget * Subtarget) static
Emit the optimal amount of multi-byte nops on X86.
Definition at line 1218 of file X86MCInstLower.cpp.
References assert(), and emitNop().
getConstantFromPool()
static const Constant * getConstantFromPool (const MachineInstr & MI, const MachineOperand & Op) static
Definition at line 1819 of file X86MCInstLower.cpp.
References llvm::MachineConstantPoolEntry::ConstVal, llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), MI, and llvm::MachineConstantPoolEntry::Val.
Referenced by addConstantComments().
getRegisterWidth()
static unsigned getRegisterWidth (const MCOperandInfo & Info) static
Definition at line 2030 of file X86MCInstLower.cpp.
References llvm_unreachable.
Referenced by addConstantComments().
getRetOpcode()
static unsigned getRetOpcode (const X86Subtarget & Subtarget) static
Definition at line 427 of file X86MCInstLower.cpp.
Referenced by llvm::X86AsmPrinter::emitInstruction().
getShuffleComment()
static std::string getShuffleComment (const MachineInstr * MI, unsigned SrcOp1Idx, unsigned SrcOp2Idx, ArrayRef< int > Mask) static
Definition at line 1836 of file X86MCInstLower.cpp.
References assert(), llvm::raw_ostream::flush(), llvm::DstOp::getReg(), llvm::MachineOperand::getReg(), llvm::X86ATTInstPrinter::getRegisterName(), llvm::MachineOperand::isReg(), MI, llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by addConstantComments().
PrevCrossBBInst()
static MachineBasicBlock::const_iterator PrevCrossBBInst (MachineBasicBlock::const_iterator MBBI) static
Definition at line 1807 of file X86MCInstLower.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::front(), llvm::MachineBasicBlock::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), MBB, and MBBI.
Referenced by llvm::X86AsmPrinter::emitInstruction().
printConstant() [1/3]
static void printConstant (const APFloat & Flt, raw_ostream & CS) static
Definition at line 1936 of file X86MCInstLower.cpp.
References llvm::APFloat::toString().
printConstant() [2/3]
static void printConstant (const APInt & Val, raw_ostream & CS) static
Definition at line 1921 of file X86MCInstLower.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getNumWords(), llvm::APInt::getRawData(), llvm::APInt::getZExtValue(), and N.
Referenced by addConstantComments(), and printConstant().
printConstant() [3/3]
static void printConstant (const Constant * COp, raw_ostream & CS) static
Definition at line 1943 of file X86MCInstLower.cpp.
References llvm::dyn_cast(), llvm::isa(), and printConstant().
SimplifyMOVSX()
static void SimplifyMOVSX (MCInst & Inst) static
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
Definition at line 349 of file X86MCInstLower.cpp.
References llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, and llvm::MCInst::setOpcode().
SimplifyShortImmForm()
static void SimplifyShortImmForm (MCInst & Inst, unsigned Opcode) static
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
Definition at line 326 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), Saved, and llvm::MCInst::setOpcode().
SimplifyShortMoveForm()
static void SimplifyShortMoveForm (X86AsmPrinter & Printer, MCInst & Inst, unsigned Opcode) static
Simplify things like MOV32rm to MOV32o32a.
Definition at line 376 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::X86::AddrScaleAmt, llvm::X86::AddrSegmentReg, assert(), llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), Saved, llvm::MCInst::setOpcode(), and llvm::MCSymbolRefExpr::VK_TLVP.