LLVM: lib/Remarks/YAMLRemarkSerializer.cpp File Reference
YAMLRemarkSerializer.cpp File Reference
#include "llvm/Remarks/YAMLRemarkSerializer.h"
#include "llvm/Remarks/Remark.h"
#include "llvm/Support/FileSystem.h"
Classes
struct llvm::yaml::MappingTraits< remarks::Remark * >
struct llvm::yaml::MappingTraits< RemarkLocation >
struct llvm::yaml::StringBlockVal
Helper struct for multiline string block literals.
struct llvm::yaml::BlockScalarTraits< StringBlockVal >
struct llvm::yaml::SequenceTraits< ArrayRef< T > >
ArrayRef is not really compatible with the YAMLTraits.
struct llvm::yaml::MappingTraits< Argument >
Implement this as a mapping for now to get proper quotation for the value.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Functions
template<typename T >
static void mapRemarkHeader (yaml::IO &io, T PassName, T RemarkName, Optional< RemarkLocation > RL, T FunctionName, Optional< uint64_t > Hotness, ArrayRef< Argument > Args)
static void emitMagic (raw_ostream &OS)
static void emitVersion (raw_ostream &OS)
static void emitStrTab (raw_ostream &OS, Optional< const StringTable * > StrTab)
static void emitExternalFile (raw_ostream &OS, StringRef Filename)
Function Documentation
emitExternalFile()
static void emitExternalFile (raw_ostream & OS, StringRef Filename) static
Definition at line 232 of file YAMLRemarkSerializer.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::SmallVectorBase< Size_T >::empty(), llvm::sys::fs::make_absolute(), llvm::SmallVectorBase< Size_T >::size(), and llvm::raw_ostream::write().
Referenced by llvm::remarks::YAMLMetaSerializer::emit(), and llvm::remarks::YAMLStrTabMetaSerializer::emit().
emitMagic()
static void emitMagic (raw_ostream & OS) static
Definition at line 205 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::Magic(), and llvm::raw_ostream::write().
Referenced by llvm::remarks::YAMLMetaSerializer::emit(), and llvm::remarks::YAMLStrTabMetaSerializer::emit().
emitStrTab()
static void emitStrTab (raw_ostream & OS, Optional< const StringTable * > StrTab) static
Definition at line 219 of file YAMLRemarkSerializer.cpp.
References llvm::raw_ostream::write(), and llvm::support::endian::write64le().
Referenced by llvm::remarks::YAMLMetaSerializer::emit(), and llvm::remarks::YAMLStrTabMetaSerializer::emit().
emitVersion()
static void emitVersion (raw_ostream & OS) static
Definition at line 212 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::CurrentRemarkVersion, llvm::Version, llvm::raw_ostream::write(), and llvm::support::endian::write64le().
Referenced by llvm::remarks::YAMLMetaSerializer::emit(), and llvm::remarks::YAMLStrTabMetaSerializer::emit().
mapRemarkHeader()
template<typename T > static void mapRemarkHeader (yaml::IO & io, T PassName, T RemarkName, Optional< RemarkLocation > RL, T FunctionName, Optional< uint64_t > Hotness, ArrayRef< Argument > Args) static
Definition at line 24 of file YAMLRemarkSerializer.cpp.
References PassName.
Referenced by llvm::yaml::MappingTraits< remarks::Remark * >::mapping().