LLVM: lib/Target/AArch64/AArch64A53Fix835769.cpp File Reference
AArch64A53Fix835769.cpp File Reference
#include "AArch64.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "aarch64-fix-cortex-a53-835769"
Functions
STATISTIC (NumNopsAdded, "Number of Nops added to work around erratum 835769")
static bool isFirstInstructionInSequence (MachineInstr *MI)
static bool isSecondInstructionInSequence (MachineInstr *MI)
INITIALIZE_PASS (AArch64A53Fix835769, "aarch64-fix-cortex-a53-835769-pass", "AArch64 fix for A53 erratum 835769", false, false) bool AArch64A53Fix835769
static MachineBasicBlock * getBBFallenThrough (MachineBasicBlock *MBB, const TargetInstrInfo *TII)
static MachineInstr * getLastNonPseudo (MachineBasicBlock &MBB, const TargetInstrInfo *TII)
static void insertNopBeforeInstruction (MachineBasicBlock &MBB, MachineInstr *MI, const TargetInstrInfo *TII)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-fix-cortex-a53-835769"
Definition at line 30 of file AArch64A53Fix835769.cpp.
Function Documentation
getBBFallenThrough()
static MachineBasicBlock * getBBFallenThrough (MachineBasicBlock * MBB, const TargetInstrInfo * TII) static
Definition at line 130 of file AArch64A53Fix835769.cpp.
References llvm::HexagonInstrInfo::analyzeBranch(), llvm::MachineFunction::begin(), Cond, llvm::MachineBasicBlock::getParent(), MBB, MBBI, llvm::MachineBasicBlock::predecessors(), and TII.
Referenced by getLastNonPseudo().
getLastNonPseudo()
static MachineInstr * getLastNonPseudo (MachineBasicBlock & MBB, const TargetInstrInfo * TII) static
Definition at line 155 of file AArch64A53Fix835769.cpp.
References getBBFallenThrough(), I, llvm::make_range(), MBB, llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), and TII.
Referenced by insertNopBeforeInstruction().
INITIALIZE_PASS()
INITIALIZE_PASS (AArch64A53Fix835769 , "aarch64-fix-cortex-a53-835769-pass" , "AArch64 fix for A53 erratum 835769" , false , false)
Definition at line 111 of file AArch64A53Fix835769.cpp.
References Changed, llvm::dbgs(), F, LLVM_DEBUG, MBB, runOnBasicBlock(), and TII.
insertNopBeforeInstruction()
static void insertNopBeforeInstruction (MachineBasicBlock & MBB, MachineInstr * MI, const TargetInstrInfo * TII) static
Definition at line 171 of file AArch64A53Fix835769.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::front(), llvm::SDLoc::getDebugLoc(), getLastNonPseudo(), I, MBB, MI, and TII.
isFirstInstructionInSequence()
static bool isFirstInstructionInSequence (MachineInstr * MI) static
Definition at line 39 of file AArch64A53Fix835769.cpp.
References MI.
isSecondInstructionInSequence()
static bool isSecondInstructionInSequence (MachineInstr * MI) static
Definition at line 55 of file AArch64A53Fix835769.cpp.
References MI.
STATISTIC()
STATISTIC (NumNopsAdded , "Number of Nops added to work around erratum 835769")