LLVM: lib/Target/AMDGPU/AMDGPUPromoteAlloca.cpp File Reference
AMDGPUPromoteAlloca.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsR600.h"
#include "llvm/Pass.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "amdgpu-promote-alloca"
Functions
INITIALIZE_PASS (AMDGPUPromoteAlloca, DEBUG_TYPE, "AMDGPU promote alloca to vector or LDS", false, false) INITIALIZE_PASS(AMDGPUPromoteAllocaToVector
static FixedVectorType * arrayTypeToVecType (ArrayType *ArrayTy)
static Value * stripBitcasts (Value *V)
static Value * calculateVectorIndex (Value *Ptr, const std::map< GetElementPtrInst *, Value * > &GEPIdx)
static Value * GEPToVectorIndex (GetElementPtrInst *GEP)
static bool canVectorizeInst (Instruction *Inst, User *User, const DataLayout &DL)
static bool tryPromoteAllocaToVector (AllocaInst *Alloca, const DataLayout &DL, unsigned MaxVGPRs)
static bool isCallPromotable (CallInst *CI)
bool handlePromoteAllocaToVector (AllocaInst &I, unsigned MaxVGPRs)
bool promoteAllocasToVector (Function &F, TargetMachine &TM)
Variables
DEBUG_TYPE to vector
DEBUG_TYPE to AMDGPU promote alloca to false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-promote-alloca"
Definition at line 25 of file AMDGPUPromoteAlloca.cpp.
Function Documentation
arrayTypeToVecType()
static FixedVectorType * arrayTypeToVecType (ArrayType * ArrayTy) static
Definition at line 315 of file AMDGPUPromoteAlloca.cpp.
References llvm::FixedVectorType::get().
Referenced by tryPromoteAllocaToVector().
calculateVectorIndex()
static Value * calculateVectorIndex (Value * Ptr, const std::map< GetElementPtrInst *, Value * > & GEPIdx) static
Definition at line 330 of file AMDGPUPromoteAlloca.cpp.
References llvm::dyn_cast(), GEP, I, and stripBitcasts().
Referenced by tryPromoteAllocaToVector().
canVectorizeInst()
static bool canVectorizeInst (Instruction * Inst, User * User, const DataLayout & DL) static
Definition at line 356 of file AMDGPUPromoteAlloca.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::Instruction::getOpcode(), llvm::LoadInst::getPointerOperand(), llvm::LoadInst::getPointerOperandType(), llvm::Value::getType(), llvm::isa(), llvm::LoadInst::isSimple(), and SI.
Referenced by tryPromoteAllocaToVector().
GEPToVectorIndex()
static Value * GEPToVectorIndex (GetElementPtrInst * GEP) static
Definition at line 340 of file AMDGPUPromoteAlloca.cpp.
References llvm::dyn_cast(), GEP, and llvm::ConstantInt::isZero().
Referenced by tryPromoteAllocaToVector().
handlePromoteAllocaToVector()
bool handlePromoteAllocaToVector (AllocaInst & I, unsigned MaxVGPRs)
Definition at line 1056 of file AMDGPUPromoteAlloca.cpp.
References llvm::dbgs(), I, LLVM_DEBUG, llvm::Mod, and tryPromoteAllocaToVector().
Referenced by promoteAllocasToVector().
INITIALIZE_PASS()
INITIALIZE_PASS (AMDGPUPromoteAlloca , DEBUG_TYPE , "AMDGPU promote alloca to vector or LDS" , false , false)
isCallPromotable()
static bool isCallPromotable (CallInst * CI) static
Definition at line 547 of file AMDGPUPromoteAlloca.cpp.
References llvm::dyn_cast(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Intrinsic::invariant_end, llvm::Intrinsic::invariant_start, llvm::Intrinsic::launder_invariant_group, llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, llvm::Intrinsic::objectsize, and llvm::Intrinsic::strip_invariant_group.
promoteAllocasToVector()
bool promoteAllocasToVector (Function & F, TargetMachine & TM)
Definition at line 1068 of file AMDGPUPromoteAlloca.cpp.
References llvm::Triple::amdgcn, llvm::BasicBlock::begin(), Changed, llvm::dyn_cast(), F, llvm::AMDGPUSubtarget::get(), handlePromoteAllocaToVector(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::AMDGPUPromoteAllocaToVectorPass::run().
stripBitcasts()
static Value * stripBitcasts (Value * V) static
Definition at line 320 of file AMDGPUPromoteAlloca.cpp.
References llvm::dyn_cast(), and I.
Referenced by calculateVectorIndex().
tryPromoteAllocaToVector()
static bool tryPromoteAllocaToVector (AllocaInst * Alloca, const DataLayout & DL, unsigned MaxVGPRs) static
Definition at line 402 of file AMDGPUPromoteAlloca.cpp.
References llvm::SmallVectorImpl< T >::append(), arrayTypeToVecType(), Builder, calculateVectorIndex(), canVectorizeInst(), llvm::cast(), llvm::dbgs(), DL, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), GEP, GEPToVectorIndex(), llvm::AllocaInst::getAllocatedType(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Type::getPointerElementType(), llvm::Type::getPointerTo(), llvm::Value::getType(), Index, llvm::Type::isAggregateType(), llvm::isAssumeLikeIntrinsic(), llvm::VectorType::isValidElementType(), llvm::Type::isVectorTy(), LLVM_DEBUG, llvm_unreachable, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), SI, Users, and llvm::Value::users().
Referenced by handlePromoteAllocaToVector().
Variable Documentation
false
DEBUG_TYPE to AMDGPU promote alloca to false
Definition at line 133 of file AMDGPUPromoteAlloca.cpp.
vector
DEBUG_TYPE to AMDGPU promote alloca to vector
Definition at line 132 of file AMDGPUPromoteAlloca.cpp.