LLVM: lib/Target/AMDGPU/AMDGPUCallLowering.cpp File Reference
AMDGPUCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "AMDGPUCallLowering.h"
#include "AMDGPU.h"
#include "AMDGPULegalizerInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
Macros
#define DEBUG_TYPE "amdgpu-call-lowering"
Functions
static ISD::NodeType extOpcodeToISDExtOpcode (unsigned MIOpc)
static void unpackRegsToOrigType (MachineIRBuilder &B, ArrayRef< Register > DstRegs, Register SrcReg, const CallLowering::ArgInfo &Info, LLT SrcTy, LLT PartTy)
static void allocateHSAUserSGPRs (CCState &CCInfo, MachineIRBuilder &B, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static MachineInstrBuilder mergeVectorRegsToResultRegs (MachineIRBuilder &B, ArrayRef< Register > DstRegs, ArrayRef< Register > SrcRegs)
Pack values SrcRegs to cover the vector type result DstRegs.
static void packSplitRegsToOrigType (MachineIRBuilder &B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT)
static std::pair< CCAssignFn *, CCAssignFn * > getAssignFnsForCC (CallingConv::ID CC, const SITargetLowering &TLI)
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
static unsigned getCallOpcode (const MachineFunction &CallerF, bool IsIndirect, bool IsTailCall)
static bool addCallTargetOperands (MachineInstrBuilder &CallInst, MachineIRBuilder &MIRBuilder, AMDGPUCallLowering::CallLoweringInfo &Info)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file AMDGPUCallLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-call-lowering"
Definition at line 26 of file AMDGPUCallLowering.cpp.
Function Documentation
addCallTargetOperands()
static bool addCallTargetOperands (MachineInstrBuilder & CallInst, MachineIRBuilder & MIRBuilder, AMDGPUCallLowering::CallLoweringInfo & Info) static
Definition at line 1191 of file AMDGPUCallLowering.cpp.
References llvm::MachineIRBuilder::buildGlobalValue(), llvm::GlobalValue::getAddressSpace(), and llvm::LLT::pointer().
Referenced by llvm::AMDGPUCallLowering::lowerCall().
allocateHSAUserSGPRs()
static void allocateHSAUserSGPRs (CCState & CCInfo, MachineIRBuilder & B, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 608 of file AMDGPUCallLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), B, llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineFunction::getRegInfo(), MRI, llvm::LLT::pointer(), and TRI.
Referenced by llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
extOpcodeToISDExtOpcode()
static ISD::NodeType extOpcodeToISDExtOpcode (unsigned MIOpc) static
Definition at line 267 of file AMDGPUCallLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm_unreachable, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
getAssignFnsForCC()
static std::pair< CCAssignFn *, CCAssignFn * > getAssignFnsForCC (CallingConv::ID CC, const SITargetLowering & TLI) static
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
Definition at line 1181 of file AMDGPUCallLowering.cpp.
References llvm::AMDGPUTargetLowering::CCAssignFnForCall().
getCallOpcode()
static unsigned getCallOpcode (const MachineFunction & CallerF, bool IsIndirect, bool IsTailCall) static
Definition at line 1185 of file AMDGPUCallLowering.cpp.
mergeVectorRegsToResultRegs()
static MachineInstrBuilder mergeVectorRegsToResultRegs (MachineIRBuilder & B, ArrayRef< Register > DstRegs, ArrayRef< Register > SrcRegs) static
Pack values SrcRegs to cover the vector type result DstRegs.
Definition at line 738 of file AMDGPUCallLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::end(), llvm::getLCMType(), llvm::LLT::getSizeInBits(), I, MRI, and llvm::ArrayRef< T >::size().
Referenced by packSplitRegsToOrigType().
packSplitRegsToOrigType()
static void packSplitRegsToOrigType (MachineIRBuilder & B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT) static
Definition at line 775 of file AMDGPUCallLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::drop_front(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isPointer(), llvm::LLT::isVector(), Merge, mergeVectorRegsToResultRegs(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LLT::scalar(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::take_front(), and llvm::LLT::vector().
Referenced by llvm::AMDGPUCallLowering::lowerFormalArguments().
unpackRegsToOrigType()
static void unpackRegsToOrigType (MachineIRBuilder & B, ArrayRef< Register > DstRegs, Register SrcReg, const CallLowering::ArgInfo & Info, LLT SrcTy, LLT PartTy) static
Definition at line 368 of file AMDGPUCallLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::getGCDType(), llvm::getLCMType(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, and llvm::ArrayRef< T >::size().