LLVM: lib/Testing/Support/Annotations.cpp File Reference
Annotations.cpp File Reference
#include "llvm/Testing/Support/Annotations.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void require (bool Assertion, const char *Msg, llvm::StringRef Code)
Function Documentation
require()
static void require (bool Assertion, const char * Msg, llvm::StringRef Code) static
Definition at line 19 of file Annotations.cpp.
References llvm::errs(), and llvm_unreachable.
Referenced by llvm::Annotations::Annotations(), llvm::Annotations::point(), and llvm::Annotations::range().