LLVM: lib/Analysis/AssumptionCache.cpp File Reference
AssumptionCache.cpp File Reference
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <utility>
Functions
static void findAffectedValues (CallInst *CI, SmallVectorImpl< AssumptionCache::ResultElem > &Affected)
Variables
static cl::opt< bool > VerifyAssumptionCache ("verify-assumption-cache", cl::Hidden, cl::desc("Enable verification of assumption cache"), cl::init(false))
Function Documentation
findAffectedValues()
static void findAffectedValues (CallInst * CI, SmallVectorImpl< AssumptionCache::ResultElem > & Affected) static
Definition at line 59 of file AssumptionCache.cpp.
References A, llvm::ABA_WasOn, B, Cond, llvm::dyn_cast(), llvm::AssumptionCache::ExprResultIdx, llvm::CallBase::getArgOperand(), llvm::CallBase::getNumOperandBundles(), llvm::CallBase::getOperandBundleAt(), llvm::OperandBundleUse::getTagName(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::IgnoreBundleTag, llvm::OperandBundleUse::Inputs, llvm::isa(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_BitwiseLogic(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and X.
Referenced by llvm::AssumptionCache::unregisterAssumption(), and llvm::AssumptionCache::updateAffectedValues().
Variable Documentation
VerifyAssumptionCache
cl::opt< bool > VerifyAssumptionCache("verify-assumption-cache", cl::Hidden, cl::desc("Enable verification of assumption cache"), cl::init(false)) ("verify-assumption-cache" , cl::Hidden , cl::desc("Enable verification of assumption cache") , cl::init(false)) static
Referenced by llvm::AssumptionCacheTracker::verifyAnalysis().