LLVM: lib/Target/BPF/BPFAsmPrinter.cpp File Reference
BPFAsmPrinter.cpp File Reference
#include "BPF.h"
#include "BPFInstrInfo.h"
#include "BPFMCInstLower.h"
#include "BPFTargetMachine.h"
#include "BTFDebug.h"
#include "MCTargetDesc/BPFInstPrinter.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFAsmPrinter ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 34 of file BPFAsmPrinter.cpp.
Function Documentation
LLVMInitializeBPFAsmPrinter()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFAsmPrinter ()
Definition at line 151 of file BPFAsmPrinter.cpp.
References llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), X, Y, and llvm::Z.