LLVM: lib/Support/CachePruning.cpp File Reference
CachePruning.cpp File Reference
#include "llvm/Support/CachePruning.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <set>
#include <system_error>
Macros
#define DEBUG_TYPE "cache-pruning"
Functions
static void writeTimestampFile (StringRef TimestampFile)
Write a new timestamp file with the given path.
static Expected< std::chrono::seconds > parseDuration (StringRef Duration)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "cache-pruning"
Definition at line 22 of file CachePruning.cpp.
Function Documentation
parseDuration()
static Expected< std::chrono::seconds > parseDuration (StringRef Duration) static
Definition at line 51 of file CachePruning.cpp.
References llvm::StringRef::back(), llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::StringRef::size(), and llvm::StringRef::slice().
Referenced by llvm::parseCachePruningPolicy().
writeTimestampFile()
static void writeTimestampFile (StringRef TimestampFile) static
Write a new timestamp file with the given path.
This is used for the pruning interval option.
Definition at line 46 of file CachePruning.cpp.
References llvm::sys::fs::OF_None, and llvm::StringRef::str().
Referenced by llvm::pruneCache().