LLVM: llvm::SDLoc Class Reference
llvm::SDLoc Class Reference
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Member Functions
SDLoc ()=default
SDLoc (const SDNode *N)
SDLoc (const SDValue V)
SDLoc (const Instruction *I, int Order)
unsigned getIROrder () const
const DebugLoc & getDebugLoc () const
Detailed Description
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
When an SDNode is created from the DAGBuilder, the DebugLoc is extracted from the original Instruction, and IROrder is the ordinal position of the instruction. When an SDNode is created after the DAG is being built, both DebugLoc and the IROrder are propagated from the original SDNode. So SDLoc class provides two constructors besides the default one, one to be used by the DAGBuilder, the other to be used by others.
Definition at line 1078 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDLoc() [1/4]
llvm::SDLoc::SDLoc () default
SDLoc() [2/4]
llvm::SDLoc::SDLoc (const SDNode * N) inline
Definition at line 1085 of file SelectionDAGNodes.h.
References DL.
SDLoc() [3/4]
llvm::SDLoc::SDLoc (const SDValue V) inline
Definition at line 1086 of file SelectionDAGNodes.h.
SDLoc() [4/4]
llvm::SDLoc::SDLoc (const Instruction * I, int Order) inline
Definition at line 1087 of file SelectionDAGNodes.h.
References assert(), DL, and I.
Member Function Documentation
getDebugLoc()
const DebugLoc & llvm::SDLoc::getDebugLoc () const inline
Definition at line 1094 of file SelectionDAGNodes.h.
References DL.
Referenced by llvm::CodeViewDebug::beginInstruction(), createHWLoopAnalysis(), createLVAnalysis(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::WebAssemblyFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyFrameLowering::emitEpilogue(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), errorUnsupported(), fail(), fail(), fail(), llvm::MachineBasicBlock::findBranchDebugLoc(), fixupDebugInfoPostExtraction(), fixupLineNumbers(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAssertAlign(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLabelNode(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::Loop::getLocRange(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getPseudoProbeNode(), llvm::MachineLoop::getStartLoc(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SelectionDAG::getVectorShuffle(), INITIALIZE_PASS(), insertNopBeforeInstruction(), LLVMGetDebugLocColumn(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::BPFInstrInfo::loadRegFromStackSlot(), llvm::LanaiInstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::FunctionLoweringInfo::set(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
getIROrder()
unsigned llvm::SDLoc::getIROrder () const inline
Definition at line 1093 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAssertAlign(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLabelNode(), llvm::SelectionDAG::getLifetimeNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getPseudoProbeNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVectorShuffle().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h