LLVM: llvm::PreservedCFGCheckerInstrumentation Class Reference
llvm::PreservedCFGCheckerInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Static Public Attributes
static cl::opt< bool > VerifyPreservedCFG
Detailed Description
Definition at line 92 of file StandardInstrumentations.h.
Member Function Documentation
registerCallbacks()
void PreservedCFGCheckerInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 791 of file StandardInstrumentations.cpp.
References llvm::PreservedAnalyses::allAnalysesInSetPreserved(), llvm::any_cast(), llvm::any_isa(), assert(), CFG, llvm::dbgs(), IR, llvm::None, P, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::report_fatal_error(), and VerifyPreservedCFG.
Referenced by llvm::StandardInstrumentations::registerCallbacks().
Member Data Documentation
VerifyPreservedCFG
cl::opt< bool > PreservedCFGCheckerInstrumentation::VerifyPreservedCFG static
Definition at line 135 of file StandardInstrumentations.h.
Referenced by registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp