LLVM: llvm::legacy::PassManagerImpl Class Reference
llvm::legacy::PassManagerImpl Class Reference
PassManagerImpl manages MPPassManagers.
Public Member Functions
PassManagerImpl ()
void add (Pass *P)
Add a pass to the queue of passes to run.
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
bool run (Module &M)
run - Execute all of the passes scheduled for execution.
void getAnalysisUsage (AnalysisUsage &Info) const override
Pass Manager itself does not invalidate any analysis info.
PMDataManager * getAsPMDataManager () override
Pass * getAsPass () override
PassManagerType getTopLevelPassManagerType () override
MPPassManager * getContainedManager (unsigned N)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Public Member Functions inherited from llvm::PMDataManager
PMDataManager ()
virtual ~PMDataManager ()
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
Add pass P into the PassVector.
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
Add RequiredPass into list of lower level passes required by pass P.
virtual std::tuple< Pass *, bool > getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAndUsedAnalyses (SmallVectorImpl< Pass * > &UsedPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
Populate UsedPasses with analysis pass that are used or required by pass P and are available.
void initializeAnalysisImpl (Pass *P)
All Required analyses should be available to the pass as it runs! Here we fill in the AnalysisImpls member of the pass so that it can successfully use the getAnalysis() method to retrieve the implementations it needs.
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
Find the pass that implements Analysis AID.
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
void dumpUsedSet (const Pass *P) const
unsigned getNumContainedPasses () const
virtual PassManagerType getPassManagerType () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
unsigned initSizeRemarkInfo (Module &M, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount)
Set the initial size of the module if the user has specified that they want remarks for size.
void emitInstrCountChangedRemark (Pass *P, Module &M, int64_t Delta, unsigned CountBefore, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount, Function *F=nullptr)
Emit a remark signifying that the number of IR instructions in the module changed.
Public Member Functions inherited from llvm::PMTopLevelManager
void schedulePass (Pass *P)
Schedule pass P for execution.
void setLastUser (ArrayRef< Pass * > AnalysisPasses, Pass *P)
Set pass P as the last user of the given analysis passes.
void collectLastUses (SmallVectorImpl< Pass * > &LastUses, Pass *P)
Collect passes whose last user is P.
Pass * findAnalysisPass (AnalysisID AID)
Find the pass that implements Analysis AID.
const PassInfo * findAnalysisPassInfo (AnalysisID AID) const
Retrieve the PassInfo for an analysis.
AnalysisUsage * findAnalysisUsage (Pass *P)
Find analysis usage information for the pass P.
virtual ~PMTopLevelManager ()
Destructor.
void addImmutablePass (ImmutablePass *P)
Add immutable pass and initialize it.
SmallVectorImpl< ImmutablePass * > & getImmutablePasses ()
void addPassManager (PMDataManager *Manager)
void addIndirectPassManager (PMDataManager *Manager)
void dumpPasses () const
void dumpArguments () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::PMTopLevelManager
PMStack activeStack
Protected Member Functions inherited from llvm::PMDataManager
bool isPassDebuggingExecutionsOrMore () const
isPassDebuggingExecutionsOrMore - Return true if -debug-pass=Executions or higher is specified.
Protected Member Functions inherited from llvm::PMTopLevelManager
PMTopLevelManager (PMDataManager *PMDM)
Initialize top level manager. Create first pass manager.
unsigned getNumContainedManagers () const
void initializeAllAnalysisInfo ()
Protected Attributes inherited from llvm::PMDataManager
PMTopLevelManager * TPM
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Protected Attributes inherited from llvm::PMTopLevelManager
SmallVector< PMDataManager *, 8 > PassManagers
Collection of pass managers.
Detailed Description
PassManagerImpl manages MPPassManagers.
Definition at line 473 of file LegacyPassManager.cpp.
Constructor & Destructor Documentation
PassManagerImpl()
llvm::legacy::PassManagerImpl::PassManagerImpl () inline explicit
Definition at line 480 of file LegacyPassManager.cpp.
Member Function Documentation
add()
void llvm::legacy::PassManagerImpl::add (Pass * P) inline
Add a pass to the queue of passes to run.
This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Definition at line 485 of file LegacyPassManager.cpp.
References P, and llvm::PMTopLevelManager::schedulePass().
Referenced by llvm::legacy::PassManager::add().
createPrinterPass()
Pass * llvm::legacy::PassManagerImpl::createPrinterPass (raw_ostream & O, const std::string & Banner) const inline override virtual
createPrinterPass - Get a module printer pass.
Implements llvm::Pass.
Definition at line 490 of file LegacyPassManager.cpp.
References llvm::createPrintModulePass().
getAnalysisUsage()
void llvm::legacy::PassManagerImpl::getAnalysisUsage (AnalysisUsage & Info) const inline override virtual
Pass Manager itself does not invalidate any analysis info.
Reimplemented from llvm::Pass.
Definition at line 503 of file LegacyPassManager.cpp.
getAsPass()
Pass * llvm::legacy::PassManagerImpl::getAsPass () inline override virtual
Implements llvm::PMDataManager.
Definition at line 508 of file LegacyPassManager.cpp.
getAsPMDataManager()
PMDataManager * llvm::legacy::PassManagerImpl::getAsPMDataManager () inline override virtual
Reimplemented from llvm::Pass.
Definition at line 507 of file LegacyPassManager.cpp.
getContainedManager()
MPPassManager * llvm::legacy::PassManagerImpl::getContainedManager (unsigned N) inline
Definition at line 513 of file LegacyPassManager.cpp.
References assert(), N, and llvm::PMTopLevelManager::PassManagers.
Referenced by run().
getTopLevelPassManagerType()
PassManagerType llvm::legacy::PassManagerImpl::getTopLevelPassManagerType () inline override virtual
Implements llvm::PMTopLevelManager.
Definition at line 509 of file LegacyPassManager.cpp.
References llvm::PMT_ModulePassManager.
run()
bool llvm::legacy::PassManagerImpl::run (Module & M)
run - Execute all of the passes scheduled for execution.
Keep track of whether any of the passes modifies the module, and if so, return true.
Definition at line 530 of file LegacyPassManager.cpp.
References Changed, llvm::PMTopLevelManager::dumpArguments(), llvm::PMTopLevelManager::dumpPasses(), getContainedManager(), llvm::PMTopLevelManager::getImmutablePasses(), llvm::PMTopLevelManager::getNumContainedManagers(), Index, and llvm::PMTopLevelManager::initializeAllAnalysisInfo().
Referenced by llvm::legacy::PassManager::run().
Member Data Documentation
ID
char llvm::legacy::PassManagerImpl::ID = 0 static
Definition at line 479 of file LegacyPassManager.cpp.
The documentation for this class was generated from the following file:
lib/IR/LegacyPassManager.cpp