LLVM: llvm::orc::MaterializationUnit Class Reference
llvm::orc::MaterializationUnit Class Reference abstract
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, SymbolStringPtr InitSymbol)
virtual ~MaterializationUnit ()
virtual StringRef getName () const =0
Return the name of this materialization unit.
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
const SymbolStringPtr & getInitializerSymbol () const
Returns the initialization symbol for this MaterializationUnit (if any).
virtual void materialize (std::unique_ptr< MaterializationResponsibility > R)=0
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Protected Attributes
SymbolFlagsMap SymbolFlags
SymbolStringPtr InitSymbol
Friends
class ExecutionSession
class JITDylib
Detailed Description
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
MaterializationUnits are used when providing lazy definitions of symbols to JITDylibs. The JITDylib will call materialize when the address of a symbol is requested via the lookup method. The JITDylib will call discard if a stronger definition is added or already present.
Definition at line 635 of file Core.h.
Constructor & Destructor Documentation
MaterializationUnit()
llvm::orc::MaterializationUnit::MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, SymbolStringPtr InitSymbol) inline
Definition at line 640 of file Core.h.
References assert().
~MaterializationUnit()
virtual llvm::orc::MaterializationUnit::~MaterializationUnit () inline virtual
Definition at line 648 of file Core.h.
Member Function Documentation
doDiscard()
void llvm::orc::MaterializationUnit::doDiscard (const JITDylib & JD, const SymbolStringPtr & Name) inline
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Definition at line 668 of file Core.h.
References Name.
getInitializerSymbol()
const SymbolStringPtr & llvm::orc::MaterializationUnit::getInitializerSymbol () const inline
Returns the initialization symbol for this MaterializationUnit (if any).
Definition at line 658 of file Core.h.
References InitSymbol.
Referenced by llvm::orc::MachOPlatform::notifyAdding().
getName()
virtual StringRef llvm::orc::MaterializationUnit::getName () const pure virtual
Return the name of this materialization unit.
Useful for debugging output.
Implemented in llvm::orc::AbsoluteSymbolsMaterializationUnit, llvm::orc::BasicObjectLayerMaterializationUnit, llvm::orc::IRMaterializationUnit, llvm::orc::LazyReexportsMaterializationUnit, and llvm::orc::ReExportsMaterializationUnit.
Referenced by llvm::orc::MachOPlatform::notifyAdding(), and llvm::orc::operator<<().
getSymbols()
const SymbolFlagsMap & llvm::orc::MaterializationUnit::getSymbols () const inline
Return the set of symbols that this source provides.
Definition at line 655 of file Core.h.
References SymbolFlags.
Referenced by llvm::orc::operator<<().
materialize()
virtual void llvm::orc::MaterializationUnit::materialize (std::unique_ptr< MaterializationResponsibility > R) pure virtual
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
Friends And Related Symbol Documentation
ExecutionSession
friend class ExecutionSession friend
Definition at line 636 of file Core.h.
JITDylib
friend class JITDylib friend
Definition at line 637 of file Core.h.
Member Data Documentation
InitSymbol
SymbolStringPtr llvm::orc::MaterializationUnit::InitSymbol protected
Definition at line 675 of file Core.h.
Referenced by llvm::orc::BasicObjectLayerMaterializationUnit::Create(), getInitializerSymbol(), and llvm::orc::IRMaterializationUnit::IRMaterializationUnit().
SymbolFlags
SymbolFlagsMap llvm::orc::MaterializationUnit::SymbolFlags protected
Definition at line 674 of file Core.h.
Referenced by getSymbols().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp