LLVM: llvm::EHStreamer Class Reference
llvm::EHStreamer Class Reference
Emits exception handling directives.
#include "CodeGen/AsmPrinter/EHStreamer.h"
Classes
struct ActionEntry
Structure describing an entry in the actions table.
struct CallSiteEntry
Structure describing an entry in the call-site table.
struct CallSiteRange
Structure describing a contiguous range of call-sites which reside in the same procedure fragment.
struct PadRange
Structure holding a try-range and the associated landing pad.
Public Member Functions
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void endModule ()=0
Emit all sections that should come after the content.
virtual void beginFunction (const MachineFunction *MF)=0
Gather pre-function debug information.
virtual void markFunctionEnd ()
virtual void endFunction (const MachineFunction *MF)=0
Gather post-function debug information.
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginBasicBlock (const MachineBasicBlock &MBB)
Process beginning of a basic block during basic block sections.
virtual void endBasicBlock (const MachineBasicBlock &MBB)
Process end of a basic block during basic block sections.
Static Public Member Functions
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Protected Types
using RangeMapType = DenseMap<MCSymbol *, PadRange>
Protected Member Functions
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, RangeMapType &PadMap)
virtual void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, SmallVectorImpl< CallSiteRange > &CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > &LandingPads, const SmallVectorImpl< unsigned > &FirstActions)
Compute the call-site table and the call-site ranges.
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Static Protected Member Functions
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Protected Attributes
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Emits exception handling directives.
Definition at line 30 of file EHStreamer.h.
Member Typedef Documentation
RangeMapType
using llvm::EHStreamer::RangeMapType = DenseMap<MCSymbol *, PadRange> protected
Definition at line 51 of file EHStreamer.h.
Constructor & Destructor Documentation
EHStreamer()
EHStreamer::EHStreamer (AsmPrinter * A)
Definition at line 39 of file EHStreamer.cpp.
~EHStreamer()
EHStreamer::~EHStreamer () override default
Member Function Documentation
beginInstruction()
void llvm::EHStreamer::beginInstruction (const MachineInstr * MI) inline override virtual
Process beginning of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 155 of file EHStreamer.h.
callToNoUnwindFunction()
static bool llvm::EHStreamer::callToNoUnwindFunction (const MachineInstr * MI) static
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Return ‘false’ otherwise.
Referenced by computeCallSiteTable().
computeActionsTable()
void EHStreamer::computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > & LandingPads, SmallVectorImpl< ActionEntry > & Actions, SmallVectorImpl< unsigned > & FirstActions) protected
Compute the actions table and gather the first action index for each landing pad site.
Definition at line 54 of file EHStreamer.cpp.
References Asm, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineFunction::getFilterIds(), llvm::getSLEB128Size(), llvm::getULEB128Size(), I, isFilterEHSelector(), llvm::AsmPrinter::MF, Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), sharedTypeIDs(), llvm::SmallVectorBase< Size_T >::size(), and llvm::LandingPadInfo::TypeIds.
Referenced by emitExceptionTable().
computeCallSiteTable()
void EHStreamer::computeCallSiteTable (SmallVectorImpl< CallSiteEntry > & CallSites, SmallVectorImpl< CallSiteRange > & CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > & LandingPads, const SmallVectorImpl< unsigned > & FirstActions) protected virtual
Compute the call-site table and the call-site ranges.
Compute the call-site table.
The entry for an invoke has a try-range containing the call, a non-zero landing pad and an appropriate action. The entry for an ordinary call has a try-range containing the call and zero for the landing pad and the action. Calls marked 'nounwind' have no entry and must not be contained in the try-range of any entry - they form gaps in the table. Entries must be ordered by try-range address. CallSiteRanges vector is only populated for Itanium exception handling.
The entry for an invoke has a try-range containing the call, a non-zero landing pad, and an appropriate action. The entry for an ordinary call has a try-range containing the call and zero for the landing pad and the action. Calls marked 'nounwind' have no entry and must not be contained in the try-range of any entry - they form gaps in the table. Entries must be ordered by try-range address.
Call-sites are split into one or more call-site ranges associated with different sections of the function.
Without -basic-block-sections, all call-sites are grouped into one call-site-range corresponding to the function section.
With -basic-block-sections, one call-site range is created for each section, with its FragmentBeginLabel and FragmentEndLabel respectively
Reimplemented in llvm::WasmException.
Definition at line 231 of file EHStreamer.cpp.
References llvm::EHStreamer::CallSiteEntry::Action, llvm::AIX, Asm, assert(), llvm::MachineFunction::back(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::LandingPadInfo::BeginLabels, callToNoUnwindFunction(), computePadMap(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::EHStreamer::CallSiteEntry::EndLabel, llvm::LandingPadInfo::EndLabels, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineFunction::front(), llvm::MachineFunction::getCallSiteBeginLabel(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::AsmPrinter::getFunctionBegin(), llvm::AsmPrinter::getMBBExceptionSym(), llvm::MachineBasicBlock::getSectionIDNum(), llvm::MachineBasicBlock::isBeginSection(), llvm::MachineBasicBlock::isEHPad(), llvm::MachineBasicBlock::isEndSection(), llvm::LandingPadInfo::LandingPadLabel, llvm::EHStreamer::CallSiteEntry::LPad, llvm::AsmPrinter::MAI, MBB, llvm::AsmPrinter::MBBSectionRanges, llvm::AsmPrinter::MF, MI, P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorBase< Size_T >::size(), llvm::SjLj, and llvm::MCAsmInfo::usesCFIForEH().
Referenced by emitExceptionTable().
computePadMap()
void EHStreamer::computePadMap (const SmallVectorImpl< const LandingPadInfo * > & LandingPads, RangeMapType & PadMap) protected
Definition at line 194 of file EHStreamer.cpp.
References assert(), llvm::LandingPadInfo::BeginLabels, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), E, N, P, and llvm::SmallVectorBase< Size_T >::size().
Referenced by computeCallSiteTable().
emitExceptionTable()
MCSymbol * EHStreamer::emitExceptionTable () protected
Emit landing pads and actions.
The general organization of the table is complex, but the basic concepts are easy. First there is a header which describes the location and organization of the three components that follow.
The landing pad site information describes the range of code covered by the try. In our case it's an accumulation of the ranges covered by the invokes in the try. There is also a reference to the landing pad that handles the exception once processed. Finally an index into the actions table.
The action table, in our case, is composed of pairs of type ids and next action offset. Starting with the action index from the landing pad site, each type Id is checked for a match to the current exception. If it matches then the exception and type id are passed on to the landing pad. Otherwise the next action is looked up. This chain is terminated with a next action of zero. If no type id is found the frame is unwound and handling continues.
Type id table contains references to all the C++ typeinfo for all catches in the function. This tables is reversed indexed base 1.
Returns the starting symbol of an exception table.
The general organization of the table is complex, but the basic concepts are easy. First there is a header which describes the location and organization of the three components that follow.
The landing pad site information describes the range of code covered by the try. In our case it's an accumulation of the ranges covered by the invokes in the try. There is also a reference to the landing pad that handles the exception once processed. Finally an index into the actions table.
The action table, in our case, is composed of pairs of type IDs and next action offset. Starting with the action index from the landing pad site, each type ID is checked for a match to the current exception. If it matches then the exception and type id are passed on to the landing pad. Otherwise the next action is looked up. This chain is terminated with a next action of zero. If no type id is found then the frame is unwound and handling continues.
Type ID table contains references to all the C++ typeinfo for all catches in the function. This tables is reverse indexed base 1.
Returns the starting symbol of an exception table.
Definition at line 381 of file EHStreamer.cpp.
References llvm::EHStreamer::CallSiteEntry::Action, Align, Asm, assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::EHStreamer::CallSiteEntry::BeginLabel, llvm::EHStreamer::CallSiteRange::CallSiteBeginIdx, llvm::EHStreamer::CallSiteRange::CallSiteEndIdx, computeActionsTable(), computeCallSiteTable(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::createTempSymbol(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_pcrel, llvm::dwarf::DW_EH_PE_udata4, E, llvm::AsmPrinter::emitAlignment(), llvm::AsmPrinter::emitCallSiteOffset(), llvm::AsmPrinter::emitCallSiteValue(), llvm::AsmPrinter::emitEncodingByte(), llvm::AsmPrinter::emitLabelDifferenceAsULEB128(), llvm::AsmPrinter::emitSLEB128(), emitTypeInfos(), llvm::AsmPrinter::emitULEB128(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::EHStreamer::CallSiteEntry::EndLabel, llvm::EHStreamer::CallSiteRange::FragmentBeginLabel, llvm::MachineFunction::front(), llvm::TargetLoweringObjectFile::getCallSiteEncoding(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFilterIds(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineFunction::getLandingPads(), llvm::AsmPrinter::getMBBExceptionSym(), llvm::MCSymbol::getName(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), llvm::TargetLoweringObjectFile::getSectionForLSDA(), llvm::AsmPrinter::GetSizeOfEncodedValue(), llvm::getSLEB128Size(), llvm::TargetLoweringObjectFile::getTTypeEncoding(), llvm::MachineFunction::getTypeInfos(), llvm::getULEB128Size(), llvm::MCAsmInfo::hasLEB128Directives(), I, llvm::AsmPrinter::isPositionIndependent(), llvm::isUInt< 32 >(), llvm::LandingPadInfo::LandingPadLabel, llvm::EHStreamer::CallSiteEntry::LPad, llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, N, llvm::EHStreamer::ActionEntry::NextAction, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::EHStreamer::ActionEntry::Previous, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase< Size_T >::size(), llvm::SjLj, llvm::sort(), llvm::AsmPrinter::TM, llvm::LandingPadInfo::TypeIds, llvm::EHStreamer::ActionEntry::ValueForTypeID, and llvm::Wasm.
Referenced by llvm::AIXException::endFunction(), llvm::ARMException::endFunction(), llvm::DwarfCFIException::endFunction(), llvm::WasmException::endFunction(), and llvm::WinException::endFunction().
emitTypeInfos()
void EHStreamer::emitTypeInfos (unsigned TTypeEncoding, MCSymbol * TTBaseLabel) protected virtual
Definition at line 806 of file EHStreamer.cpp.
References Asm, E, llvm::AsmPrinter::emitTTypeReference(), llvm::AsmPrinter::emitULEB128(), llvm::MachineFunction::getFilterIds(), llvm::MachineFunction::getTypeInfos(), I, isFilterEHSelector(), llvm::make_range(), llvm::AsmPrinter::MF, and llvm::AsmPrinter::OutStreamer.
Referenced by emitExceptionTable().
endInstruction()
void llvm::EHStreamer::endInstruction () inline override virtual
Process end of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 156 of file EHStreamer.h.
isCatchEHSelector()
static bool llvm::EHStreamer::isCatchEHSelector (int Selector) inline static protected
Definition at line 147 of file EHStreamer.h.
isCleanupEHSelector()
static bool llvm::EHStreamer::isCleanupEHSelector (int Selector) inline static protected
Definition at line 146 of file EHStreamer.h.
isFilterEHSelector()
static bool llvm::EHStreamer::isFilterEHSelector (int Selector) inline static protected
Definition at line 145 of file EHStreamer.h.
Referenced by computeActionsTable(), and emitTypeInfos().
setSymbolSize()
void llvm::EHStreamer::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline override virtual
For symbols that have a size designated (e.g.
common symbols), this tracks that size.
Implements llvm::AsmPrinterHandler.
Definition at line 154 of file EHStreamer.h.
sharedTypeIDs()
unsigned EHStreamer::sharedTypeIDs (const LandingPadInfo * L, const LandingPadInfo * R) static protected
How many leading type ids two landing pads have in common.
Definition at line 44 of file EHStreamer.cpp.
References llvm::LandingPadInfo::TypeIds.
Referenced by computeActionsTable().
Member Data Documentation
Asm
AsmPrinter* llvm::EHStreamer::Asm protected
Target of directive emission.
Definition at line 33 of file EHStreamer.h.
Referenced by llvm::DwarfCFIException::beginFragment(), llvm::WinException::beginFunclet(), llvm::ARMException::beginFunction(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), computeActionsTable(), computeCallSiteTable(), llvm::WasmException::computeCallSiteTable(), emitExceptionTable(), emitTypeInfos(), llvm::DwarfCFIException::endBasicBlock(), llvm::DwarfCFIExceptionBase::endFragment(), llvm::WinException::endFunclet(), llvm::AIXException::endFunction(), llvm::ARMException::endFunction(), llvm::WasmException::endFunction(), llvm::WinException::endFunction(), llvm::DwarfCFIException::endModule(), llvm::WasmException::endModule(), llvm::WinException::endModule(), llvm::DwarfCFIExceptionBase::markFunctionEnd(), llvm::WasmException::markFunctionEnd(), llvm::WinException::markFunctionEnd(), and llvm::WinException::WinException().
MMI
MachineModuleInfo* llvm::EHStreamer::MMI protected
Collected machine module information.
Definition at line 36 of file EHStreamer.h.
Referenced by llvm::DwarfCFIException::beginFragment(), llvm::WinException::beginFunclet(), llvm::DwarfCFIException::endModule(), and llvm::WinException::endModule().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/EHStreamer.h
lib/CodeGen/AsmPrinter/EHStreamer.cpp