LLVM: llvm::generic_gep_type_iterator< T > Class Template Reference
llvm::generic_gep_type_iterator< T > Class Template Reference
#include "llvm/IR/GetElementPtrTypeIterator.h"
Public Member Functions
bool operator== (const generic_gep_type_iterator &x) const
bool operator!= (const generic_gep_type_iterator &x) const
Type * getIndexedType () const
Value * getOperand () const
generic_gep_type_iterator & operator++ ()
generic_gep_type_iterator operator++ (int)
bool isStruct () const
bool isSequential () const
StructType * getStructType () const
StructType * getStructTypeOrNull () const
bool isBoundedSequential () const
uint64_t getSequentialNumElements () const
Static Public Member Functions
static generic_gep_type_iterator begin (Type *Ty, ItTy It)
static generic_gep_type_iterator end (ItTy It)
Detailed Description
template<typename T>
class llvm::generic_gep_type_iterator< T >
Definition at line 27 of file Interpreter.h.
Member Function Documentation
begin()
template<typename T > static generic_gep_type_iterator llvm::generic_gep_type_iterator< T >::begin (Type * Ty, ItTy It) inline static
Definition at line 43 of file GetElementPtrTypeIterator.h.
References I.
Referenced by llvm::gep_type_begin(), llvm::gep_type_begin(), and llvm::gep_type_begin().
end()
template<typename T > static generic_gep_type_iterator llvm::generic_gep_type_iterator< T >::end (ItTy It) inline static
Definition at line 50 of file GetElementPtrTypeIterator.h.
References I.
Referenced by llvm::gep_type_end(), llvm::gep_type_end(), and llvm::gep_type_end().
getIndexedType()
template<typename T > Type * llvm::generic_gep_type_iterator< T >::getIndexedType () const inline
Definition at line 68 of file GetElementPtrTypeIterator.h.
References llvm::generic_gep_type_iterator< T >::getOperand(), and T.
Referenced by computeKnownBitsFromOperator(), llvm::EmitGEPOffset(), evaluateGEPOffsetExpression(), evaluateICmpRelation(), llvm::getGEPInductionOperand(), llvm::DataLayout::getIndexedOffsetInType(), getOffsetFromIndex(), llvm::generic_gep_type_iterator< T >::operator++(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
getOperand()
template<typename T > Value * llvm::generic_gep_type_iterator< T >::getOperand () const inline
Definition at line 74 of file GetElementPtrTypeIterator.h.
Referenced by llvm::DataLayout::getIndexedOffsetInType(), llvm::generic_gep_type_iterator< T >::getIndexedType(), and isSafeSROAGEP().
getSequentialNumElements()
template<typename T > uint64_t llvm::generic_gep_type_iterator< T >::getSequentialNumElements () const inline
Definition at line 125 of file GetElementPtrTypeIterator.h.
References assert(), and llvm::generic_gep_type_iterator< T >::isBoundedSequential().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), and isSafeSROAGEP().
getStructType()
template<typename T > StructType * llvm::generic_gep_type_iterator< T >::getStructType () const inline
Definition at line 115 of file GetElementPtrTypeIterator.h.
References llvm::StructType::get().
getStructTypeOrNull()
template<typename T > StructType * llvm::generic_gep_type_iterator< T >::getStructTypeOrNull () const inline
Definition at line 117 of file GetElementPtrTypeIterator.h.
Referenced by computeKnownBitsFromOperator(), llvm::EmitGEPOffset(), evaluateGEPOffsetExpression(), llvm::DataLayout::getIndexedOffsetInType(), and getOffsetFromIndex().
isBoundedSequential()
template<typename T > bool llvm::generic_gep_type_iterator< T >::isBoundedSequential () const inline
Definition at line 121 of file GetElementPtrTypeIterator.h.
References llvm::generic_gep_type_iterator< T >::isSequential().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::generic_gep_type_iterator< T >::getSequentialNumElements(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), and isSafeSROAGEP().
isSequential()
template<typename T > bool llvm::generic_gep_type_iterator< T >::isSequential () const inline
Definition at line 113 of file GetElementPtrTypeIterator.h.
Referenced by llvm::ConstantFoldGetElementPtr(), and llvm::generic_gep_type_iterator< T >::isBoundedSequential().
isStruct()
template<typename T > bool llvm::generic_gep_type_iterator< T >::isStruct () const inline
Definition at line 112 of file GetElementPtrTypeIterator.h.
Referenced by llvm::canReplaceOperandWithVariable(), isSafeSROAGEP(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
operator!=()
template<typename T > bool llvm::generic_gep_type_iterator< T >::operator!= (const generic_gep_type_iterator< T > & x) const inline
Definition at line 60 of file GetElementPtrTypeIterator.h.
References llvm::generic_gep_type_iterator< T >::operator==().
operator++() [1/2]
template<typename T > generic_gep_type_iterator & llvm::generic_gep_type_iterator< T >::operator++ () inline
Definition at line 76 of file GetElementPtrTypeIterator.h.
References llvm::cast(), llvm::dyn_cast(), llvm::generic_gep_type_iterator< T >::getIndexedType(), and llvm::isa().
operator++() [2/2]
template<typename T > generic_gep_type_iterator llvm::generic_gep_type_iterator< T >::operator++ (int) inline
Definition at line 93 of file GetElementPtrTypeIterator.h.
operator==()
template<typename T > bool llvm::generic_gep_type_iterator< T >::operator== (const generic_gep_type_iterator< T > & x) const inline
Definition at line 56 of file GetElementPtrTypeIterator.h.
Referenced by llvm::generic_gep_type_iterator< T >::operator!=().
The documentation for this class was generated from the following files:
include/llvm/IR/GetElementPtrTypeIterator.h
lib/ExecutionEngine/Interpreter/Interpreter.h