LLVM: llvm::IRChangedPrinter Class Reference
llvm::IRChangedPrinter Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
IRChangedPrinter (bool VerboseMode)
~IRChangedPrinter () override
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Public Member Functions inherited from llvm::ChangeReporter< std::string >
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID)
void handleIRAfterPass (Any IR, StringRef PassID)
void handleInvalidatedPass (StringRef PassID)
Protected Member Functions
void generateIRRepresentation (Any IR, StringRef PassID, std::string &Output) override
void handleAfter (StringRef PassID, std::string &Name, const std::string &Before, const std::string &After, Any) override
bool same (const std::string &Before, const std::string &After) override
Protected Member Functions inherited from llvm::TextChangeReporter< std::string >
TextChangeReporter (bool Verbose)
void handleInitialIR (Any IR) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
Protected Member Functions inherited from llvm::ChangeReporter< std::string >
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
bool isInterestingFunction (const Function &F)
bool isInterestingPass (StringRef PassID)
bool isInteresting (Any IR, StringRef PassID)
Additional Inherited Members
Protected Attributes inherited from llvm::TextChangeReporter< std::string >
raw_ostream & Out
Protected Attributes inherited from llvm::ChangeReporter< std::string >
std::vector< std::string > BeforeStack
bool InitialIR
const bool VerboseMode
Detailed Description
Definition at line 240 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
IRChangedPrinter()
llvm::IRChangedPrinter::IRChangedPrinter (bool VerboseMode) inline
Definition at line 242 of file StandardInstrumentations.h.
~IRChangedPrinter()
IRChangedPrinter::~IRChangedPrinter () override
Definition at line 415 of file StandardInstrumentations.cpp.
Member Function Documentation
generateIRRepresentation()
void IRChangedPrinter::generateIRRepresentation (Any IR, StringRef PassID, std::string & Output) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 422 of file StandardInstrumentations.cpp.
References llvm::forcePrintModuleIR(), llvm::formatv(), IR, and llvm::raw_string_ostream::str().
handleAfter()
void IRChangedPrinter::handleAfter (StringRef PassID, std::string & Name, const std::string & Before, const std::string & After, Any) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 433 of file StandardInstrumentations.cpp.
References assert(), C, llvm::forcePrintModuleIR(), Name, llvm::TextChangeReporter< std::string >::Out, PrintChangedBefore, llvm::StringRef::size(), llvm::StringRef::substr(), and llvm::StringRef::take_until().
registerCallbacks()
void IRChangedPrinter::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 417 of file StandardInstrumentations.cpp.
References NoChangePrinter, PrintChanged, and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
same()
bool IRChangedPrinter::same (const std::string & Before, const std::string & After) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 463 of file StandardInstrumentations.cpp.
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp