LLVM: llvm::MemorySSA::CachingWalker< AliasAnalysisType > Class Template Reference
llvm::MemorySSA::CachingWalker< AliasAnalysisType > Class Template Reference final
A MemorySSAWalker that does AA walks to disambiguate accesses.
Public Member Functions
CachingWalker (MemorySSA *M, ClobberWalkerBase< AliasAnalysisType > *W)
~CachingWalker () override=default
MemoryAccess * getClobberingMemoryAccess (MemoryAccess *MA, unsigned &UWL)
MemoryAccess * getClobberingMemoryAccess (MemoryAccess *MA, const MemoryLocation &Loc, unsigned &UWL)
MemoryAccess * getClobberingMemoryAccess (MemoryAccess *MA) override
Does the same thing as getClobberingMemoryAccess(const Instruction *I), but takes a MemoryAccess instead of an Instruction.
MemoryAccess * getClobberingMemoryAccess (MemoryAccess *MA, const MemoryLocation &Loc) override
Given a potentially clobbering memory access and a new location, calling this will give you the nearest dominating clobbering MemoryAccess (by skipping non-aliasing def links).
void invalidateInfo (MemoryAccess *MA) override
Given a memory access, invalidate anything this walker knows about that access.
MemoryAccess * getClobberingMemoryAccess (const Instruction *I)
Given a memory Mod/Ref/ModRef'ing instruction, calling this will give you the nearest dominating MemoryAccess that Mod's the location the instruction accesses (by skipping any def which AA can prove does not alias the location(s) accessed by the instruction given).
Public Member Functions inherited from llvm::MemorySSAWalker
MemorySSAWalker (MemorySSA *)
virtual ~MemorySSAWalker ()=default
MemoryAccess * getClobberingMemoryAccess (const Instruction *I)
Given a memory Mod/Ref/ModRef'ing instruction, calling this will give you the nearest dominating MemoryAccess that Mod's the location the instruction accesses (by skipping any def which AA can prove does not alias the location(s) accessed by the instruction given).
Additional Inherited Members
Public Types inherited from llvm::MemorySSAWalker
using MemoryAccessSet = SmallVector<MemoryAccess *, 8>
Protected Attributes inherited from llvm::MemorySSAWalker
MemorySSA * MSSA
Detailed Description
template<class AliasAnalysisType>
class llvm::MemorySSA::CachingWalker< AliasAnalysisType >
A MemorySSAWalker that does AA walks to disambiguate accesses.
It no longer does caching on its own, but the name has been retained for the moment.
Definition at line 1024 of file MemorySSA.cpp.
Constructor & Destructor Documentation
CachingWalker()
template<class AliasAnalysisType > llvm::MemorySSA::CachingWalker< AliasAnalysisType >::CachingWalker (MemorySSA * M, ClobberWalkerBase< AliasAnalysisType > * W) inline
Definition at line 1028 of file MemorySSA.cpp.
~CachingWalker()
template<class AliasAnalysisType > llvm::MemorySSA::CachingWalker< AliasAnalysisType >::~CachingWalker () override default
Member Function Documentation
getClobberingMemoryAccess() [1/5]
template<class AliasAnalysisType > MemoryAccess * llvm::MemorySSAWalker::getClobberingMemoryAccess (const Instruction * I) inline
Given a memory Mod/Ref/ModRef'ing instruction, calling this will give you the nearest dominating MemoryAccess that Mod's the location the instruction accesses (by skipping any def which AA can prove does not alias the location(s) accessed by the instruction given).
Note that this will return a single access, and it must dominate the Instruction, so if an operand of a MemoryPhi node Mod's the instruction, this will return the MemoryPhi, not the operand. This means that given: if (a) { 1 = MemoryDef(liveOnEntry) store a } else { 2 = MemoryDef(liveOnEntry) store b } 3 = MemoryPhi(2, 1) MemoryUse(3) load a
calling this API on load(a) will return the MemoryPhi, not the MemoryDef in the if (a) branch.
Definition at line 1020 of file MemorySSA.h.
getClobberingMemoryAccess() [2/5]
template<class AliasAnalysisType > MemoryAccess * llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess (MemoryAccess *) inline override virtual
Does the same thing as getClobberingMemoryAccess(const Instruction *I), but takes a MemoryAccess instead of an Instruction.
Implements llvm::MemorySSAWalker.
Definition at line 1043 of file MemorySSA.cpp.
References llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess(), and MaxCheckLimit().
getClobberingMemoryAccess() [3/5]
template<class AliasAnalysisType > MemoryAccess * llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess (MemoryAccess * , const MemoryLocation &) inline override virtual
Given a potentially clobbering memory access and a new location, calling this will give you the nearest dominating clobbering MemoryAccess (by skipping non-aliasing def links).
This version of the function is mainly used to disambiguate phi translated pointers, where the value of a pointer may have changed from the initial memory access. Note that this expects to be handed either a MemoryUse, or an already potentially clobbering access. Unlike the above API, if given a MemoryDef that clobbers the pointer as the starting access, it will return that MemoryDef, whereas the above would return the clobber starting from the use side of the memory def.
Implements llvm::MemorySSAWalker.
Definition at line 1047 of file MemorySSA.cpp.
References llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess(), and MaxCheckLimit().
getClobberingMemoryAccess() [4/5]
template<class AliasAnalysisType > MemoryAccess * llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess (MemoryAccess * MA, const MemoryLocation & Loc, unsigned & UWL) inline
Definition at line 1037 of file MemorySSA.cpp.
getClobberingMemoryAccess() [5/5]
template<class AliasAnalysisType > MemoryAccess * llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess (MemoryAccess * MA, unsigned & UWL) inline
Definition at line 1034 of file MemorySSA.cpp.
Referenced by llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess(), and llvm::MemorySSA::CachingWalker< AliasAnalysisType >::getClobberingMemoryAccess().
invalidateInfo()
template<class AliasAnalysisType > void llvm::MemorySSA::CachingWalker< AliasAnalysisType >::invalidateInfo (MemoryAccess *) inline override virtual
Given a memory access, invalidate anything this walker knows about that access.
This API is used by walkers that store information to perform basic cache invalidation. This will be called by MemorySSA at appropriate times for the walker it uses or returns.
Reimplemented from llvm::MemorySSAWalker.
Definition at line 1053 of file MemorySSA.cpp.
References llvm::dyn_cast().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp