LLVM: llvm::MaximumSpanningTree< T > Class Template Reference
llvm::MaximumSpanningTree< T > Class Template Reference
MaximumSpanningTree - A MST implementation.
#include "Transforms/Instrumentation/MaximumSpanningTree.h"
Public Types
typedef std::pair< const T *, const T * > Edge
typedef std::pair< Edge, double > EdgeWeight
typedef std::vector< EdgeWeight > EdgeWeights
Public Member Functions
MaximumSpanningTree (EdgeWeights &EdgeVector)
MaximumSpanningTree() - Takes a vector of weighted edges and returns a spanning tree.
MaxSpanTree::iterator begin ()
MaxSpanTree::iterator end ()
Static Public Attributes
static char ID
Protected Types
typedef std::vector< Edge > MaxSpanTree
Protected Attributes
MaxSpanTree MST
Detailed Description
template<typename T>
class llvm::MaximumSpanningTree< T >
MaximumSpanningTree - A MST implementation.
The type parameter T determines the type of the nodes of the graph.
Definition at line 27 of file MaximumSpanningTree.h.
Member Typedef Documentation
Edge
template<typename T > std::pair<const T*, const T*> llvm::MaximumSpanningTree< T >::Edge
Definition at line 29 of file MaximumSpanningTree.h.
EdgeWeight
template<typename T > std::pair<Edge, double> llvm::MaximumSpanningTree< T >::EdgeWeight
Definition at line 30 of file MaximumSpanningTree.h.
EdgeWeights
template<typename T > std::vector<EdgeWeight> llvm::MaximumSpanningTree< T >::EdgeWeights
Definition at line 31 of file MaximumSpanningTree.h.
MaxSpanTree
template<typename T > std::vector<Edge> llvm::MaximumSpanningTree< T >::MaxSpanTree protected
Definition at line 33 of file MaximumSpanningTree.h.
Constructor & Destructor Documentation
MaximumSpanningTree()
template<typename T > llvm::MaximumSpanningTree< T >::MaximumSpanningTree (EdgeWeights & EdgeVector) inline
MaximumSpanningTree() - Takes a vector of weighted edges and returns a spanning tree.
Definition at line 69 of file MaximumSpanningTree.h.
References llvm::EquivalenceClasses< ElemTy >::findLeader(), llvm::EquivalenceClasses< ElemTy >::insert(), llvm::MaximumSpanningTree< T >::MST, llvm::stable_sort(), and llvm::EquivalenceClasses< ElemTy >::unionSets().
Member Function Documentation
begin()
template<typename T > MaxSpanTree::iterator llvm::MaximumSpanningTree< T >::begin () inline
Definition at line 98 of file MaximumSpanningTree.h.
References llvm::MaximumSpanningTree< T >::MST.
end()
template<typename T > MaxSpanTree::iterator llvm::MaximumSpanningTree< T >::end () inline
Definition at line 102 of file MaximumSpanningTree.h.
References llvm::MaximumSpanningTree< T >::MST.
Member Data Documentation
ID
template<typename T > char llvm::MaximumSpanningTree< T >::ID static
Definition at line 65 of file MaximumSpanningTree.h.
MST
template<typename T > MaxSpanTree llvm::MaximumSpanningTree< T >::MST protected
Definition at line 35 of file MaximumSpanningTree.h.
Referenced by llvm::MaximumSpanningTree< T >::begin(), llvm::MaximumSpanningTree< T >::end(), and llvm::MaximumSpanningTree< T >::MaximumSpanningTree().
The documentation for this class was generated from the following file:
lib/Transforms/Instrumentation/MaximumSpanningTree.h