LLVM: llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/RPCUtils.h"
Public Types
template<typename Func >
using NonBlockingCallResult
Return type for non-blocking call primitives.
Public Member Functions
MultiThreadedRPCEndpoint (ChannelT &C, bool LazyAutoNegotiation)
template<typename Func , typename HandlerT >
void addHandler (HandlerT Handler)
Add a handler for the given RPC function.
template<typename Func , typename ClassT , typename RetT , typename... ArgTs>
void addHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
Add a class-method as a handler.
template<typename Func , typename HandlerT >
void addAsyncHandler (HandlerT Handler)
template<typename Func , typename ClassT , typename RetT , typename... ArgTs>
void addAsyncHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
Add a class-method as a handler.
template<typename Func , typename... ArgTs>
Expected< NonBlockingCallResult< Func > > appendCallNB (const ArgTs &...Args)
Call Func on Channel C.
template<typename Func , typename... ArgTs>
Expected< NonBlockingCallResult< Func > > callNB (const ArgTs &...Args)
The same as appendCallNBWithSeq, except that it calls C.send() to flush the channel after serializing the call.
template<typename Func , typename... ArgTs, typename AltRetT = typename Func::ReturnType>
detail::ResultTraits< AltRetT >::ErrorReturnType callB (const ArgTs &...Args)
Call Func on Channel C.
Error handlerLoop ()
Handle incoming RPC calls.
Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
RPCEndpointBase (ChannelT &C, bool LazyAutoNegotiation)
Construct an RPC instance on a channel.
Error negotiateFunction (bool Retry=false)
Negotiate a function id for Func with the other end of the channel.
Error appendCallAsync (HandlerT Handler, const ArgTs &...Args)
Append a call Func, does not call send on the channel.
Error sendAppendedCalls ()
Error callAsync (HandlerT Handler, const ArgTs &...Args)
Error handleOne ()
Handle one incoming call.
void abandonPendingResponses ()
Abandon all outstanding result handlers.
void removeHandler ()
Remove the handler for the given function.
void clearHandlers ()
Clear all handlers.
Additional Inherited Members
Static Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
static detail::ReadArgs< ArgTs... > readArgs (ArgTs &...Args)
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args... to values deserialized from the channel.
Protected Types inherited from llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
using WrappedHandlerFn
Protected Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
uint32_t getInvalidFunctionId () const
void addHandlerImpl (HandlerT Handler)
Add the given handler to the handler map and make it available for autonegotiation and execution.
void addAsyncHandlerImpl (HandlerT Handler)
Error handleResponse (uint32_t SeqNo)
uint32_t handleNegotiate (const std::string &Name)
Expected< uint32_t > getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid)
WrappedHandlerFn wrapHandler (HandlerT Handler)
WrappedHandlerFn wrapAsyncHandler (HandlerT Handler)
Protected Attributes inherited from llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
ChannelT & C
bool LazyAutoNegotiation
RPCFunctionIdAllocator< uint32_t > FnIdAllocator
uint32_t ResponseId
std::map< std::string, uint32_t > LocalFunctionIds
std::map< const char *, uint32_t > RemoteFunctionIds
std::map< uint32_t, WrappedHandlerFn > Handlers
std::mutex ResponsesMutex
detail::SequenceNumberManager< uint32_t > SequenceNumberMgr
std::map< uint32_t, std::unique_ptr< detail::ResponseHandler< ChannelT > > > PendingResponses
Detailed Description
template<typename ChannelT, typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t>
class llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >
Definition at line 1341 of file RPCUtils.h.
Member Typedef Documentation
NonBlockingCallResult
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func > using llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::NonBlockingCallResult
Initial value:
 typename detail::ResultTraits<
      typename Func::ReturnType>::ReturnFutureType
Return type for non-blocking call primitives.
Definition at line 1383 of file RPCUtils.h.
Constructor & Destructor Documentation
MultiThreadedRPCEndpoint()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::MultiThreadedRPCEndpoint (ChannelT & C, bool LazyAutoNegotiation) inline
Definition at line 1351 of file RPCUtils.h.
Member Function Documentation
addAsyncHandler() [1/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename ClassT , typename RetT , typename... ArgTs> void llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler (ClassT & Object, RetT(ClassT::* Method)(ArgTs...)) inline
Add a class-method as a handler.
Definition at line 1376 of file RPCUtils.h.
References llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler(), and llvm::Object.
addAsyncHandler() [2/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename HandlerT > void llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler (HandlerT Handler) inline
Definition at line 1370 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::addAsyncHandlerImpl().
Referenced by llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler().
addHandler() [1/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename ClassT , typename RetT , typename... ArgTs> void llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler (ClassT & Object, RetT(ClassT::* Method)(ArgTs...)) inline
Add a class-method as a handler.
Definition at line 1364 of file RPCUtils.h.
References llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler(), and llvm::Object.
addHandler() [2/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename HandlerT > void llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler (HandlerT Handler) inline
Add a handler for the given RPC function.
This installs the given handler functor for the given RPCFunction, and makes the RPC function available for negotiation/calling from the remote.
Definition at line 1358 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::addHandlerImpl().
Referenced by llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler().
appendCallNB()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename... ArgTs> Expected< NonBlockingCallResult< Func > > llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::appendCallNB (const ArgTs &... Args) inline
Call Func on Channel C.
Does not block, does not call send. Returns a pair of a future result and the sequence number assigned to the result.
This utility function is primarily used for single-threaded mode support, where the sequence number can be used to wait for the corresponding result. In multi-threaded mode the appendCallNB method, which does not return the sequence numeber, should be preferred.
Definition at line 1394 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::appendCallAsync(), and llvm::Error::success().
Referenced by llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB().
callB()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename... ArgTs, typename AltRetT = typename Func::ReturnType> detail::ResultTraits< AltRetT >::ErrorReturnType llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB (const ArgTs &... Args) inline
Call Func on Channel C.
Blocks waiting for a result. Returns an Error for void functions or an Expected<T> for functions returning a T.
This function is for use in threaded code where another thread is handling responses and incoming calls.
Definition at line 1438 of file RPCUtils.h.
References llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB().
callNB()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename... ArgTs> Expected< NonBlockingCallResult< Func > > llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB (const ArgTs &... Args) inline
The same as appendCallNBWithSeq, except that it calls C.send() to flush the channel after serializing the call.
Definition at line 1417 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::abandonPendingResponses(), llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::appendCallNB(), and llvm::orc::shared::detail::ResultTraits< RetT >::consumeAbandoned().
Referenced by llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB().
handlerLoop()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> Error llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::handlerLoop () inline
Handle incoming RPC calls.
Definition at line 1446 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< MultiThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::handleOne(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h