LLVM: llvm::StringAttributeImpl Class Reference
llvm::StringAttributeImpl Class Reference final
#include "IR/AttributeImpl.h"
Public Member Functions
StringAttributeImpl (StringRef Kind, StringRef Val=StringRef())
StringRef getStringKind () const
StringRef getStringValue () const
Public Member Functions inherited from llvm::AttributeImpl
AttributeImpl (const AttributeImpl &)=delete
AttributeImpl & operator= (const AttributeImpl &)=delete
bool isEnumAttribute () const
bool isIntAttribute () const
bool isStringAttribute () const
bool isTypeAttribute () const
bool hasAttribute (Attribute::AttrKind A) const
bool hasAttribute (StringRef Kind) const
Attribute::AttrKind getKindAsEnum () const
uint64_t getValueAsInt () const
StringRef getKindAsString () const
StringRef getValueAsString () const
Type * getValueAsType () const
bool operator< (const AttributeImpl &AI) const
Used when sorting the attributes.
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static size_t totalSizeToAlloc (StringRef Kind, StringRef Val)
Static Public Member Functions inherited from llvm::AttributeImpl
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, uint64_t Val)
static void Profile (FoldingSetNodeID &ID, StringRef Kind, StringRef Values)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, Type *Ty)
Additional Inherited Members
Protected Types inherited from llvm::AttributeImpl
enum AttrEntryKind { EnumAttrEntry , IntAttrEntry , StringAttrEntry , TypeAttrEntry }
Protected Member Functions inherited from llvm::AttributeImpl
AttributeImpl (AttrEntryKind KindID)
Detailed Description
Definition at line 145 of file AttributeImpl.h.
Constructor & Destructor Documentation
StringAttributeImpl()
llvm::StringAttributeImpl::StringAttributeImpl (StringRef Kind, StringRef Val = StringRef()) inline
Definition at line 157 of file AttributeImpl.h.
References llvm::copy(), and llvm::TrailingObjects< StringAttributeImpl, char >::getTrailingObjects().
Member Function Documentation
getStringKind()
StringRef llvm::StringAttributeImpl::getStringKind () const inline
Definition at line 168 of file AttributeImpl.h.
References llvm::TrailingObjects< StringAttributeImpl, char >::getTrailingObjects().
getStringValue()
StringRef llvm::StringAttributeImpl::getStringValue () const inline
Definition at line 171 of file AttributeImpl.h.
References llvm::TrailingObjects< StringAttributeImpl, char >::getTrailingObjects().
totalSizeToAlloc()
static size_t llvm::StringAttributeImpl::totalSizeToAlloc (StringRef Kind, StringRef Val) inline static
Definition at line 175 of file AttributeImpl.h.
References llvm::StringRef::size(), and llvm::TrailingObjects< BaseTy, TrailingTys >::totalSizeToAlloc().
Referenced by llvm::Attribute::get().
The documentation for this class was generated from the following file:
lib/IR/AttributeImpl.h