LLVM: llvm::Combiner Class Reference
llvm::Combiner Class Reference
#include "llvm/CodeGen/GlobalISel/Combiner.h"
Public Member Functions
Combiner (CombinerInfo &CombinerInfo, const TargetPassConfig *TPC)
bool combineMachineInstrs (MachineFunction &MF, GISelCSEInfo *CSEInfo)
If CSEInfo is not null, then the Combiner will setup observer for CSEInfo and instantiate a CSEMIRBuilder.
Protected Attributes
CombinerInfo & CInfo
MachineRegisterInfo * MRI = nullptr
const TargetPassConfig * TPC
std::unique_ptr< MachineIRBuilder > Builder
Detailed Description
Definition at line 27 of file Combiner.h.
Constructor & Destructor Documentation
Combiner()
Combiner::Combiner (CombinerInfo & CombinerInfo, const TargetPassConfig * TPC)
Definition at line 93 of file Combiner.cpp.
References TPC.
Member Function Documentation
combineMachineInstrs()
bool Combiner::combineMachineInstrs (MachineFunction & MF, GISelCSEInfo * CSEInfo)
If CSEInfo is not null, then the Combiner will setup observer for CSEInfo and instantiate a CSEMIRBuilder.
Pass nullptr if CSE is not needed.
Definition at line 98 of file Combiner.cpp.
References llvm::GISelObserverWrapper::addObserver(), assert(), B, Changed, CInfo, llvm::CombinerInfo::combine(), llvm::dbgs(), llvm::GISelWorkList< N >::deferred_insert(), llvm::GISelWorkList< N >::empty(), llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::errorToBool(), llvm::MachineFunctionProperties::FailedISel, llvm::GISelWorkList< N >::finalize(), llvm::MachineFunction::getName(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunctionProperties::hasProperty(), llvm::isTriviallyDead(), LLVM_DEBUG, MBB, MORE, MRI, llvm::GISelWorkList< N >::pop_back_val(), llvm::post_order(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), and llvm::GISelCSEInfo::verify().
Member Data Documentation
Builder
std::unique_ptr<MachineIRBuilder> llvm::Combiner::Builder protected
Definition at line 41 of file Combiner.h.
CInfo
CombinerInfo& llvm::Combiner::CInfo protected
Definition at line 37 of file Combiner.h.
Referenced by combineMachineInstrs().
MRI
MachineRegisterInfo* llvm::Combiner::MRI = nullptr protected
Definition at line 39 of file Combiner.h.
Referenced by combineMachineInstrs().
TPC
const TargetPassConfig* llvm::Combiner::TPC protected
Definition at line 40 of file Combiner.h.
Referenced by Combiner().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/Combiner.h
lib/CodeGen/GlobalISel/Combiner.cpp