LLVM: llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/RPCUtils.h"
Public Member Functions
SingleThreadedRPCEndpoint (ChannelT &C, bool LazyAutoNegotiation)
template<typename Func , typename HandlerT >
void addHandler (HandlerT Handler)
template<typename Func , typename ClassT , typename RetT , typename... ArgTs>
void addHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
template<typename Func , typename HandlerT >
void addAsyncHandler (HandlerT Handler)
template<typename Func , typename ClassT , typename RetT , typename... ArgTs>
void addAsyncHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
Add a class-method as a handler.
template<typename Func , typename... ArgTs, typename AltRetT = typename Func::ReturnType>
detail::ResultTraits< AltRetT >::ErrorReturnType callB (const ArgTs &...Args)
Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
RPCEndpointBase (ChannelT &C, bool LazyAutoNegotiation)
Construct an RPC instance on a channel.
Error negotiateFunction (bool Retry=false)
Negotiate a function id for Func with the other end of the channel.
Error appendCallAsync (HandlerT Handler, const ArgTs &...Args)
Append a call Func, does not call send on the channel.
Error sendAppendedCalls ()
Error callAsync (HandlerT Handler, const ArgTs &...Args)
Error handleOne ()
Handle one incoming call.
void abandonPendingResponses ()
Abandon all outstanding result handlers.
void removeHandler ()
Remove the handler for the given function.
void clearHandlers ()
Clear all handlers.
Additional Inherited Members
Static Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
static detail::ReadArgs< ArgTs... > readArgs (ArgTs &...Args)
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args... to values deserialized from the channel.
Protected Types inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
using WrappedHandlerFn
Protected Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
uint32_t getInvalidFunctionId () const
void addHandlerImpl (HandlerT Handler)
Add the given handler to the handler map and make it available for autonegotiation and execution.
void addAsyncHandlerImpl (HandlerT Handler)
Error handleResponse (uint32_t SeqNo)
uint32_t handleNegotiate (const std::string &Name)
Expected< uint32_t > getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid)
WrappedHandlerFn wrapHandler (HandlerT Handler)
WrappedHandlerFn wrapAsyncHandler (HandlerT Handler)
Protected Attributes inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >
ChannelT & C
bool LazyAutoNegotiation
RPCFunctionIdAllocator< uint32_t > FnIdAllocator
uint32_t ResponseId
std::map< std::string, uint32_t > LocalFunctionIds
std::map< const char *, uint32_t > RemoteFunctionIds
std::map< uint32_t, WrappedHandlerFn > Handlers
std::mutex ResponsesMutex
detail::SequenceNumberManager< uint32_t > SequenceNumberMgr
std::map< uint32_t, std::unique_ptr< detail::ResponseHandler< ChannelT > > > PendingResponses
Detailed Description
template<typename ChannelT, typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t>
class llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >
Definition at line 1456 of file RPCUtils.h.
Constructor & Destructor Documentation
SingleThreadedRPCEndpoint()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::SingleThreadedRPCEndpoint (ChannelT & C, bool LazyAutoNegotiation) inline
Definition at line 1466 of file RPCUtils.h.
Member Function Documentation
addAsyncHandler() [1/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename ClassT , typename RetT , typename... ArgTs> void llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler (ClassT & Object, RetT(ClassT::* Method)(ArgTs...)) inline
Add a class-method as a handler.
Definition at line 1487 of file RPCUtils.h.
References llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler(), and llvm::Object.
addAsyncHandler() [2/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename HandlerT > void llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler (HandlerT Handler) inline
Definition at line 1481 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::addAsyncHandlerImpl().
Referenced by llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addAsyncHandler().
addHandler() [1/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename ClassT , typename RetT , typename... ArgTs> void llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler (ClassT & Object, RetT(ClassT::* Method)(ArgTs...)) inline
Definition at line 1475 of file RPCUtils.h.
References llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler(), and llvm::Object.
addHandler() [2/2]
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename HandlerT > void llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler (HandlerT Handler) inline
Definition at line 1470 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::addHandlerImpl().
Referenced by llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::addHandler().
callB()
template<typename ChannelT , typename FunctionIdT = uint32_t, typename SequenceNumberT = uint32_t> template<typename Func , typename... ArgTs, typename AltRetT = typename Func::ReturnType> detail::ResultTraits< AltRetT >::ErrorReturnType llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB (const ArgTs &... Args) inline
Definition at line 1495 of file RPCUtils.h.
References llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::appendCallAsync(), llvm::orc::shared::detail::ResultTraits< RetT >::consumeAbandoned(), llvm::orc::shared::detail::ResultTraits< RetT >::createBlankErrorReturnValue(), llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< ChannelT, uint32_t, uint32_t >, ChannelT, uint32_t, uint32_t >::handleOne(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h