LLVM: llvm::po_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
llvm::po_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
#include "llvm/ADT/PostOrderIterator.h"
Public Types
using pointer = typename super::pointer
Public Member Functions
bool operator== (const po_iterator &x) const
bool operator!= (const po_iterator &x) const
const NodeRef & operator* () const
NodeRef operator-> () const
po_iterator & operator++ ()
po_iterator operator++ (int)
Public Member Functions inherited from llvm::po_iterator_storage< SetType, External >
template<typename NodeRef >
bool insertEdge (Optional< NodeRef > From, NodeRef To)
template<typename NodeRef >
void finishPostorder (NodeRef BB)
Static Public Member Functions
static po_iterator begin (GraphT G)
static po_iterator end (GraphT G)
static po_iterator begin (GraphT G, SetType &S)
static po_iterator end (GraphT G, SetType &S)
Detailed Description
template<class GraphT, class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>>
class llvm::po_iterator< GraphT, SetType, ExtStorage, GT >
Definition at line 96 of file PostOrderIterator.h.
Member Typedef Documentation
pointer
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> using llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::pointer = typename super::pointer
Definition at line 138 of file PostOrderIterator.h.
Member Function Documentation
begin() [1/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static po_iterator llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::begin (GraphT G) inline static
Definition at line 141 of file PostOrderIterator.h.
References G.
Referenced by llvm::ipo_begin(), llvm::ipo_ext_begin(), llvm::po_begin(), and llvm::po_ext_begin().
begin() [2/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static po_iterator llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::begin (GraphT G, SetType & S) inline static
Definition at line 146 of file PostOrderIterator.h.
References G.
end() [1/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static po_iterator llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::end (GraphT G) inline static
Definition at line 144 of file PostOrderIterator.h.
Referenced by llvm::ipo_end(), llvm::ipo_ext_end(), llvm::po_end(), and llvm::po_ext_end().
end() [2/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static po_iterator llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::end (GraphT G, SetType & S) inline static
Definition at line 149 of file PostOrderIterator.h.
operator!=()
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator!= (const po_iterator< GraphT, SetType, ExtStorage, GT > & x) const inline
Definition at line 154 of file PostOrderIterator.h.
operator*()
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> const NodeRef & llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator* () const inline
Definition at line 156 of file PostOrderIterator.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
operator++() [1/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> po_iterator & llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++ () inline
Definition at line 164 of file PostOrderIterator.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase< Size_T >::empty(), llvm::po_iterator_storage< SetType, External >::finishPostorder(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
operator++() [2/2]
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> po_iterator llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++ (int) inline
Definition at line 172 of file PostOrderIterator.h.
operator->()
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeRef llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator-> () const inline
Definition at line 162 of file PostOrderIterator.h.
operator==()
template<class GraphT , class SetType = SmallPtrSet<typename GraphTraits<GraphT>::NodeRef, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator== (const po_iterator< GraphT, SetType, ExtStorage, GT > & x) const inline
Definition at line 151 of file PostOrderIterator.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/PostOrderIterator.h