LLVM: llvm::TargetLoweringBase::ArgListEntry Class Reference
llvm::TargetLoweringBase::ArgListEntry Class Reference
#include "llvm/CodeGen/TargetLowering.h"
Public Member Functions
ArgListEntry ()
void setAttributes (const CallBase *Call, unsigned ArgIdx)
Set CallLoweringInfo attribute flags based on a call instruction and called function attributes.
Public Attributes
Value * Val = nullptr
SDValue Node = SDValue()
Type * Ty = nullptr
bool IsSExt: 1
bool IsZExt: 1
bool IsInReg: 1
bool IsSRet: 1
bool IsNest: 1
bool IsByVal: 1
bool IsByRef: 1
bool IsInAlloca: 1
bool IsPreallocated: 1
bool IsReturned: 1
bool IsSwiftSelf: 1
bool IsSwiftError: 1
bool IsCFGuardTarget: 1
MaybeAlign Alignment = None
Type * ByValType = nullptr
Type * PreallocatedType = nullptr
Detailed Description
Definition at line 270 of file TargetLowering.h.
Constructor & Destructor Documentation
ArgListEntry()
llvm::TargetLoweringBase::ArgListEntry::ArgListEntry () inline
Definition at line 292 of file TargetLowering.h.
Member Function Documentation
setAttributes()
void TargetLoweringBase::ArgListEntry::setAttributes (const CallBase * Call, unsigned ArgIdx)
Set CallLoweringInfo attribute flags based on a call instruction and called function attributes.
Definition at line 105 of file TargetLowering.cpp.
References Alignment, ByValType, Call, llvm::CallBase::getParamAlign(), llvm::CallBase::getParamByValType(), llvm::CallBase::getParamPreallocatedType(), IsByVal, IsInAlloca, IsInReg, IsNest, IsPreallocated, IsReturned, IsSExt, IsSRet, IsSwiftError, IsSwiftSelf, IsZExt, llvm::CallBase::paramHasAttr(), and PreallocatedType.
Member Data Documentation
Alignment
MaybeAlign llvm::TargetLoweringBase::ArgListEntry::Alignment = None
Definition at line 288 of file TargetLowering.h.
Referenced by setAttributes().
ByValType
Type* llvm::TargetLoweringBase::ArgListEntry::ByValType = nullptr
Definition at line 289 of file TargetLowering.h.
Referenced by setAttributes().
IsByRef
bool llvm::TargetLoweringBase::ArgListEntry::IsByRef
Definition at line 281 of file TargetLowering.h.
IsByVal
bool llvm::TargetLoweringBase::ArgListEntry::IsByVal
Definition at line 280 of file TargetLowering.h.
Referenced by setAttributes().
IsCFGuardTarget
bool llvm::TargetLoweringBase::ArgListEntry::IsCFGuardTarget
Definition at line 287 of file TargetLowering.h.
IsInAlloca
bool llvm::TargetLoweringBase::ArgListEntry::IsInAlloca
Definition at line 282 of file TargetLowering.h.
Referenced by setAttributes().
IsInReg
bool llvm::TargetLoweringBase::ArgListEntry::IsInReg
Definition at line 277 of file TargetLowering.h.
Referenced by setAttributes().
IsNest
bool llvm::TargetLoweringBase::ArgListEntry::IsNest
Definition at line 279 of file TargetLowering.h.
Referenced by setAttributes().
IsPreallocated
bool llvm::TargetLoweringBase::ArgListEntry::IsPreallocated
Definition at line 283 of file TargetLowering.h.
Referenced by setAttributes().
IsReturned
bool llvm::TargetLoweringBase::ArgListEntry::IsReturned
Definition at line 284 of file TargetLowering.h.
Referenced by setAttributes().
IsSExt
bool llvm::TargetLoweringBase::ArgListEntry::IsSExt
Definition at line 275 of file TargetLowering.h.
Referenced by setAttributes().
IsSRet
bool llvm::TargetLoweringBase::ArgListEntry::IsSRet
Definition at line 278 of file TargetLowering.h.
Referenced by setAttributes().
IsSwiftError
bool llvm::TargetLoweringBase::ArgListEntry::IsSwiftError
Definition at line 286 of file TargetLowering.h.
Referenced by setAttributes().
IsSwiftSelf
bool llvm::TargetLoweringBase::ArgListEntry::IsSwiftSelf
Definition at line 285 of file TargetLowering.h.
Referenced by setAttributes().
IsZExt
bool llvm::TargetLoweringBase::ArgListEntry::IsZExt
Definition at line 276 of file TargetLowering.h.
Referenced by setAttributes().
Node
SDValue llvm::TargetLoweringBase::ArgListEntry::Node = SDValue()
Definition at line 273 of file TargetLowering.h.
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemset(), llvm::TargetLowering::LowerCallTo(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), LowerFSINCOS(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
PreallocatedType
Type* llvm::TargetLoweringBase::ArgListEntry::PreallocatedType = nullptr
Definition at line 290 of file TargetLowering.h.
Referenced by setAttributes().
Ty
Type* llvm::TargetLoweringBase::ArgListEntry::Ty = nullptr
Definition at line 274 of file TargetLowering.h.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SelectionDAG::getAtomicMemcpy(), llvm::SelectionDAG::getAtomicMemmove(), llvm::SelectionDAG::getAtomicMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), and llvm::MipsCallLowering::lowerCall().
Val
Value* llvm::TargetLoweringBase::ArgListEntry::Val = nullptr
Definition at line 272 of file TargetLowering.h.
Referenced by llvm::FastISel::lowerCallTo().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetLowering.h
lib/CodeGen/SelectionDAG/TargetLowering.cpp