LLVM: lib/Analysis/CodeMetrics.cpp File Reference
CodeMetrics.cpp File Reference
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "code-metrics"
Functions
static void appendSpeculatableOperands (const Value *V, SmallPtrSetImpl< const Value * > &Visited, SmallVectorImpl< const Value * > &Worklist)
static void completeEphemeralValues (SmallPtrSetImpl< const Value * > &Visited, SmallVectorImpl< const Value * > &Worklist, SmallPtrSetImpl< const Value * > &EphValues)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "code-metrics"
Definition at line 22 of file CodeMetrics.cpp.
Function Documentation
appendSpeculatableOperands()
static void appendSpeculatableOperands (const Value * V, SmallPtrSetImpl< const Value * > & Visited, SmallVectorImpl< const Value * > & Worklist) static
Definition at line 27 of file CodeMetrics.cpp.
References llvm::dyn_cast(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isSafeToSpeculativelyExecute(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), llvm::CodeMetrics::collectEphemeralValues(), and completeEphemeralValues().
completeEphemeralValues()
static void completeEphemeralValues (SmallPtrSetImpl< const Value * > & Visited, SmallVectorImpl< const Value * > & Worklist, SmallPtrSetImpl< const Value * > & EphValues) static
Definition at line 40 of file CodeMetrics.cpp.
References llvm::all_of(), appendSpeculatableOperands(), assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), and llvm::CodeMetrics::collectEphemeralValues().