LLVM: lib/MC/MCParser/COFFMasmParser.cpp File Reference
COFFMasmParser.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/MC/MCParser/MCAsmParserUtils.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolCOFF.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/SMLoc.h"
#include <cassert>
#include <cstdint>
#include <limits>
#include <utility>
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static SectionKind computeSectionKind (unsigned Flags)
MCAsmParserExtension * llvm::createCOFFMasmParser ()
Function Documentation
computeSectionKind()
static SectionKind computeSectionKind (unsigned Flags) static
Definition at line 223 of file COFFMasmParser.cpp.
References llvm::SectionKind::getData(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getText(), llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, and llvm::COFF::IMAGE_SCN_MEM_WRITE.