LLVM: lib/CodeGen/GlobalISel/CombinerHelper.cpp File Reference
CombinerHelper.cpp File Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
#include "llvm/CodeGen/GlobalISel/Combiner.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "gi-combiner"
Functions
static unsigned littleEndianByteAt (const unsigned ByteWidth, const unsigned I)
static unsigned bigEndianByteAt (const unsigned ByteWidth, const unsigned I)
static Optional< bool > isBigEndian (const SmallDenseMap< int64_t, int64_t, 8 > &MemOffset2Idx, int64_t LowestIdx)
Given a map from byte offsets in memory to indices in a load/store, determine if that map corresponds to a little or big endian byte pattern.
static bool shouldLowerMemFuncForSize (const MachineFunction &MF)
static bool findGISelOptimalMemOpLowering (std::vector< LLT > &MemOps, unsigned Limit, const MemOp &Op, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes, const TargetLowering &TLI)
static Type * getTypeForLLT (LLT Ty, LLVMContext &C)
static Register getMemsetValue (Register Val, LLT Ty, MachineIRBuilder &MIB)
static Optional< APFloat > constantFoldFpUnary (unsigned Opcode, LLT DstTy, const Register Op, const MachineRegisterInfo &MRI)
static Register peekThroughBitcast (Register Reg, const MachineRegisterInfo &MRI)
static bool isConstValidTrue (const TargetLowering &TLI, unsigned ScalarSizeBits, int64_t Cst, bool IsVector, bool IsFP)
static Optional< std::pair< MachineInstr *, int64_t > > matchLoadAndBytePosition (Register Reg, unsigned MemSizeInBits, const MachineRegisterInfo &MRI)
Helper function for findLoadOffsetsForLoadOrCombine.
Variables
static cl::opt< bool > ForceLegalIndexing ("force-legal-indexing", cl::Hidden, cl::init(false), cl::desc("Force all indexed operations to be " "legal for the GlobalISel combiner"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gi-combiner"
Definition at line 26 of file CombinerHelper.cpp.
Function Documentation
bigEndianByteAt()
static unsigned bigEndianByteAt (const unsigned ByteWidth, const unsigned I) static
Returns
The big endian in-memory byte position of byte I in a ByteWidth bytes wide type.
E.g. Given a 4-byte type x, x[0] -> byte 3
Definition at line 64 of file CombinerHelper.cpp.
References assert(), and I.
Referenced by isBigEndian(), isBigEndian(), and llvm::CombinerHelper::matchLoadOrCombine().
constantFoldFpUnary()
static Optional< APFloat > constantFoldFpUnary (unsigned Opcode, LLT DstTy, const Register Op, const MachineRegisterInfo & MRI) static
Definition at line 1493 of file CombinerHelper.cpp.
References llvm::getConstantFPVRegVal(), llvm::getFltSemanticForLLT(), llvm::ConstantFP::getValueAPF(), llvm::APFloatBase::IEEEdouble(), llvm_unreachable, llvm::log2(), MRI, llvm::None, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by llvm::CombinerHelper::matchCombineConstantFoldFpUnary().
findGISelOptimalMemOpLowering()
static bool findGISelOptimalMemOpLowering (std::vector< LLT > & MemOps, unsigned Limit, const MemOp & Op, unsigned DstAS, unsigned SrcAS, const AttributeList & FuncAttributes, const TargetLowering & TLI) static
Definition at line 1015 of file CombinerHelper.cpp.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), assert(), llvm::Fast, llvm::getMVTForLLT(), llvm::TargetLoweringBase::getOptimalMemOpLLT(), llvm::LLT::getSizeInBits(), llvm::LLT::getSizeInBytes(), llvm::LLT::isVector(), llvm::MachineMemOperand::MONone, llvm::PowerOf2Floor(), llvm::LLT::scalar(), and Size.
getMemsetValue()
static Register getMemsetValue (Register Val, LLT Ty, MachineIRBuilder & MIB) static
Definition at line 1088 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildMul(), llvm::MachineIRBuilder::buildSplatVector(), llvm::MachineIRBuilder::buildZExtOrTrunc(), llvm::getConstantVRegValWithLookThrough(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getScalarType(), llvm::APInt::getSplat(), Magic, and MRI.
Referenced by getMemsetStores().
getTypeForLLT()
static Type * getTypeForLLT (LLT Ty, LLVMContext & C) static
Definition at line 1080 of file CombinerHelper.cpp.
References C, llvm::FixedVectorType::get(), and llvm::IntegerType::get().
isBigEndian()
static Optional< bool > isBigEndian (const SmallDenseMap< int64_t, int64_t, 8 > & MemOffset2Idx, int64_t LowestIdx) static
Given a map from byte offsets in memory to indices in a load/store, determine if that map corresponds to a little or big endian byte pattern.
Parameters
MemOffset2Idx maps memory offsets to address offsets.
LowestIdx is the lowest index in MemOffset2Idx.
Returns
true if the map corresponds to a big endian byte pattern, false if it corresponds to a little endian byte pattern, and None otherwise.
E.g. given a 32-bit type x, and x[AddrOffset], the in-memory byte patterns are as follows:
AddrOffset Little endian Big endian 0 0 3 1 1 2 2 2 1 3 3 0
Definition at line 87 of file CombinerHelper.cpp.
References assert(), bigEndianByteAt(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), littleEndianByteAt(), llvm::None, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by collectInsertionElements(), createGPRPairNode(), llvm::SelectionDAG::getConstant(), llvm::CombinerHelper::matchLoadOrCombine(), PerformSTORECombine(), ReplaceCMP_SWAP_64Results(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), and llvm::orc::OrcMips32_Base::writeResolverCode().
isConstValidTrue()
static bool isConstValidTrue (const TargetLowering & TLI, unsigned ScalarSizeBits, int64_t Cst, bool IsVector, bool IsFP) static
Definition at line 3011 of file CombinerHelper.cpp.
References llvm::isConstTrueVal().
Referenced by llvm::CombinerHelper::matchNotCmp().
littleEndianByteAt()
static unsigned littleEndianByteAt (const unsigned ByteWidth, const unsigned I) static
Returns
The little endian in-memory byte position of byte I in a ByteWidth bytes wide type.
E.g. Given a 4-byte type x, x[0] -> byte 0
Definition at line 55 of file CombinerHelper.cpp.
References assert(), and I.
Referenced by isBigEndian(), isBigEndian(), and llvm::CombinerHelper::matchLoadOrCombine().
matchLoadAndBytePosition()
static Optional< std::pair< MachineInstr *, int64_t > > matchLoadAndBytePosition (Register Reg, unsigned MemSizeInBits, const MachineRegisterInfo & MRI) static
Helper function for findLoadOffsetsForLoadOrCombine.
Check if Reg is the result of loading a MemSizeInBits wide value, and then moving that value into a specific byte offset.
e.g. x[i] << 24
Returns
The load instruction and the byte offset it is moved into.
Definition at line 3288 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), MRI, llvm::None, and Reg.
peekThroughBitcast()
static Register peekThroughBitcast (Register Reg, const MachineRegisterInfo & MRI) static
Definition at line 1875 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), MRI, and Reg.
Referenced by llvm::CombinerHelper::matchCombineUnmergeMergeToPlainValues().
shouldLowerMemFuncForSize()
static bool shouldLowerMemFuncForSize (const MachineFunction & MF) static
Definition at line 1005 of file CombinerHelper.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::Function::hasMinSize(), llvm::Function::hasOptSize(), and llvm::Triple::isOSDarwin().
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and getMemsetStores().
Variable Documentation
ForceLegalIndexing
cl::opt< bool > ForceLegalIndexing("force-legal-indexing", cl::Hidden, cl::init(false), cl::desc("Force all indexed operations to be " "legal for the GlobalISel combiner")) ("force-legal-indexing" , cl::Hidden , cl::init(false) , cl::desc("Force all indexed operations to be " "legal for the GlobalISel combiner")) static
Referenced by llvm::CombinerHelper::matchCombineIndexedLoadStore().