LLVM: lib/Support/CommandLine.cpp File Reference
CommandLine.cpp File Reference
#include "llvm/Support/CommandLine.h"
#include "llvm-c/Support.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/config.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdlib>
#include <map>
#include <string>
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::cl
cl Namespace - This namespace contains all of the command line option processing machinery.
Macros
#define DEBUG_TYPE "commandline"
#define PRINT_OPT_DIFF(T)
#define LLVM_IS_DEBUG_BUILD 0
Functions
static size_t argPlusPrefixesSize (StringRef ArgName, size_t Pad=DefaultPad)
static SmallString< 8 > argPrefix (StringRef ArgName, size_t Pad=DefaultPad)
static bool isGrouping (const Option *O)
static bool isPrefixedOrGrouping (const Option *O)
static Option * LookupNearestOption (StringRef Arg, const StringMap< Option * > &OptionsMap, std::string &NearestString)
LookupNearestOption - Lookup the closest match to the option specified by the specified option on the command line.
static bool CommaSeparateAndAddOccurrence (Option *Handler, unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
CommaSeparateAndAddOccurrence - A wrapper around Handler->addOccurrence() that does special handling of cl::CommaSeparated options.
static bool ProvideOption (Option *Handler, StringRef ArgName, StringRef Value, int argc, const char *const *argv, int &i)
ProvideOption - For Value, this differentiates between an empty value ("") and a null value (StringRef()).
static Option * getOptionPred (StringRef Name, size_t &Length, bool(*Pred)(const Option *), const StringMap< Option * > &OptionsMap)
static Option * HandlePrefixedOrGroupedOption (StringRef &Arg, StringRef &Value, bool &ErrorParsing, const StringMap< Option * > &OptionsMap)
HandlePrefixedOrGroupedOption - The specified argument string (which started with at least one '-') does not fully match an available option.
static bool RequiresValue (const Option *O)
static bool EatsUnboundedNumberOfValues (const Option *O)
static bool isWhitespace (char C)
static bool isWhitespaceOrNull (char C)
static bool isQuote (char C)
static size_t parseBackslash (StringRef Src, size_t I, SmallString< 128 > &Token)
Backslashes are interpreted in a rather complicated way in the Windows-style command line, because backslashes are used both to separate path and to escape double quote.
static bool isWindowsSpecialChar (char C)
static void tokenizeWindowsCommandLineImpl (StringRef Src, StringSaver &Saver, function_ref< void(StringRef)> AddToken, bool AlwaysCopy, function_ref< void()> MarkEOL)
static bool hasUTF8ByteOrderMark (ArrayRef< char > S)
static llvm::Error ExpandResponseFile (StringRef FName, StringSaver &Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs, bool RelativeNames, llvm::vfs::FileSystem &FS)
static StringRef getValueStr (const Option &O, StringRef DefaultMsg)
static bool parseDouble (Option &O, StringRef Arg, double &Value)
static bool shouldPrintOption (StringRef Name, StringRef Description, const Option &O)
static int OptNameCompare (const std::pair< const char *, Option * > *LHS, const std::pair< const char *, Option * > *RHS)
static int SubNameCompare (const std::pair< const char *, SubCommand * > *LHS, const std::pair< const char *, SubCommand * > *RHS)
static void sortOpts (StringMap< Option * > &OptMap, SmallVectorImpl< std::pair< const char *, Option * > > &Opts, bool ShowHidden)
static void sortSubCommands (const SmallPtrSetImpl< SubCommand * > &SubMap, SmallVectorImpl< std::pair< const char *, SubCommand * > > &Subs)
static HelpPrinter UncategorizedNormalPrinter (false)
static HelpPrinter UncategorizedHiddenPrinter (true)
static CategorizedHelpPrinter CategorizedNormalPrinter (false)
static CategorizedHelpPrinter CategorizedHiddenPrinter (true)
static HelpPrinterWrapper WrappedNormalPrinter (UncategorizedNormalPrinter, CategorizedNormalPrinter)
static HelpPrinterWrapper WrappedHiddenPrinter (UncategorizedHiddenPrinter, CategorizedHiddenPrinter)
void LLVMParseCommandLineOptions (int argc, const char *const *argv, const char *Overview)
This function parses the given arguments using the LLVM command line parser.
Variables
static const size_t DefaultPad = 2
static StringRef ArgPrefix = "-"
static StringRef ArgPrefixLong = "--"
static StringRef ArgHelpPrefix = " - "
static ManagedStatic< CommandLineParser > GlobalParser
static StringRef EqValue = "=<value>"
static StringRef EmptyOption = "<empty>"
static StringRef OptionPrefix = " ="
static size_t OptionPrefixesSize = OptionPrefix.size() + ArgHelpPrefix.size()
static const size_t MaxOptWidth = 8
static cl::OptionCategory GenericCategory ("Generic Options")
static cl::opt< HelpPrinter, true, parser< bool > > HLOp ("help-list", cl::desc("Display list of available options (--help-list-hidden for more)"), cl::location(UncategorizedNormalPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static cl::opt< HelpPrinter, true, parser< bool > > HLHOp ("help-list-hidden", cl::desc("Display list of all available options"), cl::location(UncategorizedHiddenPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static cl::opt< HelpPrinterWrapper, true, parser< bool > > HOp ("help", cl::desc("Display available options (--help-hidden for more)"), cl::location(WrappedNormalPrinter), cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static cl::alias HOpA ("h", cl::desc("Alias for --help"), cl::aliasopt(HOp), cl::DefaultOption)
static cl::opt< HelpPrinterWrapper, true, parser< bool > > HHOp ("help-hidden", cl::desc("Display all available options"), cl::location(WrappedHiddenPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static cl::opt< bool > PrintOptions ("print-options", cl::desc("Print non-default options after command line parsing"), cl::Hidden, cl::init(false), cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static cl::opt< bool > PrintAllOptions ("print-all-options", cl::desc("Print all option values after command line parsing"), cl::Hidden, cl::init(false), cl::cat(GenericCategory), cl::sub(*AllSubCommands))
static VersionPrinterTy OverrideVersionPrinter = nullptr
static std::vector< VersionPrinterTy > * ExtraVersionPrinters = nullptr
static VersionPrinter VersionPrinterInstance
static cl::opt< VersionPrinter, true, parser< bool > > VersOp ("version", cl::desc("Display the version of this program"), cl::location(VersionPrinterInstance), cl::ValueDisallowed, cl::cat(GenericCategory))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "commandline"
Definition at line 50 of file CommandLine.cpp.
LLVM_IS_DEBUG_BUILD
#define LLVM_IS_DEBUG_BUILD 0
Definition at line 2485 of file CommandLine.cpp.
PRINT_OPT_DIFF
#define PRINT_OPT_DIFF (T)
Value:
  void parser<T>::printOptionDiff(const Option &O, T V, OptionValue<T> D,      \
                                  size_t GlobalWidth) const {                  \
    printOptionName(O, GlobalWidth);                                           \
    std::string Str;                                                           \
    {                                                                          \
      raw_string_ostream SS(Str);                                              \
      SS << V;                                                                 \
    }                                                                          \
    outs() << "= " << Str;                                                     \
    size_t NumSpaces =                                                         \
        MaxOptWidth > Str.size() ? MaxOptWidth - Str.size() : 0;               \
    outs().indent(NumSpaces) << " (default: ";                                 \
    if (D.hasValue())                                                          \
      outs() << D.getValue();                                                  \
    else                                                                       \
      outs() << "*no default*";                                                \
    outs() << ")\n";                                                           \
  }
Definition at line 2044 of file CommandLine.cpp.
Function Documentation
argPlusPrefixesSize()
static size_t argPlusPrefixesSize (StringRef ArgName, size_t Pad = DefaultPad) static
Definition at line 105 of file CommandLine.cpp.
References ArgHelpPrefix, ArgPrefix, ArgPrefixLong, and llvm::StringRef::size().
Referenced by llvm::cl::basic_parser_impl::getOptionWidth(), llvm::cl::generic_parser_base::getOptionWidth(), and llvm::cl::generic_parser_base::printOptionInfo().
argPrefix()
static SmallString< 8 > argPrefix (StringRef ArgName, size_t Pad = DefaultPad) static
Definition at line 112 of file CommandLine.cpp.
References llvm::SmallString< N >::append(), ArgPrefix, ArgPrefixLong, I, llvm::cl::Prefix, and llvm::StringRef::size().
CategorizedHiddenPrinter()
static CategorizedHelpPrinter CategorizedHiddenPrinter (true) static
Referenced by llvm::cl::PrintHelpMessage().
CategorizedNormalPrinter()
static CategorizedHelpPrinter CategorizedNormalPrinter (false) static
Referenced by llvm::cl::PrintHelpMessage().
CommaSeparateAndAddOccurrence()
static bool CommaSeparateAndAddOccurrence (Option * Handler, unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg = false) static
CommaSeparateAndAddOccurrence - A wrapper around Handler->addOccurrence() that does special handling of cl::CommaSeparated options.
Definition at line 621 of file CommandLine.cpp.
References llvm::cl::Option::addOccurrence(), llvm::cl::CommaSeparated, llvm::StringRef::find(), llvm::cl::Option::getMiscFlags(), llvm::StringRef::npos, and llvm::StringRef::substr().
Referenced by ProvideOption().
EatsUnboundedNumberOfValues()
static bool EatsUnboundedNumberOfValues (const Option * O) static
Definition at line 808 of file CommandLine.cpp.
References llvm::cl::OneOrMore, and llvm::cl::ZeroOrMore.
ExpandResponseFile()
static llvm::Error ExpandResponseFile (StringRef FName, StringSaver & Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char * > & NewArgv, bool MarkEOLs, bool RelativeNames, llvm::vfs::FileSystem & FS) static
Definition at line 1082 of file CommandLine.cpp.
References llvm::SmallString< N >::append(), llvm::sys::path::append(), Arg, assert(), llvm::SmallString< N >::c_str(), llvm::convertUTF16ToUTF8String(), llvm::createStringError(), llvm::ArrayRef< T >::data(), llvm::StringRef::data(), llvm::errorCodeToError(), llvm::ErrorOr< T >::get(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::ErrorOr< T >::getError(), llvm::hasUTF16ByteOrderMark(), hasUTF8ByteOrderMark(), llvm::sys::path::is_absolute(), llvm::sys::path::is_relative(), llvm::sys::path::parent_path(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringSaver::save(), llvm::ArrayRef< T >::size(), and llvm::Error::success().
Referenced by llvm::cl::ExpandResponseFiles(), and llvm::cl::readConfigFile().
getOptionPred()
static Option * getOptionPred (StringRef Name, size_t & Length, bool(* Pred)(const Option *), const StringMap< Option * > & OptionsMap) static
Definition at line 720 of file CommandLine.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), and Name.
Referenced by HandlePrefixedOrGroupedOption().
getValueStr()
static StringRef getValueStr (const Option & O, StringRef DefaultMsg) static
Definition at line 1702 of file CommandLine.cpp.
Referenced by llvm::cl::basic_parser_impl::getOptionWidth(), and llvm::cl::basic_parser_impl::printOptionInfo().
HandlePrefixedOrGroupedOption()
static Option * HandlePrefixedOrGroupedOption (StringRef & Arg, StringRef & Value, bool & ErrorParsing, const StringMap< Option * > & OptionsMap) static
HandlePrefixedOrGroupedOption - The specified argument string (which started with at least one '-') does not fully match an available option.
Check to see if this is a prefix or grouped option. If so, split arg into output an Arg/Value pair and return the Option to parse it with.
Definition at line 749 of file CommandLine.cpp.
References llvm::cl::AlwaysPrefix, Arg, assert(), llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::StringRef::empty(), llvm::cl::Option::error(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::cl::Option::getFormattingFlag(), getOptionPred(), llvm::cl::Option::getValueExpectedFlag(), isGrouping(), isPrefixedOrGrouping(), llvm::cl::Prefix, ProvideOption(), llvm::StringRef::substr(), and llvm::cl::ValueRequired.
hasUTF8ByteOrderMark()
static bool hasUTF8ByteOrderMark (ArrayRef< char > S) static
Definition at line 1077 of file CommandLine.cpp.
References llvm::ArrayRef< T >::size().
Referenced by ExpandResponseFile().
isGrouping()
static bool isGrouping (const Option * O) inline static
Definition at line 122 of file CommandLine.cpp.
References llvm::cl::Grouping.
Referenced by HandlePrefixedOrGroupedOption(), and isPrefixedOrGrouping().
isPrefixedOrGrouping()
static bool isPrefixedOrGrouping (const Option * O) inline static
Definition at line 125 of file CommandLine.cpp.
References llvm::cl::AlwaysPrefix, isGrouping(), and llvm::cl::Prefix.
Referenced by HandlePrefixedOrGroupedOption().
isQuote()
static bool isQuote (char C) static
Definition at line 821 of file CommandLine.cpp.
References C.
Referenced by llvm::cl::TokenizeGNUCommandLine().
isWhitespace()
static bool isWhitespace (char C) static
Definition at line 813 of file CommandLine.cpp.
References C.
Referenced by isWhitespaceOrNull(), llvm::cl::tokenizeConfigFile(), and llvm::cl::TokenizeGNUCommandLine().
isWhitespaceOrNull()
static bool isWhitespaceOrNull (char C) static
Definition at line 817 of file CommandLine.cpp.
References C, and isWhitespace().
Referenced by isWindowsSpecialChar(), and tokenizeWindowsCommandLineImpl().
isWindowsSpecialChar()
static bool isWindowsSpecialChar (char C) static
Definition at line 923 of file CommandLine.cpp.
References C, and isWhitespaceOrNull().
Referenced by tokenizeWindowsCommandLineImpl().
LLVMParseCommandLineOptions()
void LLVMParseCommandLineOptions (int argc, const char *const * argv, const char * Overview)
This function parses the given arguments using the LLVM command line parser.
Note that the only stable thing about this function is its signature; you cannot rely on any particular set of command line arguments being interpreted the same way across LLVM versions.
See also
llvm::cl::ParseCommandLineOptions()
Definition at line 2613 of file CommandLine.cpp.
References llvm::nulls(), and llvm::cl::ParseCommandLineOptions().
LookupNearestOption()
static Option * LookupNearestOption (StringRef Arg, const StringMap< Option * > & OptionsMap, std::string & NearestString) static
LookupNearestOption - Lookup the closest match to the option specified by the specified option on the command line.
If there is a value specified (after an equal sign) return that as well. This assumes that leading dashes have already been stripped.
Definition at line 572 of file CommandLine.cpp.
References Arg, llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::StringRef::edit_distance(), llvm::StringMap< ValueTy, AllocatorTy >::end(), Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::cl::ReallyHidden, and llvm::cl::ValueDisallowed.
OptNameCompare()
static int OptNameCompare (const std::pair< const char *, Option * > * LHS, const std::pair< const char *, Option * > * RHS) static
Definition at line 2101 of file CommandLine.cpp.
Referenced by sortOpts().
parseBackslash()
static size_t parseBackslash (StringRef Src, size_t I, SmallString< 128 > & Token) static
Backslashes are interpreted in a rather complicated way in the Windows-style command line, because backslashes are used both to separate path and to escape double quote.
This method consumes runs of backslashes as well as the following double quote if it's escaped.
If an even number of backslashes is followed by a double quote, one backslash is output for every pair of backslashes, and the last double quote remains unconsumed. The double quote will later be interpreted as the start or end of a quoted string in the main loop outside of this function.
If an odd number of backslashes is followed by a double quote, one backslash is output for every pair of backslashes, and a double quote is output for the last pair of backslash-double quote. The double quote is consumed in this case.
Otherwise, backslashes are interpreted literally.
Definition at line 901 of file CommandLine.cpp.
References llvm::SmallString< N >::append(), E, I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::StringRef::size().
Referenced by tokenizeWindowsCommandLineImpl().
parseDouble()
static bool parseDouble (Option & O, StringRef Arg, double & Value) static
Definition at line 1891 of file CommandLine.cpp.
References Arg.
ProvideOption()
static bool ProvideOption (Option * Handler, StringRef ArgName, StringRef Value, int argc, const char *const * argv, int & i) inline static
ProvideOption - For Value, this differentiates between an empty value ("") and a null value (StringRef()).
The later is accepted for arguments that don't allow a value (-foo) the former is rejected (-foo=).
Definition at line 649 of file CommandLine.cpp.
References llvm::cl::AlwaysPrefix, assert(), CommaSeparateAndAddOccurrence(), llvm::cl::Option::error(), llvm::cl::Option::getFormattingFlag(), llvm::cl::Option::getNumAdditionalVals(), llvm::cl::Option::getValueExpectedFlag(), llvm::cl::ValueDisallowed, llvm::cl::ValueOptional, and llvm::cl::ValueRequired.
Referenced by HandlePrefixedOrGroupedOption(), and llvm::cl::ProvidePositionalOption().
RequiresValue()
static bool RequiresValue (const Option * O) static
Definition at line 803 of file CommandLine.cpp.
References llvm::cl::OneOrMore, and llvm::cl::Required.
shouldPrintOption()
static bool shouldPrintOption (StringRef Name, StringRef Description, const Option & O) static
Definition at line 1932 of file CommandLine.cpp.
References llvm::StringRef::empty(), Name, and llvm::cl::ValueOptional.
Referenced by llvm::cl::generic_parser_base::getOptionWidth(), and llvm::cl::generic_parser_base::printOptionInfo().
sortOpts()
static void sortOpts (StringMap< Option * > & OptMap, SmallVectorImpl< std::pair< const char *, Option * > > & Opts, bool ShowHidden) static
Definition at line 2112 of file CommandLine.cpp.
References llvm::array_pod_sort(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), E, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::cl::Hidden, I, llvm::SmallPtrSetImpl< PtrType >::insert(), OptNameCompare(), and llvm::cl::ReallyHidden.
sortSubCommands()
static void sortSubCommands (const SmallPtrSetImpl< SubCommand * > & SubMap, SmallVectorImpl< std::pair< const char *, SubCommand * > > & Subs) static
Definition at line 2140 of file CommandLine.cpp.
References llvm::array_pod_sort(), and SubNameCompare().
SubNameCompare()
static int SubNameCompare (const std::pair< const char *, SubCommand * > * LHS, const std::pair< const char *, SubCommand * > * RHS) static
Definition at line 2106 of file CommandLine.cpp.
Referenced by sortSubCommands().
tokenizeWindowsCommandLineImpl()
static void tokenizeWindowsCommandLineImpl (StringRef Src, StringSaver & Saver, function_ref< void(StringRef)> AddToken, bool AlwaysCopy, function_ref< void()> MarkEOL) inline static
Definition at line 930 of file CommandLine.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), E, llvm::SmallVectorBase< Size_T >::empty(), I, INIT, isWhitespaceOrNull(), isWindowsSpecialChar(), llvm_unreachable, parseBackslash(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringSaver::save(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::SmallString< N >::str().
Referenced by llvm::cl::TokenizeWindowsCommandLine(), and llvm::cl::TokenizeWindowsCommandLineNoCopy().
UncategorizedHiddenPrinter()
static HelpPrinter UncategorizedHiddenPrinter (true) static
Referenced by llvm::cl::PrintHelpMessage().
UncategorizedNormalPrinter()
static HelpPrinter UncategorizedNormalPrinter (false) static
Referenced by llvm::cl::PrintHelpMessage().
WrappedHiddenPrinter()
static HelpPrinterWrapper WrappedHiddenPrinter (UncategorizedHiddenPrinter , CategorizedHiddenPrinter) static
WrappedNormalPrinter()
static HelpPrinterWrapper WrappedNormalPrinter (UncategorizedNormalPrinter , CategorizedNormalPrinter) static
Variable Documentation
ArgHelpPrefix
StringRef ArgHelpPrefix = " - " static
Definition at line 103 of file CommandLine.cpp.
Referenced by argPlusPrefixesSize(), llvm::cl::Option::printEnumValHelpStr(), and llvm::cl::Option::printHelpStr().
ArgPrefix
StringRef ArgPrefix = "-" static
Definition at line 101 of file CommandLine.cpp.
Referenced by argPlusPrefixesSize(), and argPrefix().
ArgPrefixLong
StringRef ArgPrefixLong = "--" static
Definition at line 102 of file CommandLine.cpp.
Referenced by argPlusPrefixesSize(), and argPrefix().
DefaultPad
const size_t DefaultPad = 2 static
Definition at line 99 of file CommandLine.cpp.
EmptyOption
StringRef EmptyOption = "<empty>" static
Definition at line 1928 of file CommandLine.cpp.
Referenced by llvm::cl::generic_parser_base::getOptionWidth(), and llvm::cl::generic_parser_base::printOptionInfo().
EqValue
StringRef EqValue = "=<value>" static
Definition at line 1927 of file CommandLine.cpp.
Referenced by llvm::cl::generic_parser_base::getOptionWidth(), and llvm::cl::generic_parser_base::printOptionInfo().
ExtraVersionPrinters
std::vector<VersionPrinterTy>* ExtraVersionPrinters = nullptr static
Definition at line 2464 of file CommandLine.cpp.
Referenced by llvm::cl::AddExtraVersionPrinter().
GenericCategory
cl::OptionCategory GenericCategory("Generic Options") ("Generic Options") static
Referenced by llvm::cl::HideUnrelatedOptions(), and llvm::cl::HideUnrelatedOptions().
GlobalParser
ManagedStatic<CommandLineParser> GlobalParser static
Definition at line 434 of file CommandLine.cpp.
Referenced by llvm::cl::Option::addArgument(), llvm::cl::AddLiteralOption(), llvm::cl::Option::error(), llvm::cl::extrahelp::extrahelp(), llvm::cl::getRegisteredOptions(), llvm::cl::getRegisteredSubcommands(), llvm::cl::SubCommand::operator bool(), llvm::cl::ParseCommandLineOptions(), llvm::cl::PrintOptionValues(), llvm::cl::SubCommand::registerSubCommand(), llvm::cl::Option::removeArgument(), llvm::cl::ResetCommandLineParser(), llvm::cl::Option::setArgStr(), and llvm::cl::SubCommand::unregisterSubCommand().
HHOp
cl::opt< HelpPrinterWrapper, true, parser< bool > > HHOp("help-hidden", cl::desc("Display all available options"), cl::location(WrappedHiddenPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("help-hidden" , cl::desc("Display all available options") , cl::location(WrappedHiddenPrinter) , cl::Hidden , cl::ValueDisallowed , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
HLHOp
cl::opt< HelpPrinter, true, parser< bool > > HLHOp("help-list-hidden", cl::desc("Display list of all available options"), cl::location(UncategorizedHiddenPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("help-list-hidden" , cl::desc("Display list of all available options") , cl::location(UncategorizedHiddenPrinter) , cl::Hidden , cl::ValueDisallowed , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
HLOp
cl::opt< HelpPrinter, true, parser< bool > > HLOp("help-list", cl::desc("Display list of available options (--help-list-hidden for more)"), cl::location(UncategorizedNormalPrinter), cl::Hidden, cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("help-list" , cl::desc("Display list of available options (--help-list-hidden for more)") , cl::location(UncategorizedNormalPrinter) , cl::Hidden , cl::ValueDisallowed , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
HOp
cl::opt< HelpPrinterWrapper, true, parser< bool > > HOp("help", cl::desc("Display available options (--help-hidden for more)"), cl::location(WrappedNormalPrinter), cl::ValueDisallowed, cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("help" , cl::desc("Display available options (--help-hidden for more)") , cl::location(WrappedNormalPrinter) , cl::ValueDisallowed , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
Referenced by canonicalizeShuffleMaskWithHorizOp(), combineX86ShufflesRecursively(), foldShuffleOfHorizOp(), and lowerAddSubToHorizontalOp().
HOpA
cl::alias HOpA("h", cl::desc("Alias for --help"), cl::aliasopt(HOp), cl::DefaultOption) ("h" , cl::desc("Alias for --help") , cl::aliasopt(HOp) , cl::DefaultOption) static
MaxOptWidth
const size_t MaxOptWidth = 8 static
Definition at line 2010 of file CommandLine.cpp.
Referenced by llvm::cl::generic_parser_base::printGenericOptionDiff().
OptionPrefix
StringRef OptionPrefix = " =" static
Definition at line 1929 of file CommandLine.cpp.
Referenced by llvm::cl::generic_parser_base::printOptionInfo().
OptionPrefixesSize
size_t OptionPrefixesSize = OptionPrefix.size() + ArgHelpPrefix.size() static
Definition at line 1930 of file CommandLine.cpp.
Referenced by llvm::cl::generic_parser_base::getOptionWidth(), and llvm::cl::generic_parser_base::printOptionInfo().
OverrideVersionPrinter
VersionPrinterTy OverrideVersionPrinter = nullptr static
Definition at line 2462 of file CommandLine.cpp.
Referenced by llvm::cl::SetVersionPrinter().
PrintAllOptions
cl::opt< bool > PrintAllOptions("print-all-options", cl::desc("Print all option values after command line parsing"), cl::Hidden, cl::init(false), cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("print-all-options" , cl::desc("Print all option values after command line parsing") , cl::Hidden , cl::init(false) , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
PrintOptions
cl::opt< bool > PrintOptions("print-options", cl::desc("Print non-default options after command line parsing"), cl::Hidden, cl::init(false), cl::cat(GenericCategory), cl::sub(*AllSubCommands)) ("print-options" , cl::desc("Print non-default options after command line parsing") , cl::Hidden , cl::init(false) , cl::cat(GenericCategory) , cl::sub * AllSubCommands) static
VersionPrinterInstance
VersionPrinter VersionPrinterInstance static
Definition at line 2545 of file CommandLine.cpp.
Referenced by llvm::cl::PrintVersionMessage().
VersOp
cl::opt< VersionPrinter, true, parser< bool > > VersOp("version", cl::desc("Display the version of this program"), cl::location(VersionPrinterInstance), cl::ValueDisallowed, cl::cat(GenericCategory)) ("version" , cl::desc("Display the version of this program") , cl::location(VersionPrinterInstance) , cl::ValueDisallowed , cl::cat(GenericCategory)) static