LLVM: lib/CodeGen/AsmPrinter/DbgEntityHistoryCalculator.cpp File Reference
DbgEntityHistoryCalculator.cpp File Reference
#include "llvm/CodeGen/DbgEntityHistoryCalculator.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/LexicalScopes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <map>
#include <utility>
Macros
#define DEBUG_TYPE "dwarfdebug"
Functions
static Register isDescribedByReg (const MachineInstr &MI)
static Optional< ArrayRef< InsnRange >::iterator > intersects (const MachineInstr *StartMI, const MachineInstr *EndMI, const ArrayRef< InsnRange > &Ranges, const InstructionOrdering &Ordering)
Check if the instruction range [StartMI, EndMI] intersects any instruction range in Ranges.
static void dropRegDescribedVar (RegDescribedVarsMap &RegVars, unsigned RegNo, InlinedEntity Var)
static void addRegDescribedVar (RegDescribedVarsMap &RegVars, unsigned RegNo, InlinedEntity Var)
static void clobberRegEntries (InlinedEntity Var, unsigned RegNo, const MachineInstr &ClobberingInstr, DbgValueEntriesMap &LiveEntries, DbgValueHistoryMap &HistMap)
Create a clobbering entry and end all open debug value entries for Var that are described by RegNo using that entry.
static void handleNewDebugValue (InlinedEntity Var, const MachineInstr &DV, RegDescribedVarsMap &RegVars, DbgValueEntriesMap &LiveEntries, DbgValueHistoryMap &HistMap)
Add a new debug value for Var. Closes all overlapping debug values.
static void clobberRegisterUses (RegDescribedVarsMap &RegVars, RegDescribedVarsMap::iterator I, DbgValueHistoryMap &HistMap, DbgValueEntriesMap &LiveEntries, const MachineInstr &ClobberingInstr)
static void clobberRegisterUses (RegDescribedVarsMap &RegVars, unsigned RegNo, DbgValueHistoryMap &HistMap, DbgValueEntriesMap &LiveEntries, const MachineInstr &ClobberingInstr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarfdebug"
Definition at line 34 of file DbgEntityHistoryCalculator.cpp.
Function Documentation
addRegDescribedVar()
static void addRegDescribedVar (RegDescribedVarsMap & RegVars, unsigned RegNo, InlinedEntity Var) static
Definition at line 310 of file DbgEntityHistoryCalculator.cpp.
References assert(), and llvm::is_contained().
Referenced by handleNewDebugValue().
clobberRegEntries()
static void clobberRegEntries (InlinedEntity Var, unsigned RegNo, const MachineInstr & ClobberingInstr, DbgValueEntriesMap & LiveEntries, DbgValueHistoryMap & HistMap) static
Create a clobbering entry and end all open debug value entries for Var that are described by RegNo using that entry.
Definition at line 320 of file DbgEntityHistoryCalculator.cpp.
References assert(), llvm::SmallVectorImpl< T >::erase(), llvm::DbgValueHistoryMap::getEntry(), isDescribedByReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::DbgValueHistoryMap::startClobber().
Referenced by clobberRegisterUses().
clobberRegisterUses() [1/2]
static void clobberRegisterUses (RegDescribedVarsMap & RegVars, RegDescribedVarsMap::iterator I, DbgValueHistoryMap & HistMap, DbgValueEntriesMap & LiveEntries, const MachineInstr & ClobberingInstr) static
Definition at line 391 of file DbgEntityHistoryCalculator.cpp.
References clobberRegEntries(), and I.
Referenced by llvm::calculateDbgEntityHistory(), and clobberRegisterUses().
clobberRegisterUses() [2/2]
static void clobberRegisterUses (RegDescribedVarsMap & RegVars, unsigned RegNo, DbgValueHistoryMap & HistMap, DbgValueEntriesMap & LiveEntries, const MachineInstr & ClobberingInstr) static
Definition at line 405 of file DbgEntityHistoryCalculator.cpp.
References clobberRegisterUses(), and I.
dropRegDescribedVar()
static void dropRegDescribedVar (RegDescribedVarsMap & RegVars, unsigned RegNo, InlinedEntity Var) static
Definition at line 296 of file DbgEntityHistoryCalculator.cpp.
References assert(), llvm::find(), and I.
Referenced by handleNewDebugValue().
handleNewDebugValue()
static void handleNewDebugValue (InlinedEntity Var, const MachineInstr & DV, RegDescribedVarsMap & RegVars, DbgValueEntriesMap & LiveEntries, DbgValueHistoryMap & HistMap) static
Add a new debug value for Var. Closes all overlapping debug values.
Definition at line 343 of file DbgEntityHistoryCalculator.cpp.
References addRegDescribedVar(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), dropRegDescribedVar(), llvm::DIExpression::fragmentsOverlap(), llvm::MachineInstr::getDebugExpression(), llvm::DbgValueHistoryMap::getEntry(), I, isDescribedByReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, and llvm::DbgValueHistoryMap::startDbgValue().
Referenced by llvm::calculateDbgEntityHistory().
intersects()
static Optional< ArrayRef< InsnRange >::iterator > intersects (const MachineInstr * StartMI, const MachineInstr * EndMI, const ArrayRef< InsnRange > & Ranges, const InstructionOrdering & Ordering) static
Check if the instruction range [StartMI, EndMI] intersects any instruction range in Ranges.
EndMI can be nullptr to indicate that the range is unbounded. Assumes Ranges is ordered and disjoint. Returns true and points to the first intersecting scope range if one exists.
Definition at line 131 of file DbgEntityHistoryCalculator.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::InstructionOrdering::isBefore(), and llvm::None.
Referenced by llvm::DbgValueHistoryMap::trimLocationRanges().
isDescribedByReg()
static Register isDescribedByReg (const MachineInstr & MI) static
Definition at line 43 of file DbgEntityHistoryCalculator.cpp.
References assert(), MI, and Register.
Referenced by clobberRegEntries(), and handleNewDebugValue().