LLVM: lib/CodeGen/AsmPrinter/DebugHandlerBase.cpp File Reference
DebugHandlerBase.cpp File Reference
#include "llvm/CodeGen/DebugHandlerBase.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "dwarfdebug"
Functions
static bool hasDebugInfo (const MachineModuleInfo *MMI, const MachineFunction *MF)
Variables
static cl::opt< bool > TrimVarLocs ("trim-var-locs", cl::Hidden, cl::init(true))
If true, we drop variable location ranges which exist entirely outside the variable's lexical scope instruction ranges.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarfdebug"
Definition at line 28 of file DebugHandlerBase.cpp.
Function Documentation
hasDebugInfo()
static bool hasDebugInfo (const MachineModuleInfo * MMI, const MachineFunction * MF) static
Definition at line 214 of file DebugHandlerBase.cpp.
References assert(), llvm::MachineFunction::getFunction(), llvm::Function::getSubprogram(), llvm::MachineModuleInfo::hasDebugInfo(), and llvm::DICompileUnit::NoDebug.
Referenced by llvm::DebugHandlerBase::beginFunction(), and llvm::DebugHandlerBase::endFunction().
Variable Documentation
TrimVarLocs
cl::opt< bool > TrimVarLocs("trim-var-locs", cl::Hidden, cl::init(true)) ("trim-var-locs" , cl::Hidden , cl::init(true)) static
If true, we drop variable location ranges which exist entirely outside the variable's lexical scope instruction ranges.
Referenced by llvm::DebugHandlerBase::beginFunction().