LLVM: lib/Support/Debug.cpp File Reference
Debug.cpp File Reference
#include "llvm/Support/Debug.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/circular_raw_ostream.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
bool llvm::isCurrentDebugType (const char *Type)
isCurrentDebugType - Return true if the specified string is the debug type specified on the command line, or if none was specified on the command line with the -debug-only=X option.
void llvm::setCurrentDebugTypes (const char **Types, unsigned Count)
setCurrentDebugTypes - Set the current debug type, as if the -debug-only=X,Y,Z option were specified.
void llvm::setCurrentDebugType (const char *Type)
setCurrentDebugType - Set the current debug type, as if the -debug-only=X option were specified.
static void debug_user_sig_handler (void *Cookie)
Variables
static ManagedStatic< std::vector< std::string > > llvm::CurrentDebugType
static cl::opt< bool, true > Debug ("debug", cl::desc("Enable debug output"), cl::Hidden, cl::location(DebugFlag))
static cl::opt< unsigned > DebugBufferSize ("debug-buffer-size", cl::desc("Buffer the last N characters of debug output " "until program termination. " "[default 0 -- immediate print-out]"), cl::Hidden, cl::init(0))
static DebugOnlyOpt DebugOnlyOptLoc
static cl::opt< DebugOnlyOpt, true, cl::parser< std::string > > DebugOnly ("debug-only", cl::desc("Enable a specific type of debug output (comma separated list of types)"), cl::Hidden, cl::ZeroOrMore, cl::value_desc("debug string"), cl::location(DebugOnlyOptLoc), cl::ValueRequired)
Function Documentation
debug_user_sig_handler()
static void debug_user_sig_handler (void * Cookie) static
Definition at line 121 of file Debug.cpp.
References llvm::dbgs(), and llvm::circular_raw_ostream::flushBufferWithBanner().
Referenced by llvm::dbgs().
Variable Documentation
Debug
cl::opt< bool, true > Debug("debug", cl::desc("Enable debug output"), cl::Hidden, cl::location(DebugFlag)) ("debug" , cl::desc("Enable debug output") , cl::Hidden , cl::location(DebugFlag)) static
Referenced by llvm::MCObjectStreamer::emitCFISections(), llvm::MCStreamer::emitCFISections(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), and llvm::LTOCodeGenerator::setDebugInfo().
DebugBufferSize
cl::opt< unsigned > DebugBufferSize("debug-buffer-size", cl::desc("Buffer the last N characters of debug output " "until program termination. " "[default 0 -- immediate print-out]"), cl::Hidden, cl::init(0)) ("debug-buffer-size" , cl::desc("Buffer the last N characters of debug output " "until program termination. " "[default 0 -- immediate print-out]") , cl::Hidden , cl::init(0)) static
Referenced by llvm::dbgs().
DebugOnly
cl::opt< DebugOnlyOpt, true, cl::parser< std::string > > DebugOnly("debug-only", cl::desc("Enable a specific type of debug output (comma separated list of types)"), cl::Hidden, cl::ZeroOrMore, cl::value_desc("debug string"), cl::location(DebugOnlyOptLoc), cl::ValueRequired) ("debug-only" , cl::desc("Enable a specific type of debug output (comma separated list of types)") , cl::Hidden , cl::ZeroOrMore , cl::value_desc("debug string") , cl::location(DebugOnlyOptLoc) , cl::ValueRequired) static
DebugOnlyOptLoc
DebugOnlyOpt DebugOnlyOptLoc static
Definition at line 114 of file Debug.cpp.