LLVM: lib/DebugInfo/PDB/DIA/DIASession.cpp File Reference
DIASession.cpp File Reference
#include "llvm/DebugInfo/PDB/DIA/DIASession.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumDebugStreams.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumFrameData.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumInjectedSources.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumLineNumbers.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumSectionContribs.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumSourceFiles.h"
#include "llvm/DebugInfo/PDB/DIA/DIAEnumTables.h"
#include "llvm/DebugInfo/PDB/DIA/DIAError.h"
#include "llvm/DebugInfo/PDB/DIA/DIARawSymbol.h"
#include "llvm/DebugInfo/PDB/DIA/DIASourceFile.h"
#include "llvm/DebugInfo/PDB/DIA/DIASupport.h"
#include "llvm/DebugInfo/PDB/GenericError.h"
#include "llvm/DebugInfo/PDB/PDB.h"
#include "llvm/DebugInfo/PDB/PDBSymbolCompiland.h"
#include "llvm/DebugInfo/PDB/PDBSymbolExe.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename... Ts>
static Error ErrorFromHResult (HRESULT Result, const char *Str, Ts &&... Args)
static Error LoadDIA (CComPtr< IDiaDataSource > &DiaDataSource)
template<class T >
static CComPtr< T > getTableEnumerator (IDiaSession &Session)
Function Documentation
ErrorFromHResult()
template<typename... Ts> static Error ErrorFromHResult (HRESULT Result, const char * Str, Ts &&... Args) static
Definition at line 34 of file DIASession.cpp.
References Context, llvm::errorCodeToError(), llvm::format_hex(), llvm::formatv(), llvm::make_error(), llvm::raw_string_ostream::str(), and llvm::SmallString< N >::str().
Referenced by llvm::pdb::DIASession::createFromExe(), llvm::pdb::DIASession::createFromPdb(), and LoadDIA().
getTableEnumerator()
template<class T > static CComPtr< T > getTableEnumerator (IDiaSession & Session) static
Definition at line 378 of file DIASession.cpp.
References llvm::Count, and llvm::Enumerator.
Referenced by llvm::pdb::DIASession::getFrameData(), llvm::pdb::DIASession::getInjectedSources(), and llvm::pdb::DIASession::getSectionContribs().
LoadDIA()
static Error LoadDIA (CComPtr< IDiaDataSource > & DiaDataSource) static
Definition at line 65 of file DIASession.cpp.
References ErrorFromHResult(), llvm::make_error(), and llvm::Error::success().
Referenced by llvm::pdb::DIASession::createFromExe(), and llvm::pdb::DIASession::createFromPdb().