LLVM: include/llvm/DebugInfo/PDB/DIA/DIAUtils.h File Reference
DIAUtils.h File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/ConvertUTF.h"
Functions
template<typename Obj >
std::string invokeBstrMethod (Obj &Object, HRESULT(__stdcall Obj::*Func)(BSTR *))
Function Documentation
invokeBstrMethod()
template<typename Obj > std::string invokeBstrMethod (Obj & Object, HRESULT(__stdcall Obj::* Func)(BSTR *))
Definition at line 16 of file DIAUtils.h.
References llvm::convertUTF16ToUTF8String().
Referenced by llvm::pdb::DIAInjectedSource::getFileName(), llvm::pdb::DIASourceFile::getFileName(), llvm::pdb::DIADataStream::getName(), llvm::pdb::DIATable::getName(), llvm::pdb::DIAInjectedSource::getObjectFileName(), llvm::pdb::DIAFrameData::getProgram(), and llvm::pdb::DIAInjectedSource::getVirtualFileName().