LLVM: lib/IR/DIBuilder.cpp File Reference
DIBuilder.cpp File Reference
#include "llvm/IR/DIBuilder.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Functions
static DIScope * getNonCompileUnitScope (DIScope *N)
If N is compile unit return NULL otherwise return N.
static DIImportedEntity * createImportedModule (LLVMContext &C, dwarf::Tag Tag, DIScope *Context, Metadata *NS, DIFile *File, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > &AllImportedModules)
static ConstantAsMetadata * getConstantOrNull (Constant *C)
static DITemplateValueParameter * createTemplateValueParameterHelper (LLVMContext &VMContext, unsigned Tag, DIScope *Context, StringRef Name, DIType *Ty, bool IsDefault, Metadata *MD)
static DIType * createTypeWithFlags (const DIType *Ty, DINode::DIFlags FlagsToSet)
static void checkGlobalVariableScope (DIScope *Context)
static DILocalVariable * createLocalVariable (LLVMContext &VMContext, DenseMap< MDNode *, SmallVector< TrackingMDNodeRef, 1 > > &PreservedVariables, DIScope *Scope, StringRef Name, unsigned ArgNo, DIFile *File, unsigned LineNo, DIType *Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits)
template<class... Ts>
static DISubprogram * getSubprogram (bool IsDistinct, Ts &&... Args)
static void initIRBuilder (IRBuilder<> &Builder, const DILocation *DL, BasicBlock *InsertBB, Instruction *InsertBefore)
Initialize IRBuilder for inserting dbg.declare and dbg.value intrinsics.
static Value * getDbgIntrinsicValueImpl (LLVMContext &VMContext, Value *V)
static Function * getDeclareIntrin (Module &M)
Variables
static cl::opt< bool > UseDbgAddr ("use-dbg-addr", llvm::cl::desc("Use llvm.dbg.addr for all local variables"), cl::init(false), cl::Hidden)
Function Documentation
checkGlobalVariableScope()
static void checkGlobalVariableScope (DIScope * Context) static
Definition at line 676 of file DIBuilder.cpp.
References assert(), llvm::dyn_cast_or_null(), and getNonCompileUnitScope().
Referenced by llvm::DIBuilder::createGlobalVariableExpression(), and llvm::DIBuilder::createTempGlobalVariableFwdDecl().
createImportedModule()
static DIImportedEntity * createImportedModule (LLVMContext & C, dwarf::Tag Tag, DIScope * Context, Metadata * NS, DIFile * File, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > & AllImportedModules) static
Definition at line 165 of file DIBuilder.cpp.
References assert(), C, llvm::cast_or_null(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MDNode::get(), and Name.
Referenced by LLVMDIBuilderCreateImportedModuleFromAlias(), LLVMDIBuilderCreateImportedModuleFromModule(), and LLVMDIBuilderCreateImportedModuleFromNamespace().
createLocalVariable()
static DILocalVariable * createLocalVariable (LLVMContext & VMContext, DenseMap< MDNode *, SmallVector< TrackingMDNodeRef, 1 > > & PreservedVariables, DIScope * Scope, StringRef Name, unsigned ArgNo, DIFile * File, unsigned LineNo, DIType * Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits) static
Definition at line 716 of file DIBuilder.cpp.
References assert(), llvm::cast_or_null(), llvm::MDNode::get(), llvm::getDISubprogram(), getNonCompileUnitScope(), and Name.
Referenced by llvm::DIBuilder::createAutoVariable(), and llvm::DIBuilder::createParameterVariable().
createTemplateValueParameterHelper()
static DITemplateValueParameter * createTemplateValueParameterHelper (LLVMContext & VMContext, unsigned Tag, DIScope * Context, StringRef Name, DIType * Ty, bool IsDefault, Metadata * MD) static
Definition at line 422 of file DIBuilder.cpp.
References assert(), llvm::MDNode::get(), llvm::isa(), and Name.
Referenced by llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTemplateParameter(), and llvm::DIBuilder::createTemplateValueParameter().
createTypeWithFlags()
static DIType * createTypeWithFlags (const DIType * Ty, DINode::DIFlags FlagsToSet) static
Definition at line 565 of file DIBuilder.cpp.
References llvm::DIType::cloneWithFlags(), and llvm::MDNode::replaceWithUniqued().
Referenced by llvm::DIBuilder::createArtificialType(), and llvm::DIBuilder::createObjectPointerType().
getConstantOrNull()
static ConstantAsMetadata * getConstantOrNull (Constant * C) static
Definition at line 354 of file DIBuilder.cpp.
References C, and llvm::ConstantAsMetadata::get().
Referenced by llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createTemplateValueParameter(), and llvm::DIBuilder::createVariantMemberType().
getDbgIntrinsicValueImpl()
static Value * getDbgIntrinsicValueImpl (LLVMContext & VMContext, Value * V) static
Definition at line 954 of file DIBuilder.cpp.
References assert(), llvm::MetadataAsValue::get(), and llvm::ValueAsMetadata::get().
getDeclareIntrin()
static Function * getDeclareIntrin (Module & M) static
Definition at line 959 of file DIBuilder.cpp.
References llvm::Intrinsic::dbg_addr, llvm::Intrinsic::dbg_declare, llvm::Intrinsic::getDeclaration(), and UseDbgAddr.
getNonCompileUnitScope()
static DIScope * getNonCompileUnitScope (DIScope * N) static
If N is compile unit return NULL otherwise return N.
Definition at line 132 of file DIBuilder.cpp.
References llvm::cast(), llvm::isa(), and N.
Referenced by checkGlobalVariableScope(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createLabel(), llvm::DIBuilder::createLexicalBlock(), createLocalVariable(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createVariantMemberType(), and llvm::DIBuilder::createVariantPart().
getSubprogram()
template<class... Ts> static DISubprogram * getSubprogram (bool IsDistinct, Ts &&... Args) static
Definition at line 792 of file DIBuilder.cpp.
References llvm::MDNode::get(), and llvm::MDNode::getDistinct().
Referenced by llvm::DIBuilder::createFunction(), llvm::DIBuilder::createMethod(), getSubprogram(), and LLVMGetSubprogram().
initIRBuilder()
static void initIRBuilder (IRBuilder<> & Builder, const DILocation * DL, BasicBlock * InsertBB, Instruction * InsertBefore) static
Initialize IRBuilder for inserting dbg.declare and dbg.value intrinsics.
This abstracts over the various ways to specify an insert position.
Definition at line 945 of file DIBuilder.cpp.
References DL.
Variable Documentation
UseDbgAddr
cl::opt< bool > UseDbgAddr("use-dbg-addr", llvm::cl::desc("Use llvm.dbg.addr for all local variables"), cl::init(false), cl::Hidden) ("use-dbg-addr" , llvm::cl::desc("Use llvm.dbg.addr for all local variables") , cl::init(false) , cl::Hidden) static
Referenced by getDeclareIntrin().