LLVM: lib/DebugInfo/DWARF/DWARFContext.cpp File Reference
DWARFContext.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAddr.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAranges.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugMacro.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugPubTable.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRangeList.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRnglists.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFGdbIndex.h"
#include "llvm/DebugInfo/DWARF/DWARFSection.h"
#include "llvm/DebugInfo/DWARF/DWARFUnitIndex.h"
#include "llvm/DebugInfo/DWARF/DWARFVerifier.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Object/Decompressor.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/RelocationResolver.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstdint>
#include <deque>
#include <map>
#include <string>
#include <utility>
#include <vector>
Classes
struct SymInfo
SymInfo contains information about symbol: it's address and section index which is -1LL for absolute symbols.
Macros
#define DEBUG_TYPE "dwarf"
Typedefs
using DWARFLineTable = DWARFDebugLine::LineTable
using ContributionCollection
Functions
static void dumpUUID (raw_ostream &OS, const ObjectFile &Obj)
Dump the UUID load command.
static ContributionCollection collectContributionData (DWARFContext::unit_iterator_range Units)
static void dumpStringOffsetsSection (raw_ostream &OS, DIDumpOptions DumpOpts, StringRef SectionName, const DWARFObject &Obj, const DWARFSection &StringOffsetsSection, StringRef StringSection, DWARFContext::unit_iterator_range Units, bool LittleEndian)
static void dumpAddrSection (raw_ostream &OS, DWARFDataExtractor &AddrData, DIDumpOptions DumpOpts, uint16_t Version, uint8_t AddrSize)
static void dumpRnglistsSection (raw_ostream &OS, DWARFDataExtractor &rnglistData, llvm::function_ref< Optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress, DIDumpOptions DumpOpts)
static void dumpLoclistsSection (raw_ostream &OS, DIDumpOptions DumpOpts, DWARFDataExtractor Data, const MCRegisterInfo *MRI, const DWARFObject &Obj, Optional< uint64_t > DumpOffset)
static void dumpPubTableSection (raw_ostream &OS, DIDumpOptions DumpOpts, DWARFDataExtractor Data, bool GnuStyle)
template<typename T >
static T & getAccelTable (std::unique_ptr< T > &Cache, const DWARFObject &Obj, const DWARFSection &Section, StringRef StringSection, bool IsLittleEndian)
static bool getFunctionNameAndStartLineForAddress (DWARFCompileUnit *CU, uint64_t Address, FunctionNameKind Kind, DILineInfoSpecifier::FileLineInfoKind FileNameKind, std::string &FunctionName, std::string &StartFile, uint32_t &StartLine)
TODO: change input parameter from "uint64_t Address" into "SectionedAddress Address".
static Optional< uint64_t > getTypeSize (DWARFDie Type, uint64_t PointerSize)
static Optional< int64_t > getExpressionFrameOffset (ArrayRef< uint8_t > Expr, Optional< unsigned > FrameBaseReg)
static Error createError (const Twine &Reason, llvm::Error E)
static Expected< SymInfo > getSymbolInfo (const object::ObjectFile &Obj, const RelocationRef &Reloc, const LoadedObjectInfo *L, std::map< SymbolRef, SymInfo > &Cache)
Returns the address of symbol relocation used against and a section index.
static bool isRelocScattered (const object::ObjectFile &Obj, const RelocationRef &Reloc)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarf"
Definition at line 61 of file DWARFContext.cpp.
Typedef Documentation
ContributionCollection
using ContributionCollection
Initial value:
    std::vector<Optional<StrOffsetsContributionDescriptor>>
Definition at line 99 of file DWARFContext.cpp.
DWARFLineTable
using DWARFLineTable = DWARFDebugLine::LineTable
Definition at line 63 of file DWARFContext.cpp.
Function Documentation
collectContributionData()
static ContributionCollection collectContributionData (DWARFContext::unit_iterator_range Units) static
Definition at line 105 of file DWARFContext.cpp.
References C, and llvm::sort().
Referenced by dumpStringOffsetsSection().
createError()
static Error createError (const Twine & Reason, llvm::Error E) static
Definition at line 1411 of file DWARFContext.cpp.
References E, llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::toString().
dumpAddrSection()
static void dumpAddrSection (raw_ostream & OS, DWARFDataExtractor & AddrData, DIDumpOptions DumpOpts, uint16_t Version, uint8_t AddrSize) static
Definition at line 217 of file DWARFContext.cpp.
References llvm::DWARFDebugAddrTable::dump(), llvm::DWARFDebugAddrTable::extract(), llvm::DWARFDebugAddrTable::getFullLength(), llvm::DataExtractor::isValidOffset(), Offset, llvm::DIDumpOptions::RecoverableErrorHandler, and llvm::DIDumpOptions::WarningHandler.
Referenced by llvm::DWARFContext::dump().
dumpLoclistsSection()
static void dumpLoclistsSection (raw_ostream & OS, DIDumpOptions DumpOpts, DWARFDataExtractor Data, const MCRegisterInfo * MRI, const DWARFObject & Obj, Optional< uint64_t > DumpOffset) static
Definition at line 305 of file DWARFContext.cpp.
References llvm::Data, llvm::DWARFListTableHeader::dump(), E, llvm::DWARFListTableHeader::extract(), llvm::DWARFListTableHeader::getAddrSize(), llvm::DWARFListTableHeader::getHeaderOffset(), llvm::DWARFListTableHeader::getVersion(), llvm::DWARFListTableHeader::length(), MRI, llvm::None, Offset, and llvm::DIDumpOptions::RecoverableErrorHandler.
Referenced by llvm::DWARFContext::dump().
dumpPubTableSection()
static void dumpPubTableSection (raw_ostream & OS, DIDumpOptions DumpOpts, DWARFDataExtractor Data, bool GnuStyle) static
Definition at line 339 of file DWARFContext.cpp.
References llvm::Data, llvm::DWARFDebugPubTable::dump(), llvm::DWARFDebugPubTable::extract(), and llvm::DIDumpOptions::RecoverableErrorHandler.
Referenced by llvm::DWARFContext::dump().
dumpRnglistsSection()
static void dumpRnglistsSection (raw_ostream & OS, DWARFDataExtractor & rnglistData, llvm::function_ref< Optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress, DIDumpOptions DumpOpts) static
Definition at line 240 of file DWARFContext.cpp.
References llvm::DWARFListTableBase< DWARFListType >::dump(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DataExtractor::isValidOffset(), llvm::DWARFListTableBase< DWARFListType >::length(), Offset, and llvm::DIDumpOptions::RecoverableErrorHandler.
Referenced by llvm::DWARFContext::dump().
dumpStringOffsetsSection()
static void dumpStringOffsetsSection (raw_ostream & OS, DIDumpOptions DumpOpts, StringRef SectionName, const DWARFObject & Obj, const DWARFSection & StringOffsetsSection, StringRef StringSection, DWARFContext::unit_iterator_range Units, bool LittleEndian) static
Definition at line 144 of file DWARFContext.cpp.
References collectContributionData(), llvm::createStringError(), llvm::DWARFSection::Data, llvm::dwarf::DWARF32, llvm::format(), llvm::dwarf::FormatString(), llvm::DataExtractor::getCStr(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::invalid_argument, Offset, llvm::DIDumpOptions::RecoverableErrorHandler, and llvm::StringRef::size().
Referenced by llvm::DWARFContext::dump().
dumpUUID()
static void dumpUUID (raw_ostream & OS, const ObjectFile & Obj) static
Dump the UUID load command.
Definition at line 78 of file DWARFContext.cpp.
References llvm::dyn_cast(), and llvm::raw_ostream::write_uuid().
Referenced by llvm::DWARFContext::dump().
getAccelTable()
template<typename T > static T & getAccelTable (std::unique_ptr< T > & Cache, const DWARFObject & Obj, const DWARFSection & Section, StringRef StringSection, bool IsLittleEndian) static
Definition at line 884 of file DWARFContext.cpp.
References llvm::consumeError(), E, and T.
Referenced by llvm::DWARFContext::getAppleNames(), llvm::DWARFContext::getAppleNamespaces(), llvm::DWARFContext::getAppleObjC(), llvm::DWARFContext::getAppleTypes(), and llvm::DWARFContext::getDebugNames().
getExpressionFrameOffset()
static Optional< int64_t > getExpressionFrameOffset (ArrayRef< uint8_t > Expr, Optional< unsigned > FrameBaseReg) static
Definition at line 1127 of file DWARFContext.cpp.
References llvm::Count, llvm::ArrayRef< T >::data(), llvm::decodeSLEB128(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::None, Offset, and llvm::ArrayRef< T >::size().
getFunctionNameAndStartLineForAddress()
static bool getFunctionNameAndStartLineForAddress (DWARFCompileUnit * CU, uint64_t Address, FunctionNameKind Kind, DILineInfoSpecifier::FileLineInfoKind FileNameKind, std::string & FunctionName, std::string & StartFile, uint32_t & StartLine) static
TODO: change input parameter from "uint64_t Address" into "SectionedAddress Address".
Definition at line 1034 of file DWARFContext.cpp.
References llvm::SmallVectorBase< Size_T >::empty(), and Name.
Referenced by llvm::DWARFContext::getLineInfoForAddress(), and llvm::DWARFContext::getLineInfoForAddressRange().
getSymbolInfo()
static Expected< SymInfo > getSymbolInfo (const object::ObjectFile & Obj, const RelocationRef & Reloc, const LoadedObjectInfo * L, std::map< SymbolRef, SymInfo > & Cache) static
Returns the address of symbol relocation used against and a section index.
Used for futher relocations computation. Symbol's section load address is
Definition at line 1425 of file DWARFContext.cpp.
References llvm::createError(), llvm::dyn_cast(), llvm::object::SymbolRef::getAddress(), llvm::object::RelocationRef::getRawDataRefImpl(), llvm::object::SymbolRef::getSection(), llvm::LoadedObjectInfo::getSectionLoadAddress(), llvm::object::RelocationRef::getSymbol(), llvm::object::ObjectFile::section_end(), llvm::object::SymbolicFile::symbol_end(), and llvm::Expected< T >::takeError().
getTypeSize()
static Optional< uint64_t > getTypeSize (DWARFDie Type, uint64_t PointerSize) static
Definition at line 1069 of file DWARFContext.cpp.
References getTypeSize(), and Size.
Referenced by getTypeSize().
isRelocScattered()
static bool isRelocScattered (const object::ObjectFile & Obj, const RelocationRef & Reloc) static
Definition at line 1480 of file DWARFContext.cpp.
References llvm::dyn_cast(), llvm::object::RelocationRef::getRawDataRefImpl(), llvm::object::MachOObjectFile::getRelocation(), and llvm::object::MachOObjectFile::isRelocationScattered().