LLVM: lib/ExecutionEngine/JITLink/ELF_x86_64.cpp File Reference
ELF_x86_64.cpp File Reference
#include "llvm/ExecutionEngine/JITLink/ELF_x86_64.h"
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Support/Endian.h"
#include "BasicGOTAndStubsBuilder.h"
#include "EHFrameSupportImpl.h"
#include "JITLinkGeneric.h"
#include "llvm/BinaryFormat/Dwarf.def"
Classes
class llvm::jitlink::ELFLinkGraphBuilder_x86_64
class llvm::jitlink::ELFJITLinker_x86_64
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::jitlink
Macros
#define DEBUG_TYPE "jitlink"
#define HANDLE_DWARF_SECTION(ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)
Functions
static Error optimizeELF_x86_64_GOTAndStubs (LinkGraph &G)
static bool isDwarfSection (StringRef SectionName)
Expected< std::unique_ptr< LinkGraph > > llvm::jitlink::createLinkGraphFromELFObject_x86_64 (MemoryBufferRef ObjectBuffer)
Create a LinkGraph from an ELF/x86-64 relocatable object.
void llvm::jitlink::link_ELF_x86_64 (std::unique_ptr< LinkGraph > G, std::unique_ptr< JITLinkContext > Ctx)
jit-link the given object buffer, which must be a ELF x86-64 object file.
StringRef llvm::jitlink::getELFX86RelocationKindName (Edge::Kind R)
Return the string name of the given ELF x86-64 edge kind.
Variables
static const char * CommonSectionName = "__common"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "jitlink"
Definition at line 22 of file ELF_x86_64.cpp.
HANDLE_DWARF_SECTION
#define HANDLE_DWARF_SECTION (ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)
Value:
  ELF_NAME,
Function Documentation
isDwarfSection()
static bool isDwarfSection (StringRef SectionName) static
Definition at line 206 of file ELF_x86_64.cpp.
Referenced by llvm::NVPTXTargetStreamer::changeSection().
optimizeELF_x86_64_GOTAndStubs()
static Error optimizeELF_x86_64_GOTAndStubs (LinkGraph & G) static
Definition at line 132 of file ELF_x86_64.cpp.
References assert(), B, llvm::jitlink::ELF_x86_64_Edges::Branch32, llvm::jitlink::ELF_x86_64_Edges::Branch32ToStub, llvm::dbgs(), E, G, llvm::jitlink::getELFX86RelocationKindName(), LLVM_DEBUG, llvm::jitlink::ELF_x86_64_Edges::PCRel32, llvm::jitlink::ELF_x86_64_Edges::PCRel32GOTLoad, llvm::jitlink::printEdge(), and llvm::Error::success().
Referenced by llvm::jitlink::link_ELF_x86_64().
Variable Documentation
CommonSectionName
const char* CommonSectionName = "__common" static
Definition at line 131 of file ELF_x86_64.cpp.