LLVM: lib/Support/FileCollector.cpp File Reference
FileCollector.cpp File Reference
#include "llvm/Support/FileCollector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
Classes
class llvm::FileCollectorFileSystem
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static bool isCaseSensitivePath (StringRef Path)
static void makeAbsolute (SmallVectorImpl< char > &Path)
Make Path absolute.
static std::error_code copyAccessAndModificationTime (StringRef Filename, const sys::fs::file_status &Stat)
Set the access and modification time for the given file from the given status object.
Function Documentation
copyAccessAndModificationTime()
static std::error_code copyAccessAndModificationTime (StringRef Filename, const sys::fs::file_status & Stat) static
Set the access and modification time for the given file from the given status object.
Definition at line 158 of file FileCollector.cpp.
References llvm::sys::fs::CD_OpenExisting, llvm::sys::fs::basic_file_status::getLastAccessedTime(), llvm::sys::fs::basic_file_status::getLastModificationTime(), llvm::sys::fs::openFileForWrite(), llvm::sys::Process::SafelyCloseFileDescriptor(), and llvm::sys::fs::setLastAccessAndModificationTime().
Referenced by llvm::FileCollector::copyFiles().
isCaseSensitivePath()
static bool isCaseSensitivePath (StringRef Path) static
Definition at line 34 of file FileCollector.cpp.
References llvm::StringRef::equals(), llvm::sys::fs::real_path(), and llvm::StringRef::upper().
Referenced by llvm::FileCollector::writeMapping().
makeAbsolute()
static void makeAbsolute (SmallVectorImpl< char > & Path) static
Make Path absolute.
Definition at line 89 of file FileCollector.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::begin(), llvm::SmallVectorImpl< T >::erase(), llvm::sys::fs::make_absolute(), llvm::sys::path::native, llvm::sys::path::remove_leading_dotslash(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::FileCollector::PathCanonicalizer::canonicalize().