LLVM: lib/Transforms/IPO/ForceFunctionAttrs.cpp File Reference
ForceFunctionAttrs.cpp File Reference
#include "llvm/Transforms/IPO/ForceFunctionAttrs.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "forceattrs"
Functions
static Attribute::AttrKind parseAttrKind (StringRef Kind)
static void forceAttributes (Function &F)
If F has any forced attributes given on the command line, add them.
static bool hasForceAttributes ()
INITIALIZE_PASS (ForceFunctionAttrsLegacyPass, "forceattrs", "Force set function attributes", false, false) Pass *llvm
Variables
static cl::list< std::string > ForceAttributes ("force-attribute", cl::Hidden, cl::desc("Add an attribute to a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-attribute=foo:noinline. This " "option can be specified multiple times."))
static cl::list< std::string > ForceRemoveAttributes ("force-remove-attribute", cl::Hidden, cl::desc("Remove an attribute from a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-remove-attribute=foo:noinline. This " "option can be specified multiple times."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "forceattrs"
Definition at line 20 of file ForceFunctionAttrs.cpp.
Function Documentation
forceAttributes()
static void forceAttributes (Function & F) static
If F has any forced attributes given on the command line, add them.
If F has any forced remove attributes given on the command line, remove them. When both force and force-remove are given to a function, the latter takes precedence.
Definition at line 83 of file ForceFunctionAttrs.cpp.
References llvm::dbgs(), F, ForceAttributes, ForceRemoveAttributes, LLVM_DEBUG, parseAttrKind(), and llvm::StringRef::split().
Referenced by llvm::ForceFunctionAttrsPass::run().
hasForceAttributes()
static bool hasForceAttributes () static
Definition at line 112 of file ForceFunctionAttrs.cpp.
References ForceAttributes, and ForceRemoveAttributes.
Referenced by llvm::ForceFunctionAttrsPass::run().
INITIALIZE_PASS()
INITIALIZE_PASS (ForceFunctionAttrsLegacyPass , "forceattrs" , "Force set function attributes" , false , false)
Definition at line 150 of file ForceFunctionAttrs.cpp.
parseAttrKind()
static Attribute::AttrKind parseAttrKind (StringRef Kind) static
Definition at line 36 of file ForceFunctionAttrs.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by forceAttributes().
Variable Documentation
ForceAttributes
cl::list< std::string > ForceAttributes("force-attribute", cl::Hidden, cl::desc("Add an attribute to a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-attribute=foo:noinline. This " "option can be specified multiple times.")) ("force-attribute" , cl::Hidden , cl::desc("Add an attribute to a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-attribute=foo:noinline. This " "option can be specified multiple times.")) static
Referenced by forceAttributes(), and hasForceAttributes().
ForceRemoveAttributes
cl::list< std::string > ForceRemoveAttributes("force-remove-attribute", cl::Hidden, cl::desc("Remove an attribute from a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-remove-attribute=foo:noinline. This " "option can be specified multiple times.")) ("force-remove-attribute" , cl::Hidden , cl::desc("Remove an attribute from a function. This should be a " "pair of 'function-name:attribute-name', for " "example -force-remove-attribute=foo:noinline. This " "option can be specified multiple times.")) static
Referenced by forceAttributes(), and hasForceAttributes().