LLVM: lib/CodeGen/SelectionDAG/FunctionLoweringInfo.cpp File Reference
FunctionLoweringInfo.cpp File Reference
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "function-lowering-info"
Functions
static bool isUsedOutsideOfDefiningBlock (const Instruction *I)
isUsedOutsideOfDefiningBlock - Return true if this instruction is used by PHI nodes or outside of the basic block that defines it, or used by a switch or atomic instruction, which may expand to multiple basic blocks.
static ISD::NodeType getPreferredExtendForValue (const Value *V)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "function-lowering-info"
Definition at line 44 of file FunctionLoweringInfo.cpp.
Function Documentation
getPreferredExtendForValue()
static ISD::NodeType getPreferredExtendForValue (const Value * V) static
Definition at line 60 of file FunctionLoweringInfo.cpp.
References llvm::ISD::ANY_EXTEND, llvm::dyn_cast(), llvm::ISD::SIGN_EXTEND, and llvm::Value::users().
Referenced by llvm::FunctionLoweringInfo::set().
isUsedOutsideOfDefiningBlock()
static bool isUsedOutsideOfDefiningBlock (const Instruction * I) static
isUsedOutsideOfDefiningBlock - Return true if this instruction is used by PHI nodes or outside of the basic block that defines it, or used by a switch or atomic instruction, which may expand to multiple basic blocks.
Definition at line 49 of file FunctionLoweringInfo.cpp.
References llvm::cast(), getParent(), llvm::BasicBlock::getParent(), I, llvm::isa(), and llvm::Value::users().
Referenced by llvm::FunctionLoweringInfo::set().