LLVM: lib/IR/Globals.cpp File Reference
Globals.cpp File Reference
#include "LLVMContextImpl.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/IR/Value.def"
Macros
#define HANDLE_GLOBAL_VALUE(NAME)
#define HANDLE_GLOBAL_VALUE(NAME)
Functions
static const GlobalObject * findBaseObject (const Constant *C, DenseSet< const GlobalAlias * > &Aliases)
Macro Definition Documentation
HANDLE_GLOBAL_VALUE [1/2]
#define HANDLE_GLOBAL_VALUE (NAME)
Value:
  case Value::NAME##Val:                                                       \
    return static_cast<NAME *>(this)->removeFromParent();
HANDLE_GLOBAL_VALUE [2/2]
#define HANDLE_GLOBAL_VALUE (NAME)
Value:
  case Value::NAME##Val:                                                       \
    return static_cast<NAME *>(this)->eraseFromParent();
Function Documentation
findBaseObject()
static const GlobalObject * findBaseObject (const Constant * C, DenseSet< const GlobalAlias * > & Aliases) static
Definition at line 435 of file Globals.cpp.
References C, llvm::dyn_cast(), findBaseObject(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by findBaseObject(), and llvm::GlobalIndirectSymbol::getBaseObject().