LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCShuffler.cpp File Reference
HexagonMCShuffler.cpp File Reference
#include "MCTargetDesc/HexagonMCShuffler.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "MCTargetDesc/HexagonShuffler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Macros
#define DEBUG_TYPE "hexagon-shuffle"
Variables
static cl::opt< bool > DisableShuffle ("disable-hexagon-shuffle", cl::Hidden, cl::init(false), cl::desc("Disable Hexagon instruction shuffling"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-shuffle"
Definition at line 14 of file HexagonMCShuffler.cpp.
Variable Documentation
DisableShuffle
cl::opt< bool > DisableShuffle("disable-hexagon-shuffle", cl::Hidden, cl::init(false), cl::desc("Disable Hexagon instruction shuffling")) ("disable-hexagon-shuffle" , cl::Hidden , cl::init(false) , cl::desc("Disable Hexagon instruction shuffling")) static
Referenced by llvm::HexagonMCShuffle(), llvm::HexagonMCShuffle(), and llvm::HexagonMCShuffle().