LLVM: lib/Transforms/Scalar/InferAddressSpaces.cpp File Reference
InferAddressSpaces.cpp File Reference
#include "llvm/Transforms/Scalar/InferAddressSpaces.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <cassert>
#include <iterator>
#include <limits>
#include <utility>
#include <vector>
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "infer-address-spaces"
Functions
void llvm::initializeInferAddressSpacesPass (PassRegistry &)
INITIALIZE_PASS (InferAddressSpaces, DEBUG_TYPE, "Infer address spaces", false, false) static bool isNoopPtrIntCastPair(const Operator *I2P
if (!P2I||P2I->getOpcode() !=Instruction::PtrToInt) return false
return static CastInst::isNoopCast(Instruction::CastOps(I2P->getOpcode()), I2P->getOperand(0) ->getType(), I2P->getType(), DL) &&CastInst bool isAddressExpression (const Value &V, const DataLayout &DL, const TargetTransformInfo *TTI)
static SmallVector< Value *, 2 > getPointerOperands (const Value &V, const DataLayout &DL, const TargetTransformInfo *TTI)
static Value * operandWithNewAddressSpaceOrCreateUndef (const Use &OperandUse, unsigned NewAddrSpace, const ValueToValueMapTy &ValueWithNewAddrSpace, SmallVectorImpl< const Use * > *UndefUsesToFix)
static Value * cloneConstantExprWithNewAddressSpace (ConstantExpr *CE, unsigned NewAddrSpace, const ValueToValueMapTy &ValueWithNewAddrSpace, const DataLayout *DL, const TargetTransformInfo *TTI)
static bool isSimplePointerUseValidToReplace (const TargetTransformInfo &TTI, Use &U, unsigned AddrSpace)
returns true if U is the pointer operand of a memory instruction with a single pointer operand that can have its address space changed by simply mutating the use to a new value.
static bool handleMemIntrinsicPtrUse (MemIntrinsic *MI, Value *OldV, Value *NewV)
Update memory intrinsic uses that require more complex processing than simple memory instructions.
static Value::use_iterator skipToNextUser (Value::use_iterator I, Value::use_iterator End)
Variables
static cl::opt< bool > AssumeDefaultIsFlatAddressSpace ("assume-default-is-flat-addrspace", cl::init(false), cl::ReallyHidden, cl::desc("The default address space is assumed as the flat address space. " "This is mainly for test purpose."))
static const unsigned UninitializedAddressSpace
const DataLayout & DL
const DataLayout const TargetTransformInfo * TTI
auto * P2I = dyn_cast<Operator>(I2P->getOperand(0))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "infer-address-spaces"
Definition at line 134 of file InferAddressSpaces.cpp.
Function Documentation
cloneConstantExprWithNewAddressSpace()
static Value * cloneConstantExprWithNewAddressSpace (ConstantExpr * CE, unsigned NewAddrSpace, const ValueToValueMapTy & ValueWithNewAddrSpace, const DataLayout * DL, const TargetTransformInfo * TTI) static
Definition at line 633 of file InferAddressSpaces.cpp.
References assert(), llvm::cast(), cloneConstantExprWithNewAddressSpace(), DL, llvm::dyn_cast(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::ConstantExpr::getBitCast(), llvm::Type::getPointerAddressSpace(), llvm::ConstantExpr::getSelect(), getType(), llvm::Value::getType(), Index, llvm::ValueMap< KeyT, ValueT, Config >::lookup(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by cloneConstantExprWithNewAddressSpace().
getPointerOperands()
static SmallVector< Value *, 2 > getPointerOperands (const Value & V, const DataLayout & DL, const TargetTransformInfo * TTI) static
Definition at line 307 of file InferAddressSpaces.cpp.
References assert(), llvm::cast(), DL, llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm_unreachable, P2I, llvm::Intrinsic::ptrmask, and llvm::SmallVector.
handleMemIntrinsicPtrUse()
static bool handleMemIntrinsicPtrUse (MemIntrinsic * MI, Value * OldV, Value * NewV) static
Update memory intrinsic uses that require more complex processing than simple memory instructions.
Thse require re-mangling and may have multiple pointer operands.
Definition at line 933 of file InferAddressSpaces.cpp.
References assert(), B, llvm::dyn_cast(), llvm::isa(), llvm_unreachable, and MI.
if()
if (!P2I||P2I->getOpcode() ! = Instruction::PtrToInt)
INITIALIZE_PASS()
INITIALIZE_PASS (InferAddressSpaces , DEBUG_TYPE , "Infer address spaces" , false , false) const
isAddressExpression()
return static CastInst::isNoopCast(Instruction::CastOps(I2P->getOpcode()), I2P->getOperand(0) ->getType(), I2P->getType(), DL) &&CastInst bool isAddressExpression (const Value & V, const DataLayout & DL, const TargetTransformInfo * TTI) static
Definition at line 275 of file InferAddressSpaces.cpp.
References assert(), DL, llvm::dyn_cast(), llvm::TargetTransformInfo::getAssumedAddrSpace(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Intrinsic::ptrmask, and UninitializedAddressSpace.
isSimplePointerUseValidToReplace()
static bool isSimplePointerUseValidToReplace (const TargetTransformInfo & TTI, Use & U, unsigned AddrSpace) static
returns true if U is the pointer operand of a memory instruction with a single pointer operand that can have its address space changed by simply mutating the use to a new value.
If the memory instruction is volatile, return true only if the target allows the memory instruction to be volatile in the new address space.
Definition at line 903 of file InferAddressSpaces.cpp.
References llvm::dyn_cast(), llvm::AtomicCmpXchgInst::getPointerOperandIndex(), llvm::AtomicRMWInst::getPointerOperandIndex(), llvm::LoadInst::getPointerOperandIndex(), llvm::StoreInst::getPointerOperandIndex(), llvm::TargetTransformInfo::hasVolatileVariant(), I, and SI.
operandWithNewAddressSpaceOrCreateUndef()
static Value * operandWithNewAddressSpaceOrCreateUndef (const Use & OperandUse, unsigned NewAddrSpace, const ValueToValueMapTy & ValueWithNewAddrSpace, SmallVectorImpl< const Use * > * UndefUsesToFix) static
Definition at line 505 of file InferAddressSpaces.cpp.
References C, llvm::dyn_cast(), llvm::UndefValue::get(), llvm::Use::get(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::Type::getPointerElementType(), llvm::Type::getPointerTo(), llvm::Value::getType(), llvm::ValueMap< KeyT, ValueT, Config >::lookup(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
skipToNextUser()
static Value::use_iterator skipToNextUser (Value::use_iterator I, Value::use_iterator End) static
Definition at line 1007 of file InferAddressSpaces.cpp.
References I.
Variable Documentation
AssumeDefaultIsFlatAddressSpace
cl::opt< bool > AssumeDefaultIsFlatAddressSpace("assume-default-is-flat-addrspace", cl::init(false), cl::ReallyHidden, cl::desc("The default address space is assumed as the flat address space. " "This is mainly for test purpose.")) ("assume-default-is-flat-addrspace" , cl::init(false) , cl::ReallyHidden , cl::desc("The default address space is assumed as the flat address space. " "This is mainly for test purpose.")) static
DL
const DataLayout& DL
Definition at line 241 of file InferAddressSpaces.cpp.
Referenced by getPointerOperands(), and isAddressExpression().
P2I
auto* P2I = dyn_cast<Operator>(I2P->getOperand(0))
Definition at line 244 of file InferAddressSpaces.cpp.
Referenced by BuildConstantFromSCEV(), getPointerOperands(), and isKnownNonZero().
TTI
const DataLayout const TargetTransformInfo* TTI
Initial value:
{
  assert(I2P->getOpcode() == Instruction::IntToPtr)
Definition at line 242 of file InferAddressSpaces.cpp.
UninitializedAddressSpace
const unsigned UninitializedAddressSpace static
Initial value:
=
    std::numeric_limits<unsigned>::max()
Definition at line 143 of file InferAddressSpaces.cpp.
Referenced by isAddressExpression().