LLVM: lib/Target/Lanai/LanaiMemAluCombiner.cpp File Reference
LanaiMemAluCombiner.cpp File Reference
#include "LanaiAluCode.h"
#include "LanaiTargetMachine.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/Support/CommandLine.h"
#include "LanaiGenInstrInfo.inc"
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define GET_INSTRMAP_INFO
#define DEBUG_TYPE "lanai-mem-alu-combiner"
Functions
STATISTIC (NumLdStAluCombined, "Number of memory and ALU instructions combined")
void llvm::initializeLanaiMemAluCombinerPass (PassRegistry &)
INITIALIZE_PASS (LanaiMemAluCombiner, DEBUG_TYPE, "Lanai memory ALU combiner pass", false, false) namespace
Variables
static llvm::cl::opt< bool > DisableMemAluCombiner ("disable-lanai-mem-alu-combiner", llvm::cl::init(false), llvm::cl::desc("Do not combine ALU and memory operators"), llvm::cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lanai-mem-alu-combiner"
Definition at line 39 of file LanaiMemAluCombiner.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 36 of file LanaiMemAluCombiner.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LanaiMemAluCombiner , DEBUG_TYPE , "Lanai memory ALU combiner pass" , false , false)
Definition at line 91 of file LanaiMemAluCombiner.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::LPAC::AND, assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), DisableMemAluCombiner, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase(), llvm::getDefRegState(), llvm::MachineOperand::getImm(), llvm::getKillRegState(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getType(), llvm::MachineMemOperand::isAtomic(), llvm::MachineOperand::isImm(), llvm::isInt(), llvm::isInt< 16 >(), llvm::MachineOperand::isReg(), llvm::MachineMemOperand::isVolatile(), llvm::Last, llvm_unreachable, llvm::LPAC::makePostOp(), llvm::LPAC::makePreOp(), MI, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_Register, Modified, llvm::LPAC::modifiesOp(), Offset, llvm::LPAC::OR, llvm::MachineInstrBuilder::setMemRefs(), llvm::LPAC::SHL, llvm::LPAC::SRA, llvm::LPAC::SRL, llvm::LPAC::SUB, TII, llvm::LPAC::UNKNOWN, and llvm::LPAC::XOR.
STATISTIC()
STATISTIC (NumLdStAluCombined , "Number of memory and ALU instructions combined")
Variable Documentation
DisableMemAluCombiner
llvm::cl::opt< bool > DisableMemAluCombiner("disable-lanai-mem-alu-combiner", llvm::cl::init(false), llvm::cl::desc("Do not combine ALU and memory operators"), llvm::cl::Hidden) ("disable-lanai-mem-alu-combiner" , llvm::cl::init(false) , llvm::cl::desc("Do not combine ALU and memory operators") , llvm::cl::Hidden) static
Referenced by INITIALIZE_PASS().