LLVM: lib/ToolDrivers/llvm-lib/LibDriver.cpp File Reference
LibDriver.cpp File Reference
#include "llvm/ToolDrivers/llvm-lib/LibDriver.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/WindowsMachineFlag.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/raw_ostream.h"
#include "Options.inc"
Macros
#define OPTION(_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12)
#define PREFIX(NAME, VALUE)
#define OPTION(X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Functions
static std::string getDefaultOutputPath (const NewArchiveMember &FirstMember)
static std::vector< StringRef > getSearchPaths (opt::InputArgList *Args, StringSaver &Saver)
static std::string findInputFile (StringRef File, ArrayRef< StringRef > Paths)
static void fatalOpenError (llvm::Error E, Twine File)
static void doList (opt::InputArgList &Args)
static Expected< COFF::MachineTypes > getCOFFFileMachine (MemoryBufferRef MB)
static Expected< COFF::MachineTypes > getBitcodeFileMachine (MemoryBufferRef MB)
static void appendFile (std::vector< NewArchiveMember > &Members, COFF::MachineTypes &LibMachine, std::string &LibMachineSource, MemoryBufferRef MB)
Macro Definition Documentation
OPTION [1/2]
#define OPTION (_1, _2, ID, _4, _5, _6, _7, _8, _9, _10, _11, _12)
Value:
OPT_##ID,
Definition at line 38 of file LibDriver.cpp.
OPTION [2/2]
#define OPTION (X1, X2, ID, KIND, GROUP, ALIAS, X7, X8, X9, X10, X11, X12)
Value:
  {X1, X2, X10,         X11,         OPT_##ID, opt::Option::KIND##Class,       \
   X9, X8, OPT_##GROUP, OPT_##ALIAS, X7,       X12},
Definition at line 38 of file LibDriver.cpp.
PREFIX
#define PREFIX (NAME, VALUE)
Value:
const char *const NAME[] = VALUE;
Definition at line 43 of file LibDriver.cpp.
Function Documentation
appendFile()
static void appendFile (std::vector< NewArchiveMember > & Members, COFF::MachineTypes & LibMachine, std::string & LibMachineSource, MemoryBufferRef MB) static
Definition at line 180 of file LibDriver.cpp.
References appendFile(), llvm::file_magic::archive, llvm::file_magic::bitcode, C, llvm::object::Archive::children(), llvm::file_magic::coff_import_library, llvm::file_magic::coff_object, llvm::errs(), fatalOpenError(), getBitcodeFileMachine(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferIdentifier(), getCOFFFileMachine(), llvm::handleAllErrors(), llvm::identify_magic(), llvm::COFF::IMAGE_FILE_MACHINE_UNKNOWN, llvm::machineToStr(), Magic, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::file_magic::windows_resource.
Referenced by appendFile(), and llvm::libDriverMain().
doList()
static void doList (opt::InputArgList & Args) static
Definition at line 110 of file LibDriver.cpp.
References llvm::file_magic::archive, Arg, B, C, llvm::object::Archive::children(), llvm::errorCodeToError(), fatalOpenError(), llvm::ErrorOr< T >::get(), llvm::Expected< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), llvm::identify_magic(), Name, llvm::outs(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by llvm::libDriverMain().
fatalOpenError()
static void fatalOpenError (llvm::Error E, Twine File) static
Definition at line 101 of file LibDriver.cpp.
References E, llvm::errs(), llvm::handleAllErrors(), and llvm::ErrorInfoBase::message().
Referenced by appendFile(), doList(), and llvm::libDriverMain().
findInputFile()
static std::string findInputFile (StringRef File, ArrayRef< StringRef > Paths) static
Definition at line 91 of file LibDriver.cpp.
References llvm::sys::path::append(), and llvm::sys::fs::exists().
Referenced by llvm::libDriverMain().
getBitcodeFileMachine()
static Expected< COFF::MachineTypes > getBitcodeFileMachine (MemoryBufferRef MB) static
Definition at line 160 of file LibDriver.cpp.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm::createStringError(), llvm::Triple::getArch(), llvm::getBitcodeTargetTriple(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::inconvertibleErrorCode(), llvm::Expected< T >::takeError(), llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by appendFile().
getCOFFFileMachine()
static Expected< COFF::MachineTypes > getCOFFFileMachine (MemoryBufferRef MB) static
Definition at line 142 of file LibDriver.cpp.
References llvm::object::COFFObjectFile::create(), llvm::createStringError(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, and llvm::inconvertibleErrorCode().
Referenced by appendFile().
getDefaultOutputPath()
static std::string getDefaultOutputPath (const NewArchiveMember & FirstMember) static
Definition at line 62 of file LibDriver.cpp.
References llvm::NewArchiveMember::Buf, llvm::sys::path::replace_extension(), and llvm::SmallString< N >::str().
Referenced by llvm::libDriverMain().
getSearchPaths()
static std::vector< StringRef > getSearchPaths (opt::InputArgList * Args, StringSaver & Saver) static
Definition at line 68 of file LibDriver.cpp.
References Arg, llvm::StringRef::empty(), llvm::sys::Process::GetEnv(), llvm::Optional< T >::hasValue(), llvm::StringSaver::save(), and llvm::StringRef::split().
Referenced by llvm::libDriverMain().