LLVM: lib/Transforms/Utils/LoopRotationUtils.cpp File Reference
LoopRotationUtils.cpp File Reference
#include "llvm/Transforms/Utils/LoopRotationUtils.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
Macros
#define DEBUG_TYPE "loop-rotate"
Functions
STATISTIC (NumNotRotatedDueToHeaderSize, "Number of loops not rotated due to the header size")
STATISTIC (NumRotated, "Number of loops rotated")
static void InsertNewValueIntoMap (ValueToValueMapTy &VM, Value *K, Value *V)
Insert (K, V) pair into the ValueToValueMap, and verify the key did not previously exist in the map, and the value was inserted.
static void RewriteUsesOfClonedInstructions (BasicBlock *OrigHeader, BasicBlock *OrigPreheader, ValueToValueMapTy &ValueMap, SmallVectorImpl< PHINode * > *InsertedPHIs)
RewriteUsesOfClonedInstructions - We just cloned the instructions from the old header into the preheader.
static bool profitableToRotateLoopExitingLatch (Loop *L)
static bool canRotateDeoptimizingLatchExit (Loop *L)
static bool shouldSpeculateInstrs (BasicBlock::iterator Begin, BasicBlock::iterator End, Loop *L)
Determine whether the instructions in this range may be safely and cheaply speculated.
Variables
static cl::opt< bool > MultiRotate ("loop-rotate-multi", cl::init(false), cl::Hidden, cl::desc("Allow loop rotation multiple times in order to reach " "a better latch exit"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-rotate"
Definition at line 45 of file LoopRotationUtils.cpp.
Function Documentation
canRotateDeoptimizingLatchExit()
static bool canRotateDeoptimizingLatchExit (Loop * L) static
Definition at line 217 of file LoopRotationUtils.cpp.
References llvm::any_of(), assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getPostdominatingDeoptimizeCall(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlocks(), and llvm::BranchInst::isConditional().
InsertNewValueIntoMap()
static void InsertNewValueIntoMap (ValueToValueMapTy & VM, Value * K, Value * V) static
Insert (K, V) pair into the ValueToValueMap, and verify the key did not previously exist in the map, and the value was inserted.
Definition at line 90 of file LoopRotationUtils.cpp.
References assert(), and llvm::ValueMap< KeyT, ValueT, Config >::insert().
profitableToRotateLoopExitingLatch()
static bool profitableToRotateLoopExitingLatch (Loop * L) static
Definition at line 192 of file LoopRotationUtils.cpp.
References llvm::any_of(), assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::BranchInst::isConditional(), and llvm::BasicBlock::phis().
RewriteUsesOfClonedInstructions()
static void RewriteUsesOfClonedInstructions (BasicBlock * OrigHeader, BasicBlock * OrigPreheader, ValueToValueMapTy & ValueMap, SmallVectorImpl< PHINode * > * InsertedPHIs) static
RewriteUsesOfClonedInstructions - We just cloned the instructions from the old header into the preheader.
If there were uses of the values produced by these instruction that were outside of the loop, we have to insert PHI nodes to merge the two values. Do this now.
Definition at line 99 of file LoopRotationUtils.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), llvm::dyn_cast(), E, llvm::BasicBlock::end(), llvm::findDbgValues(), llvm::MetadataAsValue::get(), llvm::UndefValue::get(), llvm::ValueAsMetadata::get(), llvm::Value::getContext(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), I, llvm::isa(), llvm::ValueMap< KeyT, ValueT, Config >::lookup(), SSA, llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
shouldSpeculateInstrs()
static bool shouldSpeculateInstrs (BasicBlock::iterator Begin, BasicBlock::iterator End, Loop * L) static
Determine whether the instructions in this range may be safely and cheaply speculated.
This is not an important enough situation to develop complex heuristics. We handle a single arithmetic instruction along with any type conversions.
Definition at line 689 of file LoopRotationUtils.cpp.
References llvm::cast(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), I, llvm::isa(), llvm::isSafeToSpeculativelyExecute(), LLVM_FALLTHROUGH, and llvm::Value::users().
STATISTIC() [1/2]
STATISTIC (NumNotRotatedDueToHeaderSize , "Number of loops not rotated due to the header size")
STATISTIC() [2/2]
STATISTIC (NumRotated , "Number of loops rotated")
Variable Documentation
MultiRotate
cl::opt< bool > MultiRotate("loop-rotate-multi", cl::init(false), cl::Hidden, cl::desc("Allow loop rotation multiple times in order to reach " "a better latch exit")) ("loop-rotate-multi" , cl::init(false) , cl::Hidden , cl::desc("Allow loop rotation multiple times in order to reach " "a better latch exit")) static