LLVM: lib/Transforms/Utils/LoopUtils.cpp File Reference
LoopUtils.cpp File Reference
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/PriorityWorklist.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopAccessAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/MustExecute.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
Classes
struct RewritePhi
struct PointerBounds
IR Values for the lower and upper bounds of a pointer evolution.
Macros
#define DEBUG_TYPE "loop-utils"
Functions
static MDNode * createStringMetadata (Loop *TheLoop, StringRef Name, unsigned V)
Create MDNode for input string.
static Optional< bool > getOptionalBoolLoopAttribute (const Loop *TheLoop, StringRef Name)
static Loop * getOutermostLoop (Loop *L)
static BranchInst * getExpectedExitLoopLatchBranch (Loop *L)
Checks if L has single exit through latch block except possibly "deoptimizing" exits.
static bool isValidRewrite (ScalarEvolution *SE, Value *FromVal, Value *ToVal)
static bool hasHardUserWithinLoop (const Loop *L, const Instruction *I)
static bool canLoopBeDeleted (Loop *L, SmallVector< RewritePhi, 8 > &RewritePhiSet)
static PointerBounds expandBounds (const RuntimeCheckingPtrGroup *CG, Loop *TheLoop, Instruction *Loc, SCEVExpander &Exp, ScalarEvolution *SE)
Expand code for the lower and upper bound of the pointer group CG in TheLoop.
static SmallVector< std::pair< PointerBounds, PointerBounds >, 4 > expandBounds (const SmallVectorImpl< RuntimePointerCheck > &PointerChecks, Loop *L, Instruction *Loc, ScalarEvolution *SE, SCEVExpander &Exp)
Turns a collection of checks into a collection of expanded upper and lower bounds for both pointers in the check.
Variables
static cl::opt< bool > ForceReductionIntrinsic ("force-reduction-intrinsics", cl::Hidden, cl::desc("Force creating reduction intrinsics for testing."), cl::init(false))
static const char * LLVMLoopDisableNonforced = "llvm.loop.disable_nonforced"
static const char * LLVMLoopDisableLICM = "llvm.licm.disable"
static const char * LLVMLoopMustProgress = "llvm.loop.mustprogress"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-utils"
Definition at line 62 of file LoopUtils.cpp.
Function Documentation
canLoopBeDeleted()
static bool canLoopBeDeleted (Loop * L, SmallVector< RewritePhi, 8 > & RewritePhiSet) static
Definition at line 1244 of file LoopUtils.cpp.
References llvm::any_of(), llvm::BasicBlock::begin(), llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlocks(), llvm::Loop::hasLoopInvariantOperands(), I, P, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::rewriteLoopExitValues().
createStringMetadata()
static MDNode * createStringMetadata (Loop * TheLoop, StringRef Name, unsigned V) static
Create MDNode for input string.
Definition at line 217 of file LoopUtils.cpp.
References llvm::ConstantAsMetadata::get(), llvm::ConstantInt::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), and Name.
Referenced by llvm::addStringMetadataToLoop().
expandBounds() [1/2]
static PointerBounds expandBounds (const RuntimeCheckingPtrGroup * CG, Loop * TheLoop, Instruction * Loc, SCEVExpander & Exp, ScalarEvolution * SE) static
Expand code for the lower and upper bound of the pointer group CG in TheLoop.
Returns
the values for the bounds.
Definition at line 1588 of file LoopUtils.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), llvm::dyn_cast(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getOne(), llvm::Type::getPointerAddressSpace(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), llvm::RuntimeCheckingPtrGroup::High, llvm::ScalarEvolution::isLoopInvariant(), LLVM_DEBUG, llvm::RuntimeCheckingPtrGroup::Low, llvm::RuntimeCheckingPtrGroup::Members, llvm::RuntimePointerChecking::Pointers, and llvm::RuntimeCheckingPtrGroup::RtCheck.
Referenced by llvm::addRuntimeChecks(), and expandBounds().
expandBounds() [2/2]
static SmallVector< std::pair< PointerBounds, PointerBounds >, 4 > expandBounds (const SmallVectorImpl< RuntimePointerCheck > & PointerChecks, Loop * L, Instruction * Loc, ScalarEvolution * SE, SCEVExpander & Exp) static
Turns a collection of checks into a collection of expanded upper and lower bounds for both pointers in the check.
Definition at line 1628 of file LoopUtils.cpp.
References expandBounds(), and llvm::transform().
getExpectedExitLoopLatchBranch()
static BranchInst * getExpectedExitLoopLatchBranch (Loop * L) static
Checks if L has single exit through latch block except possibly "deoptimizing" exits.
Returns branch instruction terminating the loop latch if above check is successful, nullptr otherwise.
Definition at line 812 of file LoopUtils.cpp.
References llvm::any_of(), assert(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BranchInst::getNumSuccessors(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminatingDeoptimizeCall(), llvm::BasicBlock::getTerminator(), llvm::LoopBase< BlockT, LoopT >::getUniqueNonLatchExitBlocks(), and llvm::LoopBase< BlockT, LoopT >::isLoopExiting().
Referenced by llvm::getLoopEstimatedTripCount(), and llvm::setLoopEstimatedTripCount().
getOptionalBoolLoopAttribute()
static Optional< bool > getOptionalBoolLoopAttribute (const Loop * TheLoop, StringRef Name) static
Definition at line 283 of file LoopUtils.cpp.
References llvm::mdconst::extract_or_null(), llvm::findOptionMDForLoop(), llvm::MDOperand::get(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm_unreachable, Name, and llvm::None.
Referenced by llvm::getBooleanLoopAttribute(), and llvm::hasVectorizeTransformation().
getOutermostLoop()
static Loop * getOutermostLoop (Loop * L) static
Definition at line 764 of file LoopUtils.cpp.
References llvm::LoopBase< BlockT, LoopT >::getParentLoop().
Referenced by llvm::breakLoopBackedge().
hasHardUserWithinLoop()
static bool hasHardUserWithinLoop (const Loop * L, const Instruction * I) static
Definition at line 1200 of file LoopUtils.cpp.
References llvm::cast(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallVectorBase< Size_T >::empty(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Instruction::mayHaveSideEffects(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::users().
Referenced by llvm::rewriteLoopExitValues().
isValidRewrite()
static bool isValidRewrite (ScalarEvolution * SE, Value * FromVal, Value * ToVal) static
Definition at line 1152 of file LoopUtils.cpp.
References llvm::dbgs(), llvm::dyn_cast(), GEP, llvm::ScalarEvolution::getPointerBase(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), llvm::Type::isPointerTy(), and LLVM_DEBUG.
Referenced by llvm::rewriteLoopExitValues().
Variable Documentation
ForceReductionIntrinsic
cl::opt< bool > ForceReductionIntrinsic("force-reduction-intrinsics", cl::Hidden, cl::desc("Force creating reduction intrinsics for testing."), cl::init(false)) ("force-reduction-intrinsics" , cl::Hidden , cl::desc("Force creating reduction intrinsics for testing.") , cl::init(false)) static
Referenced by llvm::createSimpleTargetReduction().
LLVMLoopDisableLICM
const char* LLVMLoopDisableLICM = "llvm.licm.disable" static
Definition at line 65 of file LoopUtils.cpp.
Referenced by llvm::hasDisableLICMTransformsHint().
LLVMLoopDisableNonforced
const char* LLVMLoopDisableNonforced = "llvm.loop.disable_nonforced" static
Definition at line 64 of file LoopUtils.cpp.
Referenced by llvm::hasDisableAllTransformsHint().
LLVMLoopMustProgress
const char* LLVMLoopMustProgress = "llvm.loop.mustprogress" static
Definition at line 66 of file LoopUtils.cpp.
Referenced by llvm::hasMustProgress().