LLVM: lib/Analysis/LoopPass.cpp File Reference
LoopPass.cpp File Reference
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/OptBisect.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PassTimingInfo.h"
#include "llvm/IR/PrintPasses.h"
#include "llvm/IR/StructuralHash.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "loop-pass-manager"
Functions
static void addLoopIntoQueue (Loop *L, std::deque< Loop * > &LQ)
static std::string getDescription (const Loop &L)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-pass-manager"
Definition at line 31 of file LoopPass.cpp.
Function Documentation
addLoopIntoQueue()
static void addLoopIntoQueue (Loop * L, std::deque< Loop * > & LQ) static
Definition at line 98 of file LoopPass.cpp.
References addLoopIntoQueue(), I, and llvm::reverse().
Referenced by addLoopIntoQueue(), and llvm::LPPassManager::runOnFunction().
getDescription()
static std::string getDescription (const Loop & L) static
Definition at line 369 of file LoopPass.cpp.