LLVM: lib/Transforms/Scalar/LoopFlatten.cpp File Reference
LoopFlatten.cpp File Reference
#include "llvm/Transforms/Scalar/LoopFlatten.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
#include "llvm/Transforms/Utils/SimplifyIndVar.h"
Classes
struct FlattenInfo
Macros
#define DEBUG_TYPE "loop-flatten"
Functions
static bool findLoopComponents (Loop *L, SmallPtrSetImpl< Instruction * > &IterationInstructions, PHINode *&InductionPHI, Value *&Limit, BinaryOperator *&Increment, BranchInst *&BackBranch, ScalarEvolution *SE)
static bool checkPHIs (struct FlattenInfo &FI, const TargetTransformInfo *TTI)
static bool checkOuterLoopInsts (struct FlattenInfo &FI, SmallPtrSetImpl< Instruction * > &IterationInstructions, const TargetTransformInfo *TTI)
static bool checkIVUsers (struct FlattenInfo &FI)
static OverflowResult checkOverflow (struct FlattenInfo &FI, DominatorTree *DT, AssumptionCache *AC)
static bool CanFlattenLoopPair (struct FlattenInfo &FI, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, const TargetTransformInfo *TTI)
static bool DoFlattenLoopPair (struct FlattenInfo &FI, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, const TargetTransformInfo *TTI)
static bool CanWidenIV (struct FlattenInfo &FI, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, const TargetTransformInfo *TTI)
static bool FlattenLoopPair (struct FlattenInfo &FI, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, const TargetTransformInfo *TTI)
bool Flatten (DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, TargetTransformInfo *TTI)
INITIALIZE_PASS_BEGIN (LoopFlattenLegacyPass, "loop-flatten", "Flattens loops", false, false) INITIALIZE_PASS_END(LoopFlattenLegacyPass
Variables
static cl::opt< unsigned > RepeatedInstructionThreshold ("loop-flatten-cost-threshold", cl::Hidden, cl::init(2), cl::desc("Limit on the cost of instructions that can be repeated due to " "loop flattening"))
static cl::opt< bool > AssumeNoOverflow ("loop-flatten-assume-no-overflow", cl::Hidden, cl::init(false), cl::desc("Assume that the product of the two iteration " "limits will never overflow"))
static cl::opt< bool > WidenIV ("loop-flatten-widen-iv", cl::Hidden, cl::init(true), cl::desc("Widen the loop induction variables, if possible, so " "overflow checks won't reject flattening"))
loop flatten
loop Flattens loops
loop Flattens false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-flatten"
Definition at line 52 of file LoopFlatten.cpp.
Referenced by DoFlattenLoopPair().
Function Documentation
CanFlattenLoopPair()
static bool CanFlattenLoopPair (struct FlattenInfo & FI, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, const TargetTransformInfo * TTI) static
Definition at line 467 of file LoopFlatten.cpp.
References checkIVUsers(), checkOuterLoopInsts(), checkPHIs(), llvm::dbgs(), findLoopComponents(), llvm::Value::getType(), FlattenInfo::InnerBranch, FlattenInfo::InnerIncrement, FlattenInfo::InnerInductionPHI, FlattenInfo::InnerLimit, FlattenInfo::InnerLoop, llvm::Loop::isLoopInvariant(), LLVM_DEBUG, FlattenInfo::OuterBranch, FlattenInfo::OuterIncrement, FlattenInfo::OuterInductionPHI, FlattenInfo::OuterLimit, and FlattenInfo::OuterLoop.
Referenced by CanWidenIV(), and FlattenLoopPair().
CanWidenIV()
static bool CanWidenIV (struct FlattenInfo & FI, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, const TargetTransformInfo * TTI) static
Definition at line 574 of file LoopFlatten.cpp.
References assert(), CanFlattenLoopPair(), llvm::createWideIV(), llvm::dbgs(), DL, llvm::Value::dump(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), FlattenInfo::InnerInductionPHI, FlattenInfo::InnerLoop, LLVM_DEBUG, FlattenInfo::OuterInductionPHI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::RecursivelyDeleteDeadPHINode(), Rewriter, llvm::SmallVectorBase< Size_T >::size(), and FlattenInfo::Widened.
Referenced by FlattenLoopPair().
checkIVUsers()
static bool checkIVUsers (struct FlattenInfo & FI) static
Definition at line 332 of file LoopFlatten.cpp.
References llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::dyn_cast(), FlattenInfo::InnerIncrement, FlattenInfo::InnerInductionPHI, FlattenInfo::InnerLimit, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), FlattenInfo::LinearIVUses, LLVM_DEBUG, llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), FlattenInfo::OuterIncrement, FlattenInfo::OuterInductionPHI, llvm::Value::users(), and FlattenInfo::Widened.
Referenced by CanFlattenLoopPair().
checkOuterLoopInsts()
static bool checkOuterLoopInsts (struct FlattenInfo & FI, SmallPtrSetImpl< Instruction * > & IterationInstructions, const TargetTransformInfo * TTI) static
Definition at line 275 of file LoopFlatten.cpp.
References B, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BranchInst::getSuccessor(), llvm::TargetTransformInfo::getUserCost(), I, FlattenInfo::InnerLimit, FlattenInfo::InnerLoop, llvm::isa(), llvm::isSafeToSpeculativelyExecute(), llvm::BranchInst::isUnconditional(), LLVM_DEBUG, llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), FlattenInfo::OuterInductionPHI, FlattenInfo::OuterLoop, RepeatedInstructionThreshold, and llvm::TargetTransformInfo::TCK_SizeAndLatency.
Referenced by CanFlattenLoopPair().
checkOverflow()
static OverflowResult checkOverflow (struct FlattenInfo & FI, DominatorTree * DT, AssumptionCache * AC) static
Definition at line 428 of file LoopFlatten.cpp.
References AssumeNoOverflow, llvm::computeOverflowForUnsignedMul(), llvm::dbgs(), DL, llvm::dyn_cast(), F, GEP, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), FlattenInfo::InnerLimit, FlattenInfo::LinearIVUses, LLVM_DEBUG, FlattenInfo::OuterLimit, FlattenInfo::OuterLoop, and llvm::Value::users().
Referenced by FlattenLoopPair().
checkPHIs()
static bool checkPHIs (struct FlattenInfo & FI, const TargetTransformInfo * TTI) static
Definition at line 193 of file LoopFlatten.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::Value::dump(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Instruction::getParent(), llvm::PHINode::hasConstantValue(), FlattenInfo::InnerInductionPHI, FlattenInfo::InnerLoop, FlattenInfo::InnerPHIsToTransform, llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, FlattenInfo::OuterInductionPHI, FlattenInfo::OuterLoop, and llvm::BasicBlock::phis().
Referenced by CanFlattenLoopPair().
DoFlattenLoopPair()
static bool DoFlattenLoopPair (struct FlattenInfo & FI, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, const TargetTransformInfo * TTI) static
Definition at line 511 of file LoopFlatten.cpp.
References Builder, llvm::cast(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG_TYPE, llvm::DominatorTreeBase< NodeT, IsPostDom >::deleteEdge(), llvm::Value::dump(), llvm::OptimizationRemarkEmitter::emit(), llvm::LoopInfo::erase(), llvm::Instruction::eraseFromParent(), F, llvm::ScalarEvolution::forgetLoop(), llvm::BranchInst::getCondition(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Loop::getStartLoc(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), FlattenInfo::InnerInductionPHI, FlattenInfo::InnerLimit, FlattenInfo::InnerLoop, FlattenInfo::InnerPHIsToTransform, FlattenInfo::LinearIVUses, LLVM_DEBUG, FlattenInfo::OuterBranch, FlattenInfo::OuterInductionPHI, FlattenInfo::OuterLimit, FlattenInfo::OuterLoop, llvm::Remark, llvm::PHINode::removeIncomingValue(), llvm::Value::replaceAllUsesWith(), and FlattenInfo::Widened.
Referenced by FlattenLoopPair().
findLoopComponents()
static bool findLoopComponents (Loop * L, SmallPtrSetImpl< Instruction * > & IterationInstructions, PHINode *& InductionPHI, Value *& Limit, BinaryOperator *& Increment, BranchInst *& BackBranch, ScalarEvolution * SE) static
Definition at line 96 of file LoopFlatten.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), llvm::Value::dump(), llvm::dyn_cast(), llvm::BranchInst::getCondition(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Loop::getName(), llvm::PHINode::getNumIncomingValues(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_ULT, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::BranchInst::isConditional(), llvm::InductionDescriptor::isInductionPHI(), llvm::Loop::isLoopSimplifyForm(), LLVM_DEBUG, llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), and llvm::BasicBlock::phis().
Referenced by CanFlattenLoopPair().
Flatten()
bool Flatten (DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, TargetTransformInfo * TTI)
Definition at line 659 of file LoopFlatten.cpp.
References Changed, FlattenLoopPair(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), FlattenInfo::InnerLoop, and FlattenInfo::OuterLoop.
Referenced by llvm::LoopFlattenPass::run().
FlattenLoopPair()
static bool FlattenLoopPair (struct FlattenInfo & FI, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, const TargetTransformInfo * TTI) static
Definition at line 624 of file LoopFlatten.cpp.
References CanFlattenLoopPair(), CanWidenIV(), checkOverflow(), llvm::dbgs(), DoFlattenLoopPair(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Value::getName(), llvm::BasicBlock::getParent(), FlattenInfo::InnerLoop, LLVM_DEBUG, and FlattenInfo::OuterLoop.
Referenced by Flatten().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopFlattenLegacyPass , "loop-flatten" , "Flattens loops" , false , false)
Variable Documentation
AssumeNoOverflow
cl::opt< bool > AssumeNoOverflow("loop-flatten-assume-no-overflow", cl::Hidden, cl::init(false), cl::desc("Assume that the product of the two iteration " "limits will never overflow")) ("loop-flatten-assume-no-overflow" , cl::Hidden , cl::init(false) , cl::desc("Assume that the product of the two iteration " "limits will never overflow")) static
Referenced by checkOverflow().
false
loop Flattens false
Definition at line 715 of file LoopFlatten.cpp.
flatten
loop flatten
Definition at line 714 of file LoopFlatten.cpp.
loops
loop Flattens loops
Definition at line 714 of file LoopFlatten.cpp.
RepeatedInstructionThreshold
cl::opt< unsigned > RepeatedInstructionThreshold("loop-flatten-cost-threshold", cl::Hidden, cl::init(2), cl::desc("Limit on the cost of instructions that can be repeated due to " "loop flattening")) ("loop-flatten-cost-threshold" , cl::Hidden , cl::init(2) , cl::desc("Limit on the cost of instructions that can be repeated due to " "loop flattening")) static
Referenced by checkOuterLoopInsts().
WidenIV
cl::opt< bool > WidenIV("loop-flatten-widen-iv", cl::Hidden, cl::init(true), cl::desc("Widen the loop induction variables, if possible, so " "overflow checks won't reject flattening")) ("loop-flatten-widen-iv" , cl::Hidden , cl::init(true) , cl::desc("Widen the loop induction variables, if possible, so " "overflow checks won't reject flattening")) static