LLVM: lib/Analysis/LoopInfo.cpp File Reference
LoopInfo.cpp File Reference
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/Analysis/LoopInfoImpl.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PrintPasses.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Typedefs
using Direction = Loop::LoopBounds::Direction
Functions
static ICmpInst * getLatchCmpInst (const Loop &L)
Get the latch condition instruction.
static Value * findFinalIVValue (const Loop &L, const PHINode &IndVar, const Instruction &StepInst)
Return the final value of the loop induction variable if found.
static bool isBlockInLCSSAForm (const Loop &L, const BasicBlock &BB, const DominatorTree &DT)
INITIALIZE_PASS_BEGIN (LoopInfoWrapperPass, "loops", "Natural Loop Information", true, true) INITIALIZE_PASS_END(LoopInfoWrapperPass
Variables
static cl::opt< bool, true > VerifyLoopInfoX ("verify-loop-info", cl::location(VerifyLoopInfo), cl::Hidden, cl::desc("Verify loop info (time consuming)"))
loops
Natural Loop Information
Natural Loop true
Typedef Documentation
Direction
using Direction = Loop::LoopBounds::Direction
Definition at line 229 of file LoopInfo.cpp.
Function Documentation
findFinalIVValue()
static Value * findFinalIVValue (const Loop & L, const PHINode & IndVar, const Instruction & StepInst) static
Return the final value of the loop induction variable if found.
Definition at line 183 of file LoopInfo.cpp.
References getLatchCmpInst(), and llvm::User::getOperand().
Referenced by llvm::Loop::LoopBounds::getBounds().
getLatchCmpInst()
static ICmpInst * getLatchCmpInst (const Loop & L) static
Get the latch condition instruction.
Definition at line 173 of file LoopInfo.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), and llvm::LoopBase< BlockT, LoopT >::getLoopLatch().
Referenced by findFinalIVValue(), and llvm::Loop::getInductionVariable().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopInfoWrapperPass , "loops" , "Natural Loop Information" , true , true)
isBlockInLCSSAForm()
static bool isBlockInLCSSAForm (const Loop & L, const BasicBlock & BB, const DominatorTree & DT) static
Definition at line 423 of file LoopInfo.cpp.
References llvm::cast(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::Instruction::getParent(), I, llvm::DominatorTree::isReachableFromEntry(), and P.
Referenced by llvm::Loop::isLCSSAForm(), and llvm::Loop::isRecursivelyLCSSAForm().
Variable Documentation
Information
Natural Loop Information
Definition at line 1084 of file LoopInfo.cpp.
loops
loops
Definition at line 1084 of file LoopInfo.cpp.
true
Natural Loop true
Definition at line 1085 of file LoopInfo.cpp.
VerifyLoopInfoX
cl::opt< bool, true > VerifyLoopInfoX("verify-loop-info", cl::location(VerifyLoopInfo), cl::Hidden, cl::desc("Verify loop info (time consuming)")) ("verify-loop-info" , cl::location(VerifyLoopInfo) , cl::Hidden , cl::desc("Verify loop info (time consuming)")) static