LLVM: lib/Transforms/Utils/LoopSimplify.cpp File Reference
LoopSimplify.cpp File Reference
#include "llvm/Transforms/Utils/LoopSimplify.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/DependenceAnalysis.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "loop-simplify"
Functions
STATISTIC (NumNested, "Number of nested loops split out")
static void placeSplitBlockCarefully (BasicBlock *NewBB, SmallVectorImpl< BasicBlock * > &SplitPreds, Loop *L)
static void addBlockAndPredsToSet (BasicBlock *InputBB, BasicBlock *StopBlock, SmallPtrSetImpl< BasicBlock * > &Blocks)
Add the specified block, and all of its predecessors, to the specified set, if it's not already in there.
static PHINode * findPHIToPartitionLoops (Loop *L, DominatorTree *DT, AssumptionCache *AC)
The first part of loop-nestification is to find a PHI node that tells us how to partition the loops.
static Loop * separateNestedLoop (Loop *L, BasicBlock *Preheader, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, bool PreserveLCSSA, AssumptionCache *AC, MemorySSAUpdater *MSSAU)
If this loop has multiple backedges, try to pull one of them out into a nested loop.
static BasicBlock * insertUniqueBackedgeBlock (Loop *L, BasicBlock *Preheader, DominatorTree *DT, LoopInfo *LI, MemorySSAUpdater *MSSAU)
This method is called when the specified loop has more than one backedge in it.
static bool simplifyOneLoop (Loop *L, SmallVectorImpl< Loop * > &Worklist, DominatorTree *DT, LoopInfo *LI, ScalarEvolution *SE, AssumptionCache *AC, MemorySSAUpdater *MSSAU, bool PreserveLCSSA)
Simplify one loop and queue further loops for simplification.
INITIALIZE_PASS_BEGIN (LoopSimplify, "loop-simplify", "Canonicalize natural loops", false, false) INITIALIZE_PASS_END(LoopSimplify
Variables
loop simplify
loop Canonicalize natural loops
loop Canonicalize natural false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-simplify"
Definition at line 79 of file LoopSimplify.cpp.
Function Documentation
addBlockAndPredsToSet()
static void addBlockAndPredsToSet (BasicBlock * InputBB, BasicBlock * StopBlock, SmallPtrSetImpl< BasicBlock * > & Blocks) static
Add the specified block, and all of its predecessors, to the specified set, if it's not already in there.
Stop predecessor traversal when we reach StopBlock.
Definition at line 165 of file LoopSimplify.cpp.
References llvm::append_range(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by separateNestedLoop().
findPHIToPartitionLoops()
static PHINode * findPHIToPartitionLoops (Loop * L, DominatorTree * DT, AssumptionCache * AC) static
The first part of loop-nestification is to find a PHI node that tells us how to partition the loops.
Definition at line 180 of file LoopSimplify.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), llvm::LoopBase< BlockT, LoopT >::contains(), DL, llvm::Instruction::eraseFromParent(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::BasicBlock::getModule(), llvm::PHINode::getNumIncomingValues(), I, llvm::isa(), llvm::Value::replaceAllUsesWith(), and llvm::SimplifyInstruction().
Referenced by separateNestedLoop().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoopSimplify , "loop-simplify" , "Canonicalize natural loops" , false , false)
insertUniqueBackedgeBlock()
static BasicBlock * insertUniqueBackedgeBlock (Loop * L, BasicBlock * Preheader, DominatorTree * DT, LoopInfo * LI, MemorySSAUpdater * MSSAU) static
This method is called when the specified loop has more than one backedge in it.
If this occurs, revector all of these backedges to target a new basic block and have that block branch to the loop header. This ensures that loops have exactly one backedge.
Definition at line 366 of file LoopSimplify.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::PHINode::addIncoming(), assert(), llvm::BasicBlock::begin(), llvm::cast(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::PHINode::Create(), llvm::dbgs(), E, llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), F, llvm::BasicBlock::getContext(), llvm::Instruction::getDebugLoc(), llvm::BasicBlock::getFirstNonPHI(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::BasicBlock::getInstList(), llvm::LLVMContext::getMDKindID(), llvm::Instruction::getMetadata(), llvm::Value::getName(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::isa(), llvm::BasicBlock::isEHPad(), LLVM_DEBUG, P, llvm::pred_begin(), llvm::pred_end(), llvm::PHINode::removeIncomingValue(), llvm::Value::replaceAllUsesWith(), llvm::Instruction::replaceSuccessorWith(), llvm::Instruction::setDebugLoc(), llvm::PHINode::setIncomingBlock(), llvm::PHINode::setIncomingValue(), llvm::Instruction::setMetadata(), llvm::DominatorTreeBase< NodeT, IsPostDom >::splitBlock(), and llvm::MemorySSAUpdater::updatePhisWhenInsertingUniqueBackedgeBlock().
Referenced by simplifyOneLoop().
placeSplitBlockCarefully()
static void placeSplitBlockCarefully (BasicBlock * NewBB, SmallVectorImpl< BasicBlock * > & SplitPreds, Loop * L) static
Definition at line 86 of file LoopSimplify.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::Function::end(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BasicBlock::getParent(), llvm::BasicBlock::moveAfter(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::InsertPreheaderForLoop(), and separateNestedLoop().
separateNestedLoop()
static Loop * separateNestedLoop (Loop * L, BasicBlock * Preheader, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, bool PreserveLCSSA, AssumptionCache * AC, MemorySSAUpdater * MSSAU) static
If this loop has multiple backedges, try to pull one of them out into a nested loop.
This is important for code that looks like this:
Loop: ... br cond, Loop, Next ... br cond2, Loop, Out
To identify this common case, we look at the PHI nodes in the header of the loop. PHI nodes with unchanging values on one backedge correspond to values that change in the "outer" loop, but not in the "inner" loop.
If we are able to separate out a loop, return the new outer loop that was created.
Definition at line 222 of file LoopSimplify.cpp.
References addBlockAndPredsToSet(), llvm::LoopBase< BlockT, LoopT >::addBlockEntry(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), assert(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor(), llvm::LoopInfoBase< BlockT, LoopT >::changeTopLevelLoop(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), E, findPHIToPartitionLoops(), llvm::ScalarEvolution::forgetLoop(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), llvm::BasicBlock::getTerminator(), I, llvm::BasicBlock::isEHPad(), llvm::Instruction::isIndirectTerminator(), llvm::Loop::isRecursivelyLCSSAForm(), LLVM_DEBUG, llvm::LoopBase< BlockT, LoopT >::moveToHeader(), P, placeSplitBlockCarefully(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), llvm::LoopBase< BlockT, LoopT >::replaceChildLoopWith(), size(), and llvm::SplitBlockPredecessors().
Referenced by simplifyOneLoop().
simplifyOneLoop()
static bool simplifyOneLoop (Loop * L, SmallVectorImpl< Loop * > & Worklist, DominatorTree * DT, LoopInfo * LI, ScalarEvolution * SE, AssumptionCache * AC, MemorySSAUpdater * MSSAU, bool PreserveLCSSA) static
Simplify one loop and queue further loops for simplification.
Definition at line 489 of file LoopSimplify.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), Changed, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::changeToUnreachable(), Cond, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), DL, llvm::dyn_cast(), E, llvm::BasicBlock::eraseFromParent(), llvm::Instruction::eraseFromParent(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::FoldBranchToCommonDest(), llvm::ScalarEvolution::forgetLoopDispositions(), llvm::ScalarEvolution::forgetTopmostLoop(), llvm::ScalarEvolution::forgetValue(), llvm::formDedicatedExitBlocks(), llvm::ConstantInt::get(), llvm::BranchInst::getCondition(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::MemorySSAUpdater::getMemorySSA(), llvm::BasicBlock::getModule(), llvm::Value::getName(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::Instruction::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::InsertPreheaderForLoop(), insertUniqueBackedgeBlock(), llvm::BasicBlock::instructionsWithoutDebug(), llvm::BranchInst::isConditional(), LLVM_DEBUG, llvm::Loop::makeLoopInvariant(), P, llvm::pred_begin(), llvm::pred_empty(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), llvm::MemorySSAUpdater::removeBlocks(), llvm::BasicBlock::removePredecessor(), llvm::Value::replaceAllUsesWith(), llvm::LoopInfo::replacementPreservesLCSSAForm(), separateNestedLoop(), llvm::SimplifyInstruction(), llvm::SmallVectorBase< Size_T >::size(), llvm::successors(), llvm::VerifyMemorySSA, and llvm::MemorySSA::verifyMemorySSA().
Referenced by llvm::simplifyLoop().
STATISTIC()
STATISTIC (NumNested , "Number of nested loops split out")
Variable Documentation
false
loop Canonicalize natural false
Definition at line 805 of file LoopSimplify.cpp.
loops
loop Canonicalize natural loops
Definition at line 805 of file LoopSimplify.cpp.
simplify
loop simplify
Definition at line 804 of file LoopSimplify.cpp.