LLVM: lib/LTO/LTOBackend.cpp File Reference
LTOBackend.cpp File Reference
#include "llvm/LTO/LTOBackend.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/LTO/LTO.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Object/ModuleSymbolTable.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/PassPlugin.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar/LoopPassManager.h"
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
#include "llvm/Transforms/Utils/SplitModule.h"
#include "llvm/Support/Extension.def"
Macros
#define DEBUG_TYPE "lto-backend"
#define HANDLE_EXTENSION(Ext)
#define HANDLE_EXTENSION(Ext)
Enumerations
enum class LTOBitcodeEmbedding { DoNotEmbed = 0 , EmbedOptimized = 1 , EmbedPostMergePreOptimized = 2 }
Functions
static LLVM_ATTRIBUTE_NORETURN void reportOpenError (StringRef Path, Twine Msg)
static void RegisterPassPlugins (ArrayRef< std::string > PassPlugins, PassBuilder &PB)
static std::unique_ptr< TargetMachine > createTargetMachine (const Config &Conf, const Target *TheTarget, Module &M)
static void runNewPMPasses (const Config &Conf, Module &Mod, TargetMachine *TM, unsigned OptLevel, bool IsThinLTO, ModuleSummaryIndex *ExportSummary, const ModuleSummaryIndex *ImportSummary)
static void runNewPMCustomPasses (const Config &Conf, Module &Mod, TargetMachine *TM, std::string PipelineDesc, std::string AAPipelineDesc, bool DisableVerify)
static void runOldPMPasses (const Config &Conf, Module &Mod, TargetMachine *TM, bool IsThinLTO, ModuleSummaryIndex *ExportSummary, const ModuleSummaryIndex *ImportSummary)
static void codegen (const Config &Conf, TargetMachine *TM, AddStreamFn AddStream, unsigned Task, Module &Mod, const ModuleSummaryIndex &CombinedIndex)
static void splitCodeGen (const Config &C, TargetMachine *TM, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, std::unique_ptr< Module > Mod, const ModuleSummaryIndex &CombinedIndex)
static Expected< const Target * > initAndLookupTarget (const Config &C, Module &Mod)
static void dropDeadSymbols (Module &Mod, const GVSummaryMapTy &DefinedGlobals, const ModuleSummaryIndex &Index)
Variables
static cl::opt< LTOBitcodeEmbedding > EmbedBitcode ("lto-embed-bitcode", cl::init(LTOBitcodeEmbedding::DoNotEmbed), cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")), cl::desc("Embed LLVM bitcode in object files produced by LTO"))
static cl::opt< bool > ThinLTOAssumeMerged ("thinlto-assume-merged", cl::init(false), cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lto-backend"
Definition at line 53 of file LTOBackend.cpp.
HANDLE_EXTENSION [1/2]
#define HANDLE_EXTENSION (Ext)
Value:
  llvm::PassPluginLibraryInfo get##Ext##PluginInfo();
Definition at line 156 of file LTOBackend.cpp.
HANDLE_EXTENSION [2/2]
#define HANDLE_EXTENSION (Ext)
Value:
  get##Ext##PluginInfo().RegisterPassBuilderCallbacks(PB);
Definition at line 156 of file LTOBackend.cpp.
Enumeration Type Documentation
LTOBitcodeEmbedding
enum class LTOBitcodeEmbedding strong
Enumerator
DoNotEmbed
EmbedOptimized
EmbedPostMergePreOptimized
Definition at line 55 of file LTOBackend.cpp.
Function Documentation
codegen()
static void codegen (const Config & Conf, TargetMachine * TM, AddStreamFn AddStream, unsigned Task, Module & Mod, const ModuleSummaryIndex & CombinedIndex) static
Definition at line 408 of file LTOBackend.cpp.
References llvm::legacy::PassManager::add(), llvm::sys::path::append(), llvm::lto::Config::CGFileType, codegen(), llvm::sys::fs::create_directories(), llvm::createImmutableModuleSummaryIndexWrapperPass(), llvm::lto::Config::DwoDir, EmbedBitcode, llvm::EmbedBitcodeInModule(), EmbedOptimized, llvm::SmallVectorBase< Size_T >::empty(), llvm::Mod, llvm::sys::fs::OF_None, llvm::lto::Config::PreCodeGenModuleHook, llvm::lto::Config::PreCodeGenPassesHook, llvm::report_fatal_error(), llvm::legacy::PassManager::run(), llvm::lto::Config::SplitDwarfFile, and llvm::lto::Config::SplitDwarfOutput.
Referenced by llvm::lto::backend(), codegen(), splitCodeGen(), and llvm::lto::thinBackend().
createTargetMachine()
static std::unique_ptr< TargetMachine > createTargetMachine (const Config & Conf, const Target * TheTarget, Module & M) static
Definition at line 180 of file LTOBackend.cpp.
References A, llvm::SubtargetFeatures::AddFeature(), assert(), llvm::lto::Config::CGOptLevel, llvm::lto::Config::CodeModel, llvm::lto::Config::CPU, llvm::Target::createTargetMachine(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::SubtargetFeatures::getString(), llvm::lto::Config::MAttrs, llvm::PICLevel::NotPIC, llvm::lto::Config::Options, llvm::Reloc::PIC_, llvm::lto::Config::RelocModel, and llvm::Reloc::Static.
Referenced by llvm::lto::backend(), LLVMCreateTargetMachine(), splitCodeGen(), and llvm::lto::thinBackend().
dropDeadSymbols()
static void dropDeadSymbols (Module & Mod, const GVSummaryMapTy & DefinedGlobals, const ModuleSummaryIndex & Index) static
Definition at line 560 of file LTOBackend.cpp.
References llvm::convertToDeclaration(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::Mod.
Referenced by llvm::lto::thinBackend().
initAndLookupTarget()
static Expected< const Target * > initAndLookupTarget (const Config & C, Module & Mod) static
Definition at line 509 of file LTOBackend.cpp.
References C, llvm::inconvertibleErrorCode(), llvm::TargetRegistry::lookupTarget(), llvm::make_error(), llvm::Mod, and T.
Referenced by llvm::lto::backend(), and llvm::lto::thinBackend().
RegisterPassPlugins()
static void RegisterPassPlugins (ArrayRef< std::string > PassPlugins, PassBuilder & PB) static
Definition at line 160 of file LTOBackend.cpp.
References llvm::errs(), llvm::PassPlugin::Load(), and llvm::PassPlugin::registerPassBuilderCallbacks().
Referenced by runNewPMCustomPasses(), and runNewPMPasses().
reportOpenError()
static LLVM_ATTRIBUTE_NORETURN void reportOpenError (StringRef Path, Twine Msg) static
Definition at line 77 of file LTOBackend.cpp.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by llvm::lto::Config::addSaveTemps().
runNewPMCustomPasses()
static void runNewPMCustomPasses (const Config & Conf, Module & Mod, TargetMachine * TM, std::string PipelineDesc, std::string AAPipelineDesc, bool DisableVerify) static
Definition at line 291 of file LTOBackend.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PassBuilder::crossRegisterProxies(), llvm::lto::Config::DebugPassManager, llvm::lto::Config::Freestanding, llvm::Mod, llvm::PassBuilder::parseAAPipeline(), llvm::PassBuilder::parsePassPipeline(), llvm::lto::Config::PassPlugins, llvm::PassBuilder::registerCGSCCAnalyses(), llvm::PassBuilder::registerFunctionAnalyses(), llvm::PassBuilder::registerLoopAnalyses(), llvm::PassBuilder::registerModuleAnalyses(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), RegisterPassPlugins(), llvm::report_fatal_error(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), and llvm::toString().
Referenced by llvm::lto::opt().
runNewPMPasses()
static void runNewPMPasses (const Config & Conf, Module & Mod, TargetMachine * TM, unsigned OptLevel, bool IsThinLTO, ModuleSummaryIndex * ExportSummary, const ModuleSummaryIndex * ImportSummary) static
Definition at line 207 of file LTOBackend.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PassBuilder::buildLTODefaultPipeline(), llvm::PassBuilder::buildThinLTODefaultPipeline(), llvm::PassBuilder::crossRegisterProxies(), llvm::PGOOptions::CSIRInstr, llvm::lto::Config::CSIRProfile, llvm::PGOOptions::CSIRUse, llvm::lto::Config::DebugPassManager, llvm::lto::Config::DisableVerify, llvm::lto::Config::Freestanding, llvm::PGOOptions::IRUse, llvm_unreachable, llvm::Mod, llvm::PGOOptions::NoCSAction, llvm::PassBuilder::OptimizationLevel::O0, llvm::PassBuilder::OptimizationLevel::O1, llvm::PassBuilder::OptimizationLevel::O2, llvm::PassBuilder::OptimizationLevel::O3, llvm::PassBuilder::parseAAPipeline(), llvm::lto::Config::PassPlugins, llvm::lto::Config::ProfileRemapping, llvm::lto::Config::PTO, llvm::PassBuilder::registerCGSCCAnalyses(), llvm::PassBuilder::registerFunctionAnalyses(), llvm::PassBuilder::registerLoopAnalyses(), llvm::PassBuilder::registerModuleAnalyses(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), RegisterPassPlugins(), llvm::report_fatal_error(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::lto::Config::RunCSIRInstr, llvm::lto::Config::SampleProfile, llvm::PGOOptions::SampleUse, and SI.
Referenced by llvm::lto::opt().
runOldPMPasses()
static void runOldPMPasses (const Config & Conf, Module & Mod, TargetMachine * TM, bool IsThinLTO, ModuleSummaryIndex * ExportSummary, const ModuleSummaryIndex * ImportSummary) static
Definition at line 342 of file LTOBackend.cpp.
References llvm::legacy::PassManager::add(), llvm::createFunctionInliningPass(), llvm::createTargetTransformInfoWrapperPass(), llvm::lto::Config::CSIRProfile, llvm::TargetLibraryInfoImpl::disableAllFunctions(), llvm::lto::Config::DisableVerify, llvm::PassManagerBuilder::EnablePGOCSInstrGen, llvm::PassManagerBuilder::EnablePGOCSInstrUse, llvm::PassManagerBuilder::ExportSummary, llvm::lto::Config::Freestanding, llvm::PassManagerBuilder::ImportSummary, llvm::PassManagerBuilder::Inliner, llvm::PassManagerBuilder::LibraryInfo, llvm::PassManagerBuilder::LoopVectorize, llvm::Mod, llvm::lto::Config::OptLevel, llvm::PassManagerBuilder::OptLevel, llvm::PassManagerBuilder::PGOInstrUse, llvm::PassManagerBuilder::PGOSampleUse, llvm::PassManagerBuilder::populateLTOPassManager(), llvm::PassManagerBuilder::populateThinLTOPassManager(), llvm::legacy::PassManager::run(), llvm::lto::Config::RunCSIRInstr, llvm::lto::Config::SampleProfile, llvm::PassManagerBuilder::SLPVectorize, llvm::PassManagerBuilder::VerifyInput, and llvm::PassManagerBuilder::VerifyOutput.
Referenced by llvm::lto::opt().
splitCodeGen()
static void splitCodeGen (const Config & C, TargetMachine * TM, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, std::unique_ptr< Module > Mod, const ModuleSummaryIndex & CombinedIndex) static
Definition at line 457 of file LTOBackend.cpp.
References llvm::ThreadPool::async(), C, codegen(), createTargetMachine(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::Expected< T >::get(), llvm::heavyweight_hardware_concurrency(), llvm::Mod, llvm::parseBitcodeFile(), llvm::report_fatal_error(), llvm::SmallVectorBase< Size_T >::size(), llvm::SplitModule(), llvm::ThreadPool::wait(), and llvm::WriteBitcodeToFile().
Variable Documentation
EmbedBitcode
cl::opt< LTOBitcodeEmbedding > EmbedBitcode("lto-embed-bitcode", cl::init(LTOBitcodeEmbedding::DoNotEmbed), cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")), cl::desc("Embed LLVM bitcode in object files produced by LTO")) ("lto-embed-bitcode" , cl::init(LTOBitcodeEmbedding::DoNotEmbed) , cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")) , cl::desc("Embed LLVM bitcode in object files produced by LTO")) static
Referenced by codegen(), llvm::EmbedBitcodeInModule(), and llvm::lto::opt().
ThinLTOAssumeMerged
cl::opt< bool > ThinLTOAssumeMerged("thinlto-assume-merged", cl::init(false), cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes.")) ("thinlto-assume-merged" , cl::init(false) , cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes.")) static
Referenced by llvm::lto::findThinLTOModule(), llvm::lto::loadReferencedModules(), and llvm::lto::thinBackend().