LLVM: lib/Object/MachOUniversal.cpp File Reference
MachOUniversal.cpp File Reference
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
static Error malformedError (Twine Msg)
template<typename T >
static T getUniversalBinaryStruct (const char *Ptr)
Function Documentation
getUniversalBinaryStruct()
template<typename T > static T getUniversalBinaryStruct (const char * Ptr) static
Definition at line 33 of file MachOUniversal.cpp.
References llvm::sys::IsLittleEndianHost.
Referenced by llvm::object::MachOUniversalBinary::MachOUniversalBinary().
malformedError()
static Error malformedError (Twine Msg) static
Definition at line 26 of file MachOUniversal.cpp.
References llvm::make_error(), and llvm::Twine::str().