LLVM: lib/ExecutionEngine/JITLink/MachO_x86_64.cpp File Reference
MachO_x86_64.cpp File Reference
#include "llvm/ExecutionEngine/JITLink/MachO_x86_64.h"
#include "BasicGOTAndStubsBuilder.h"
#include "MachOLinkGraphBuilder.h"
Classes
class llvm::jitlink::MachOJITLinker_x86_64
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::jitlink
Macros
#define DEBUG_TYPE "jitlink"
Functions
static Error optimizeMachO_x86_64_GOTAndStubs (LinkGraph &G)
Expected< std::unique_ptr< LinkGraph > > llvm::jitlink::createLinkGraphFromMachOObject_x86_64 (MemoryBufferRef ObjectBuffer)
Create a LinkGraph from a MachO/x86-64 relocatable object.
void llvm::jitlink::link_MachO_x86_64 (std::unique_ptr< LinkGraph > G, std::unique_ptr< JITLinkContext > Ctx)
jit-link the given LinkGraph.
StringRef llvm::jitlink::getMachOX86RelocationKindName (Edge::Kind R)
Return the string name of the given MachO x86-64 edge kind.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "jitlink"
Definition at line 18 of file MachO_x86_64.cpp.
Function Documentation
optimizeMachO_x86_64_GOTAndStubs()
static Error optimizeMachO_x86_64_GOTAndStubs (LinkGraph & G) static
Definition at line 460 of file MachO_x86_64.cpp.
References assert(), B, llvm::jitlink::MachO_x86_64_Edges::Branch32, llvm::jitlink::MachO_x86_64_Edges::Branch32ToStub, llvm::dbgs(), E, G, llvm::jitlink::getMachOX86RelocationKindName(), LLVM_DEBUG, llvm::jitlink::MachO_x86_64_Edges::PCRel32, llvm::jitlink::MachO_x86_64_Edges::PCRel32GOTLoad, llvm::jitlink::printEdge(), and llvm::Error::success().
Referenced by llvm::jitlink::link_MachO_x86_64().