LLVM: lib/Support/ManagedStatic.cpp File Reference
ManagedStatic.cpp File Reference
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Threading.h"
#include <cassert>
#include <mutex>
Functions
static void initializeMutex ()
static std::recursive_mutex * getManagedStaticMutex ()
Variables
static const ManagedStaticBase * StaticList = nullptr
static std::recursive_mutex * ManagedStaticMutex = nullptr
static llvm::once_flag mutex_init_flag
Function Documentation
getManagedStaticMutex()
static std::recursive_mutex * getManagedStaticMutex () static
Definition at line 28 of file ManagedStatic.cpp.
References llvm::call_once(), initializeMutex(), ManagedStaticMutex, and mutex_init_flag.
Referenced by llvm::llvm_shutdown(), and llvm::ManagedStaticBase::RegisterManagedStatic().
initializeMutex()
static void initializeMutex () static
Definition at line 24 of file ManagedStatic.cpp.
References ManagedStaticMutex.
Referenced by getManagedStaticMutex().
Variable Documentation
ManagedStaticMutex
std::recursive_mutex* ManagedStaticMutex = nullptr static
Definition at line 21 of file ManagedStatic.cpp.
Referenced by getManagedStaticMutex(), and initializeMutex().
mutex_init_flag
llvm::once_flag mutex_init_flag static
Definition at line 22 of file ManagedStatic.cpp.
Referenced by getManagedStaticMutex().
StaticList
const ManagedStaticBase* StaticList = nullptr static
Definition at line 20 of file ManagedStatic.cpp.
Referenced by llvm::ManagedStaticBase::destroy(), llvm::llvm_shutdown(), and llvm::ManagedStaticBase::RegisterManagedStatic().