LLVM: lib/MC/MCCodeView.cpp File Reference
MCCodeView.cpp File Reference
#include "llvm/MC/MCCodeView.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/Line.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/EndianStream.h"
Functions
static bool compressAnnotation (uint32_t Data, SmallVectorImpl< char > &Buffer)
static bool compressAnnotation (BinaryAnnotationsOpCode Annotation, SmallVectorImpl< char > &Buffer)
static uint32_t encodeSignedNumber (uint32_t Data)
static unsigned computeLabelDiff (MCAsmLayout &Layout, const MCSymbol *Begin, const MCSymbol *End)
Function Documentation
compressAnnotation() [1/2]
static bool compressAnnotation (BinaryAnnotationsOpCode Annotation, SmallVectorImpl< char > & Buffer) static
Definition at line 410 of file MCCodeView.cpp.
References compressAnnotation().
compressAnnotation() [2/2]
static bool compressAnnotation (uint32_t Data, SmallVectorImpl< char > & Buffer) static
Definition at line 387 of file MCCodeView.cpp.
References llvm::Data, llvm::isUInt(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by compressAnnotation(), and llvm::CodeViewContext::encodeInlineLineTable().
computeLabelDiff()
static unsigned computeLabelDiff (MCAsmLayout & Layout, const MCSymbol * Begin, const MCSymbol * End) static
Definition at line 444 of file MCCodeView.cpp.
References assert(), llvm::MCBinaryExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCAsmLayout::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCBinaryExpr::Sub, Success, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::CodeViewContext::encodeDefRange(), and llvm::CodeViewContext::encodeInlineLineTable().
encodeSignedNumber()
static uint32_t encodeSignedNumber (uint32_t Data) static
Definition at line 415 of file MCCodeView.cpp.
References llvm::Data.
Referenced by llvm::CodeViewContext::encodeInlineLineTable().