LLVM: lib/MC/MCDwarf.cpp File Reference
MCDwarf.cpp File Reference
#include "llvm/MC/MCDwarf.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/Config/config.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>
Classes
class llvm::MCDwarfLineStr
Manage the .debug_line_str section contents, if we use it.
struct llvm::DenseMapInfo< CIEKey >
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static uint64_t ScaleAddrDelta (MCContext &Context, uint64_t AddrDelta)
static const MCExpr * makeEndMinusStartExpr (MCContext &Ctx, const MCSymbol &Start, const MCSymbol &End, int IntVal)
static const MCExpr * makeStartPlusIntExpr (MCContext &Ctx, const MCSymbol &Start, int IntVal)
static void emitDwarfLineTable (MCObjectStreamer *MCOS, MCSection *Section, const MCLineSection::MCDwarfLineEntryCollection &LineEntries)
static const MCExpr * forceExpAbs (MCStreamer &OS, const MCExpr *Expr)
static void emitAbsValue (MCStreamer &OS, const MCExpr *Value, unsigned Size)
static void emitOneV5FileEntry (MCStreamer *MCOS, const MCDwarfFile &DwarfFile, bool EmitMD5, bool HasSource, Optional< MCDwarfLineStr > &LineStr)
static bool isRootFile (const MCDwarfFile &RootFile, StringRef &Directory, StringRef &FileName, Optional< MD5::MD5Result > Checksum)
static uint64_t SpecialAddr (MCDwarfLineTableParams Params, uint64_t op)
Given a special op, return the address skip amount (in units of DWARF2_LINE_MIN_INSN_LENGTH).
static void EmitAbbrev (MCStreamer *MCOS, uint64_t Name, uint64_t Form)
static void EmitGenDwarfAbbrev (MCStreamer *MCOS)
static void EmitGenDwarfAranges (MCStreamer *MCOS, const MCSymbol *InfoSectionSymbol)
static void EmitGenDwarfInfo (MCStreamer *MCOS, const MCSymbol *AbbrevSectionSymbol, const MCSymbol *LineSectionSymbol, const MCSymbol *RangesSymbol)
static MCSymbol * emitGenDwarfRanges (MCStreamer *MCOS)
static int getDataAlignmentFactor (MCStreamer &streamer)
static unsigned getSizeForEncoding (MCStreamer &streamer, unsigned symbolEncoding)
static void emitFDESymbol (MCObjectStreamer &streamer, const MCSymbol &symbol, unsigned symbolEncoding, bool isEH)
static void EmitPersonality (MCStreamer &streamer, const MCSymbol &symbol, unsigned symbolEncoding)
static void emitEncodingByte (MCObjectStreamer &Streamer, unsigned Encoding)
static unsigned getCIEVersion (bool IsEH, unsigned DwarfVersion)
Function Documentation
EmitAbbrev()
static void EmitAbbrev (MCStreamer * MCOS, uint64_t Name, uint64_t Form) static
Definition at line 818 of file MCDwarf.cpp.
References llvm::MCStreamer::emitULEB128IntValue(), and Name.
Referenced by EmitGenDwarfAbbrev().
emitAbsValue()
static void emitAbsValue (MCStreamer & OS, const MCExpr * Value, unsigned Size) static
Definition at line 321 of file MCDwarf.cpp.
References llvm::MCStreamer::emitValue(), forceExpAbs(), and Size.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and emitGenDwarfRanges().
emitDwarfLineTable()
static void emitDwarfLineTable (MCObjectStreamer * MCOS, MCSection * Section, const MCLineSection::MCDwarfLineEntryCollection & LineEntries) inline static
Definition at line 165 of file MCDwarf.cpp.
References DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, DWARF2_LINE_DEFAULT_IS_STMT, llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitULEB128IntValue(), llvm::MCStreamer::endSection(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfVersion(), llvm::getULEB128Size(), INT64_MAX, Size, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCDwarfLineTable::EmitCU().
emitEncodingByte()
static void emitEncodingByte (MCObjectStreamer & Streamer, unsigned Encoding) static
Definition at line 1369 of file MCDwarf.cpp.
References llvm::MCStreamer::emitInt8().
emitFDESymbol()
static void emitFDESymbol (MCObjectStreamer & streamer, const MCSymbol & symbol, unsigned symbolEncoding, bool isEH) static
Definition at line 1319 of file MCDwarf.cpp.
References llvm::MCAsmInfo::doDwarfFDESymbolsUseAbsDiff(), emitAbsValue(), llvm::MCStreamer::emitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getExprForFDESymbol(), and getSizeForEncoding().
EmitGenDwarfAbbrev()
static void EmitGenDwarfAbbrev (MCStreamer * MCOS) static
Definition at line 825 of file MCDwarf.cpp.
References llvm::dwarf::DW_CHILDREN_no, llvm::dwarf::DW_CHILDREN_yes, llvm::dwarf::DWARF64, EmitAbbrev(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitULEB128IntValue(), llvm::StringRef::empty(), llvm::MCContext::getCompilationDir(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCContext::getDwarfDebugFlags(), llvm::MCContext::getDwarfFormat(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitGenDwarfAranges()
static void EmitGenDwarfAranges (MCStreamer * MCOS, const MCSymbol * InfoSectionSymbol) static
Definition at line 874 of file MCDwarf.cpp.
References Addr, assert(), llvm::MCSymbolRefExpr::create(), llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, emitAbsValue(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitSymbolValue(), llvm::MCStreamer::emitValue(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfARangesSection(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), llvm::dwarf::getUnitLengthFieldByteSize(), makeEndMinusStartExpr(), llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), Size, llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitGenDwarfInfo()
static void EmitGenDwarfInfo (MCStreamer * MCOS, const MCSymbol * AbbrevSectionSymbol, const MCSymbol * LineSectionSymbol, const MCSymbol * RangesSymbol) static
Definition at line 953 of file MCDwarf.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, emitAbsValue(), llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitSymbolValue(), llvm::MCStreamer::emitULEB128IntValue(), llvm::MCStreamer::emitValue(), llvm::SmallVectorBase< Size_T >::empty(), llvm::StringRef::empty(), llvm::sys::path::get_separator(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCContext::getCompilationDir(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfDebugFlags(), llvm::MCContext::getDwarfDebugProducer(), llvm::MCContext::getDwarfFormat(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getMCDwarfDirs(), llvm::MCContext::getMCDwarfFiles(), llvm::MCContext::getMCDwarfLineTable(), llvm::MCContext::getMCGenDwarfLabelEntries(), llvm::MCContext::getObjectFileInfo(), llvm::MCDwarfLineTable::getRootFile(), llvm::dwarf::getUnitLengthFieldByteSize(), makeEndMinusStartExpr(), llvm::MCDwarfFile::Name, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), llvm::SmallVectorBase< Size_T >::size(), llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
emitGenDwarfRanges()
static MCSymbol * emitGenDwarfRanges (MCStreamer * MCOS) static
Definition at line 1127 of file MCDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), emitAbsValue(), llvm::MCStreamer::emitFill(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitLabel(), llvm::mcdwarf::emitListsTableHeaderStart(), llvm::MCStreamer::emitULEB128Value(), llvm::MCStreamer::emitValue(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::MCObjectFileInfo::getDwarfRnglistsSection(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), makeEndMinusStartExpr(), llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
emitOneV5FileEntry()
static void emitOneV5FileEntry (MCStreamer * MCOS, const MCDwarfFile & DwarfFile, bool EmitMD5, bool HasSource, Optional< MCDwarfLineStr > & LineStr) static
Definition at line 369 of file MCDwarf.cpp.
References assert(), llvm::MD5::MD5Result::Bytes, llvm::MCStreamer::emitBinaryData(), llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::emitULEB128IntValue().
EmitPersonality()
static void EmitPersonality (MCStreamer & streamer, const MCSymbol & symbol, unsigned symbolEncoding) static
Definition at line 1333 of file MCDwarf.cpp.
References llvm::MCStreamer::emitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getExprForPersonalitySymbol(), and getSizeForEncoding().
forceExpAbs()
static const MCExpr * forceExpAbs (MCStreamer & OS, const MCExpr * Expr) static
Definition at line 310 of file MCDwarf.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), llvm::MCStreamer::emitAssignment(), llvm::MCStreamer::getContext(), and llvm::isa().
Referenced by emitAbsValue().
getCIEVersion()
static unsigned getCIEVersion (bool IsEH, unsigned DwarfVersion) static
Definition at line 1589 of file MCDwarf.cpp.
References llvm_unreachable.
getDataAlignmentFactor()
static int getDataAlignmentFactor (MCStreamer & streamer) static
Definition at line 1288 of file MCDwarf.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCalleeSaveStackSlotSize(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::isStackGrowthDirectionUp(), and size().
getSizeForEncoding()
static unsigned getSizeForEncoding (MCStreamer & streamer, unsigned symbolEncoding) static
Definition at line 1298 of file MCDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_sdata2, llvm::dwarf::DW_EH_PE_sdata4, llvm::dwarf::DW_EH_PE_sdata8, llvm::dwarf::DW_EH_PE_signed, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::format(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), and llvm_unreachable.
Referenced by emitFDESymbol(), and EmitPersonality().
isRootFile()
static bool isRootFile (const MCDwarfFile & RootFile, StringRef & Directory, StringRef & FileName, Optional< MD5::MD5Result > Checksum) static
Definition at line 574 of file MCDwarf.cpp.
References llvm::MCDwarfFile::Checksum, llvm::StringRef::data(), and llvm::MCDwarfFile::Name.
Referenced by llvm::MCDwarfLineTableHeader::tryGetFile().
makeEndMinusStartExpr()
static const MCExpr * makeEndMinusStartExpr (MCContext & Ctx, const MCSymbol & Start, const MCSymbol & End, int IntVal) inline static
Definition at line 136 of file MCDwarf.cpp.
References llvm::MCBinaryExpr::create(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and emitGenDwarfRanges().
makeStartPlusIntExpr()
static const MCExpr * makeStartPlusIntExpr (MCContext & Ctx, const MCSymbol & Start, int IntVal) inline static
Definition at line 153 of file MCDwarf.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::create(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCDwarfLineStr::emitRef().
ScaleAddrDelta()
static uint64_t ScaleAddrDelta (MCContext & Context, uint64_t AddrDelta) inline static
Definition at line 92 of file MCDwarf.cpp.
Referenced by llvm::MCDwarfLineAddr::Encode(), and llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc().
SpecialAddr()
static uint64_t SpecialAddr (MCDwarfLineTableParams Params, uint64_t op) static
Given a special op, return the address skip amount (in units of DWARF2_LINE_MIN_INSN_LENGTH).
Definition at line 682 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableParams::DWARF2LineOpcodeBase, llvm::MCDwarfLineTableParams::DWARF2LineRange, and op.
Referenced by llvm::MCDwarfLineAddr::Encode().