LLVM: lib/Analysis/MemorySSAUpdater.cpp File Reference
MemorySSAUpdater.cpp File Reference
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/IteratedDominanceFrontier.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormattedStream.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "memoryssa"
Functions
static void setMemoryPhiValueForBlock (MemoryPhi *MP, const BasicBlock *BB, MemoryAccess *NewDef)
static MemoryAccess * onlySingleValue (MemoryPhi *MP)
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
static MemoryAccess * getNewDefiningAccessForClone (MemoryAccess *MA, const ValueToValueMapTy &VMap, PhiToDefMap &MPhiMap, bool CloneWasSimplified, MemorySSA *MSSA)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memoryssa"
Definition at line 31 of file MemorySSAUpdater.cpp.
Function Documentation
getNewDefiningAccessForClone()
static MemoryAccess * getNewDefiningAccessForClone (MemoryAccess * MA, const ValueToValueMapTy & VMap, PhiToDefMap & MPhiMap, bool CloneWasSimplified, MemorySSA * MSSA) static
Definition at line 572 of file MemorySSAUpdater.cpp.
References assert(), llvm::simple_ilist< T, Options >::begin(), llvm::cast(), llvm::cast_or_null(), llvm::dyn_cast(), llvm::MemorySSA::getBlockDefs(), llvm::MemorySSA::getMemoryAccess(), getNewDefiningAccessForClone(), llvm::isa(), llvm::MemorySSA::isLiveOnEntryDef(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::ValueMap< KeyT, ValueT, Config >::lookup().
Referenced by getNewDefiningAccessForClone().
onlySingleValue()
static MemoryAccess * onlySingleValue (MemoryPhi * MP) static
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
Definition at line 560 of file MemorySSAUpdater.cpp.
References Arg, llvm::cast(), and llvm::User::operands().
Referenced by llvm::MemorySSAUpdater::removeMemoryAccess(), and llvm::MemorySSAUpdater::updateForClonedLoop().
setMemoryPhiValueForBlock()
static void setMemoryPhiValueForBlock (MemoryPhi * MP, const BasicBlock * BB, MemoryAccess * NewDef) static
Definition at line 291 of file MemorySSAUpdater.cpp.
References assert(), llvm::MemoryPhi::block_begin(), llvm::MemoryPhi::block_end(), llvm::MemoryPhi::getBasicBlockIndex(), and llvm::MemoryPhi::setIncomingValue().