LLVM: llvm::Intrinsic Namespace Reference
llvm::Intrinsic Namespace Reference
This namespace contains an enum with a value for every intrinsic/builtin function known by LLVM.
Classes
struct IITDescriptor
This is a type descriptor which explains the type requirements of an intrinsic.
Typedefs
typedef unsigned ID
LLVM IR allows to use arbitrary numbers as calling convention identifiers.
Enumerations
enum IndependentIntrinsics : unsigned {
not_intrinsic = 0 , abs = 1 , addressofreturnaddress , adjust_trampoline ,
annotation , assume , bitreverse , bswap ,
call_preallocated_arg , call_preallocated_setup , call_preallocated_teardown , canonicalize ,
ceil , clear_cache , codeview_annotation , convert_from_fp16 ,
convert_to_fp16 , copysign , coro_alloc , coro_alloca_alloc ,
coro_alloca_free , coro_alloca_get , coro_async_context_alloc , coro_async_context_dealloc ,
coro_async_resume , coro_begin , coro_destroy , coro_done ,
coro_end , coro_end_async , coro_frame , coro_free ,
coro_id , coro_id_async , coro_id_retcon , coro_id_retcon_once ,
coro_noop , coro_param , coro_prepare_async , coro_prepare_retcon ,
coro_promise , coro_resume , coro_save , coro_size ,
coro_subfn_addr , coro_suspend , coro_suspend_async , coro_suspend_retcon ,
cos , ctlz , ctpop , cttz ,
dbg_addr , dbg_declare , dbg_label , dbg_value ,
debugtrap , donothing , eh_dwarf_cfa , eh_exceptioncode ,
eh_exceptionpointer , eh_recoverfp , eh_return_i32 , eh_return_i64 ,
eh_sjlj_callsite , eh_sjlj_functioncontext , eh_sjlj_longjmp , eh_sjlj_lsda ,
eh_sjlj_setjmp , eh_sjlj_setup_dispatch , eh_typeid_for , eh_unwind_init ,
exp , exp2 , expect , expect_with_probability ,
experimental_constrained_ceil , experimental_constrained_cos , experimental_constrained_exp , experimental_constrained_exp2 ,
experimental_constrained_fadd , experimental_constrained_fcmp , experimental_constrained_fcmps , experimental_constrained_fdiv ,
experimental_constrained_floor , experimental_constrained_fma , experimental_constrained_fmul , experimental_constrained_fmuladd ,
experimental_constrained_fpext , experimental_constrained_fptosi , experimental_constrained_fptoui , experimental_constrained_fptrunc ,
experimental_constrained_frem , experimental_constrained_fsub , experimental_constrained_llrint , experimental_constrained_llround ,
experimental_constrained_log , experimental_constrained_log10 , experimental_constrained_log2 , experimental_constrained_lrint ,
experimental_constrained_lround , experimental_constrained_maximum , experimental_constrained_maxnum , experimental_constrained_minimum ,
experimental_constrained_minnum , experimental_constrained_nearbyint , experimental_constrained_pow , experimental_constrained_powi ,
experimental_constrained_rint , experimental_constrained_round , experimental_constrained_roundeven , experimental_constrained_sin ,
experimental_constrained_sitofp , experimental_constrained_sqrt , experimental_constrained_trunc , experimental_constrained_uitofp ,
experimental_deoptimize , experimental_gc_relocate , experimental_gc_result , experimental_gc_statepoint ,
experimental_guard , experimental_noalias_scope_decl , experimental_patchpoint_i64 , experimental_patchpoint_void ,
experimental_stackmap , experimental_vector_extract , experimental_vector_insert , experimental_widenable_condition ,
fabs , floor , flt_rounds , fma ,
fmuladd , fptosi_sat , fptoui_sat , frameaddress ,
fshl , fshr , gcread , gcroot ,
gcwrite , get_active_lane_mask , get_dynamic_area_offset , hwasan_check_memaccess ,
hwasan_check_memaccess_shortgranules , icall_branch_funnel , init_trampoline , instrprof_increment ,
instrprof_increment_step , instrprof_value_profile , invariant_end , invariant_start ,
is_constant , launder_invariant_group , lifetime_end , lifetime_start ,
llrint , llround , load_relative , localaddress ,
localescape , localrecover , log , log10 ,
log2 , loop_decrement , loop_decrement_reg , lrint ,
lround , masked_compressstore , masked_expandload , masked_gather ,
masked_load , masked_scatter , masked_store , matrix_column_major_load ,
matrix_column_major_store , matrix_multiply , matrix_transpose , maximum ,
maxnum , memcpy , memcpy_element_unordered_atomic , memcpy_inline ,
memmove , memmove_element_unordered_atomic , memset , memset_element_unordered_atomic ,
minimum , minnum , nearbyint , objc_arc_annotation_bottomup_bbend ,
objc_arc_annotation_bottomup_bbstart , objc_arc_annotation_topdown_bbend , objc_arc_annotation_topdown_bbstart , objc_autorelease ,
objc_autoreleasePoolPop , objc_autoreleasePoolPush , objc_autoreleaseReturnValue , objc_clang_arc_use ,
objc_copyWeak , objc_destroyWeak , objc_initWeak , objc_loadWeak ,
objc_loadWeakRetained , objc_moveWeak , objc_release , objc_retain ,
objc_retain_autorelease , objc_retainAutorelease , objc_retainAutoreleaseReturnValue , objc_retainAutoreleasedReturnValue ,
objc_retainBlock , objc_retainedObject , objc_storeStrong , objc_storeWeak ,
objc_sync_enter , objc_sync_exit , objc_unretainedObject , objc_unretainedPointer ,
objc_unsafeClaimAutoreleasedReturnValue , objectsize , pcmarker , pow ,
powi , prefetch , preserve_array_access_index , preserve_struct_access_index ,
preserve_union_access_index , pseudoprobe , ptr_annotation , ptrmask ,
read_register , read_volatile_register , readcyclecounter , returnaddress ,
rint , round , roundeven , sadd_sat ,
sadd_with_overflow , sdiv_fix , sdiv_fix_sat , set_loop_iterations ,
sideeffect , sin , smax , smin ,
smul_fix , smul_fix_sat , smul_with_overflow , sponentry ,
sqrt , ssa_copy , sshl_sat , ssub_sat ,
ssub_with_overflow , stackguard , stackprotector , stackrestore ,
stacksave , start_loop_iterations , strip_invariant_group , test_set_loop_iterations ,
thread_pointer , trap , trunc , type_checked_load ,
type_test , uadd_sat , uadd_with_overflow , ubsantrap ,
udiv_fix , udiv_fix_sat , umax , umin ,
umul_fix , umul_fix_sat , umul_with_overflow , ushl_sat ,
usub_sat , usub_with_overflow , vacopy , vaend ,
vastart , var_annotation , vector_reduce_add , vector_reduce_and ,
vector_reduce_fadd , vector_reduce_fmax , vector_reduce_fmin , vector_reduce_fmul ,
vector_reduce_mul , vector_reduce_or , vector_reduce_smax , vector_reduce_smin ,
vector_reduce_umax , vector_reduce_umin , vector_reduce_xor , vp_add ,
vp_and , vp_ashr , vp_lshr , vp_mul ,
vp_or , vp_sdiv , vp_shl , vp_srem ,
vp_sub , vp_udiv , vp_urem , vp_xor ,
vscale , write_register , xray_customevent , xray_typedevent ,
num_intrinsics
}
enum MatchIntrinsicTypesResult { MatchIntrinsicTypes_Match = 0 , MatchIntrinsicTypes_NoMatchRet = 1 , MatchIntrinsicTypes_NoMatchArg = 2 }
Functions
StringRef getName (ID id)
Return the LLVM name for an intrinsic, such as "llvm.ppc.altivec.lvx".
std::string getName (ID id, ArrayRef< Type * > Tys)
Return the LLVM name for an intrinsic, such as "llvm.ppc.altivec.lvx".
FunctionType * getType (LLVMContext &Context, ID id, ArrayRef< Type * > Tys=None)
Return the function type for an intrinsic.
bool isOverloaded (ID id)
Returns true if the intrinsic can be overloaded.
bool isLeaf (ID id)
Returns true if the intrinsic is a leaf, i.e.
AttributeList getAttributes (LLVMContext &C, ID id)
Return the attributes for an intrinsic.
Function * getDeclaration (Module *M, ID id, ArrayRef< Type * > Tys=None)
Create or insert an LLVM Function declaration for an intrinsic, and return it.
int lookupLLVMIntrinsicByName (ArrayRef< const char * > NameTable, StringRef Name)
Looks up Name in NameTable via binary search.
ID getIntrinsicForGCCBuiltin (const char *Prefix, StringRef BuiltinName)
Map a GCC builtin name to an intrinsic ID.
ID getIntrinsicForMSBuiltin (const char *Prefix, StringRef BuiltinName)
Map a MS builtin name to an intrinsic ID.
void getIntrinsicInfoTableEntries (ID id, SmallVectorImpl< IITDescriptor > &T)
Return the IIT table descriptor for the specified intrinsic into an array of IITDescriptors.
MatchIntrinsicTypesResult matchIntrinsicSignature (FunctionType *FTy, ArrayRef< IITDescriptor > &Infos, SmallVectorImpl< Type * > &ArgTys)
Match the specified function type with the type constraints specified by the .td file.
bool matchIntrinsicVarArg (bool isVarArg, ArrayRef< IITDescriptor > &Infos)
Verify if the intrinsic has variable arguments.
bool getIntrinsicSignature (Function *F, SmallVectorImpl< Type * > &ArgTys)
Gets the type arguments of an intrinsic call by matching type contraints specified by the .td file.
llvm::Optional< Function * > remangleIntrinsicFunction (Function *F)
Variables
static const int NoAliasScopeDeclScopeArg = 0
Detailed Description
This namespace contains an enum with a value for every intrinsic/builtin function known by LLVM.
The enum values are returned by Function::getIntrinsicID().
Typedef Documentation
ID
typedef unsigned llvm::Intrinsic::ID
LLVM IR allows to use arbitrary numbers as calling convention identifiers.
Definition at line 36 of file TargetTransformInfo.h.
Enumeration Type Documentation
IndependentIntrinsics
enum llvm::Intrinsic::IndependentIntrinsics : unsigned
Enumerator
not_intrinsic
abs
addressofreturnaddress
adjust_trampoline
annotation
assume
bitreverse
bswap
call_preallocated_arg
call_preallocated_setup
call_preallocated_teardown
canonicalize
ceil
clear_cache
codeview_annotation
convert_from_fp16
convert_to_fp16
copysign
coro_alloc
coro_alloca_alloc
coro_alloca_free
coro_alloca_get
coro_async_context_alloc
coro_async_context_dealloc
coro_async_resume
coro_begin
coro_destroy
coro_done
coro_end
coro_end_async
coro_frame
coro_free
coro_id
coro_id_async
coro_id_retcon
coro_id_retcon_once
coro_noop
coro_param
coro_prepare_async
coro_prepare_retcon
coro_promise
coro_resume
coro_save
coro_size
coro_subfn_addr
coro_suspend
coro_suspend_async
coro_suspend_retcon
cos
ctlz
ctpop
cttz
dbg_addr
dbg_declare
dbg_label
dbg_value
debugtrap
donothing
eh_dwarf_cfa
eh_exceptioncode
eh_exceptionpointer
eh_recoverfp
eh_return_i32
eh_return_i64
eh_sjlj_callsite
eh_sjlj_functioncontext
eh_sjlj_longjmp
eh_sjlj_lsda
eh_sjlj_setjmp
eh_sjlj_setup_dispatch
eh_typeid_for
eh_unwind_init
exp
exp2
expect
expect_with_probability
experimental_constrained_ceil
experimental_constrained_cos
experimental_constrained_exp
experimental_constrained_exp2
experimental_constrained_fadd
experimental_constrained_fcmp
experimental_constrained_fcmps
experimental_constrained_fdiv
experimental_constrained_floor
experimental_constrained_fma
experimental_constrained_fmul
experimental_constrained_fmuladd
experimental_constrained_fpext
experimental_constrained_fptosi
experimental_constrained_fptoui
experimental_constrained_fptrunc
experimental_constrained_frem
experimental_constrained_fsub
experimental_constrained_llrint
experimental_constrained_llround
experimental_constrained_log
experimental_constrained_log10
experimental_constrained_log2
experimental_constrained_lrint
experimental_constrained_lround
experimental_constrained_maximum
experimental_constrained_maxnum
experimental_constrained_minimum
experimental_constrained_minnum
experimental_constrained_nearbyint
experimental_constrained_pow
experimental_constrained_powi
experimental_constrained_rint
experimental_constrained_round
experimental_constrained_roundeven
experimental_constrained_sin
experimental_constrained_sitofp
experimental_constrained_sqrt
experimental_constrained_trunc
experimental_constrained_uitofp
experimental_deoptimize
experimental_gc_relocate
experimental_gc_result
experimental_gc_statepoint
experimental_guard
experimental_noalias_scope_decl
experimental_patchpoint_i64
experimental_patchpoint_void
experimental_stackmap
experimental_vector_extract
experimental_vector_insert
experimental_widenable_condition
fabs
floor
flt_rounds
fma
fmuladd
fptosi_sat
fptoui_sat
frameaddress
fshl
fshr
gcread
gcroot
gcwrite
get_active_lane_mask
get_dynamic_area_offset
hwasan_check_memaccess
hwasan_check_memaccess_shortgranules
icall_branch_funnel
init_trampoline
instrprof_increment
instrprof_increment_step
instrprof_value_profile
invariant_end
invariant_start
is_constant
launder_invariant_group
lifetime_end
lifetime_start
llrint
llround
load_relative
localaddress
localescape
localrecover
log
log10
log2
loop_decrement
loop_decrement_reg
lrint
lround
masked_compressstore
masked_expandload
masked_gather
masked_load
masked_scatter
masked_store
matrix_column_major_load
matrix_column_major_store
matrix_multiply
matrix_transpose
maximum
maxnum
memcpy
memcpy_element_unordered_atomic
memcpy_inline
memmove
memmove_element_unordered_atomic
memset
memset_element_unordered_atomic
minimum
minnum
nearbyint
objc_arc_annotation_bottomup_bbend
objc_arc_annotation_bottomup_bbstart
objc_arc_annotation_topdown_bbend
objc_arc_annotation_topdown_bbstart
objc_autorelease
objc_autoreleasePoolPop
objc_autoreleasePoolPush
objc_autoreleaseReturnValue
objc_clang_arc_use
objc_copyWeak
objc_destroyWeak
objc_initWeak
objc_loadWeak
objc_loadWeakRetained
objc_moveWeak
objc_release
objc_retain
objc_retain_autorelease
objc_retainAutorelease
objc_retainAutoreleaseReturnValue
objc_retainAutoreleasedReturnValue
objc_retainBlock
objc_retainedObject
objc_storeStrong
objc_storeWeak
objc_sync_enter
objc_sync_exit
objc_unretainedObject
objc_unretainedPointer
objc_unsafeClaimAutoreleasedReturnValue
objectsize
pcmarker
pow
powi
prefetch
preserve_array_access_index
preserve_struct_access_index
preserve_union_access_index
pseudoprobe
ptr_annotation
ptrmask
read_register
read_volatile_register
readcyclecounter
returnaddress
rint
round
roundeven
sadd_sat
sadd_with_overflow
sdiv_fix
sdiv_fix_sat
set_loop_iterations
sideeffect
sin
smax
smin
smul_fix
smul_fix_sat
smul_with_overflow
sponentry
sqrt
ssa_copy
sshl_sat
ssub_sat
ssub_with_overflow
stackguard
stackprotector
stackrestore
stacksave
start_loop_iterations
strip_invariant_group
test_set_loop_iterations
thread_pointer
trap
trunc
type_checked_load
type_test
uadd_sat
uadd_with_overflow
ubsantrap
udiv_fix
udiv_fix_sat
umax
umin
umul_fix
umul_fix_sat
umul_with_overflow
ushl_sat
usub_sat
usub_with_overflow
vacopy
vaend
vastart
var_annotation
vector_reduce_add
vector_reduce_and
vector_reduce_fadd
vector_reduce_fmax
vector_reduce_fmin
vector_reduce_fmul
vector_reduce_mul
vector_reduce_or
vector_reduce_smax
vector_reduce_smin
vector_reduce_umax
vector_reduce_umin
vector_reduce_xor
vp_add
vp_and
vp_ashr
vp_lshr
vp_mul
vp_or
vp_sdiv
vp_shl
vp_srem
vp_sub
vp_udiv
vp_urem
vp_xor
vscale
write_register
xray_customevent
xray_typedevent
num_intrinsics
Definition at line 44 of file Intrinsics.h.
MatchIntrinsicTypesResult
enum llvm::Intrinsic::MatchIntrinsicTypesResult
Enumerator
MatchIntrinsicTypes_Match
MatchIntrinsicTypes_NoMatchRet
MatchIntrinsicTypes_NoMatchArg
Definition at line 205 of file Intrinsics.h.
Function Documentation
getAttributes()
AttributeList llvm::Intrinsic::getAttributes (LLVMContext & C, ID id)
Return the attributes for an intrinsic.
Referenced by llvm::SITargetLowering::computeKnownAlignForTargetInstr(), llvm::SITargetLowering::getTgtMemIntrinsic(), and llvm::UpgradeIntrinsicFunction().
getDeclaration()
Function * llvm::Intrinsic::getDeclaration (Module * M, ID id, ArrayRef< Type * > Tys = None)
Create or insert an LLVM Function declaration for an intrinsic, and return it.
The Tys parameter is for intrinsics with overloaded types (e.g., those using iAny, fAny, vAny, or iPTRAny). For a declaration of an overloaded intrinsic, Tys must provide exactly one type for each overloaded type in the intrinsic.
Definition at line 1252 of file Function.cpp.
References llvm::cast(), llvm::ArrayRef< T >::empty(), getName(), and getType().
Referenced by addAssumeNonNull(), addBoundsChecking(), callIntrinsic(), llvm::changeToUnreachable(), llvm::IRBuilderBase::CreateAssumption(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::MatrixBuilder< IRBuilderTy >::CreateColumnMajorLoad(), llvm::MatrixBuilder< IRBuilderTy >::CreateColumnMajorStore(), createCoroSave(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), createFFSIntrinsic(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::IRBuilderBase::CreateGCRelocate(), CreateGCRelocates(), llvm::IRBuilderBase::CreateGCResult(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilderBase::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::MatrixBuilder< IRBuilderTy >::CreateMatrixMultiply(), llvm::MatrixBuilder< IRBuilderTy >::CreateMatrixTranspose(), llvm::IRBuilderBase::CreateMemCpyInline(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateMemTransferInst(), llvm::IRBuilderBase::CreateNoAliasScopeDeclaration(), createPopcntIntrinsic(), createPowWithIntegerExponent(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreatePreserveUnionAccessIndex(), CreatePrologue(), llvm::IRBuilderBase::CreateStripInvariantGroup(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::IRBuilderBase::CreateVScale(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::RISCVTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), explicifyGuards(), foldCtpop(), foldCttzCtlz(), foldGuardedFunnelShift(), foldToUnsignedSaturatedAdd(), llvm::InstCombinerImpl::foldUnsignedMultiplicationOverflowCheck(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), getDeclareIntrin(), getReductionIntrinsic(), getScalarIntrinsicDeclaration(), getSqrtCall(), getStackGuard(), llvm::InlineFunction(), insertCall(), insertLifetimeMarkersSurroundingCall(), llvm::BPFCoreSharedInfo::insertPassThrough(), llvm::GCNTTIImpl::instCombineIntrinsic(), instrumentOneFunc(), llvm::SampleProfileProber::instrumentOneFunc(), LLVMGetIntrinsicDeclaration(), lowerGuardIntrinsic(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerLocalAllocas(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::ARMTargetLowering::makeDMB(), llvm::coro::LowererBase::makeSubFnCall(), matchFunnelShift(), matchOrConcat(), optimizeDoubleFP(), optimizeWithFDivFast(), optimizeWithRcp(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::recognizeBSwapOrBitReverseIdiom(), remangleIntrinsicFunction(), RemovePreallocated(), replaceUnaryCall(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), simplifyAMDGCNImageIntrinsic(), simplifyAMDGCNMemoryIntrinsicDemanded(), SimplifyBSwap(), simplifyNvvmIntrinsic(), simplifyX86extrq(), simplifyX86insertq(), tryToRecognizePopCount(), upgradeAbs(), llvm::UpgradeARCRuntime(), upgradeAVX512MaskToSelect(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), UpgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), UpgradeX86IntrinsicFunction(), UpgradeX86IntrinsicsWith8BitMask(), UpgradeX86MaskedFPCompare(), UpgradeX86MaskedShift(), upgradeX86Rotate(), UpgradeX86VPERMT2Intrinsics(), UseTlsOffset(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFPTrunc(), and llvm::InnerLoopVectorizer::widenCallInstruction().
getIntrinsicForGCCBuiltin()
ID llvm::Intrinsic::getIntrinsicForGCCBuiltin (const char * Prefix, StringRef BuiltinName)
Map a GCC builtin name to an intrinsic ID.
getIntrinsicForMSBuiltin()
ID llvm::Intrinsic::getIntrinsicForMSBuiltin (const char * Prefix, StringRef BuiltinName)
Map a MS builtin name to an intrinsic ID.
getIntrinsicInfoTableEntries()
void llvm::Intrinsic::getIntrinsicInfoTableEntries (ID id, SmallVectorImpl< IITDescriptor > & T)
Return the IIT table descriptor for the specified intrinsic into an array of IITDescriptors.
Definition at line 1074 of file Function.cpp.
References DecodeIITType(), IIT_Done, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::size().
Referenced by getIntrinsicSignature(), and getType().
getIntrinsicSignature()
bool llvm::Intrinsic::getIntrinsicSignature (Function * F, SmallVectorImpl< Type * > & ArgTys)
Gets the type arguments of an intrinsic call by matching type contraints specified by the .td file.
The overloaded types are pushed into the AgTys vector.
Returns false if the given function is not a valid intrinsic call.
Definition at line 1541 of file Function.cpp.
References F, getIntrinsicInfoTableEntries(), matchIntrinsicSignature(), MatchIntrinsicTypes_Match, and matchIntrinsicVarArg().
Referenced by remangleIntrinsicFunction(), simplifyAMDGCNImageIntrinsic(), and simplifyAMDGCNMemoryIntrinsicDemanded().
getName() [1/2]
StringRef llvm::Intrinsic::getName (ID id)
Return the LLVM name for an intrinsic, such as "llvm.ppc.altivec.lvx".
Note, this version is for intrinsics with no overloads. Use the other version of getName if overloads are required.
Definition at line 778 of file Function.cpp.
References assert(), IntrinsicNameTable, isOverloaded(), and num_intrinsics.
Referenced by containsProfilingIntrinsics(), explicifyGuards(), getImpl(), llvm::SDNode::getOperationName(), LLVMIntrinsicCopyOverloadedName(), LLVMIntrinsicGetName(), lowerGuardIntrinsic(), lowerWidenableCondition(), llvm::MachineOperand::print(), remangleIntrinsicFunction(), llvm::AMDGPULowerKernelAttributesPass::run(), llvm::JumpThreadingPass::runImpl(), llvm::ScalarEvolution::ScalarEvolution(), splitGlobals(), unswitchBestCondition(), and UpgradeIntrinsicFunction1().
getName() [2/2]
std::string llvm::Intrinsic::getName (ID id, ArrayRef< Type * > Tys)
Return the LLVM name for an intrinsic, such as "llvm.ppc.altivec.lvx".
Note, this version of getName supports overloads, but is less efficient than the StringRef version of this function. If no overloads are requried, it is safe to use this version, but better to use the StringRef version.
Definition at line 785 of file Function.cpp.
References assert(), llvm::ArrayRef< T >::empty(), getMangledTypeStr(), IntrinsicNameTable, isOverloaded(), and num_intrinsics.
getType()
FunctionType * llvm::Intrinsic::getType (LLVMContext & Context, ID id, ArrayRef< Type * > Tys = None)
Return the function type for an intrinsic.
Definition at line 1208 of file Function.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), DecodeFixedType(), llvm::SmallVectorBase< Size_T >::empty(), llvm::FunctionType::get(), getIntrinsicInfoTableEntries(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by LLVMIntrinsicGetType().
isLeaf()
bool llvm::Intrinsic::isLeaf (ID id)
Returns true if the intrinsic is a leaf, i.e.
it does not make any calls itself. Most intrinsics are leafs, the exceptions being the patchpoint and statepoint intrinsics. These call (or invoke) their "target" argument.
Definition at line 1235 of file Function.cpp.
References experimental_gc_statepoint, experimental_patchpoint_i64, and experimental_patchpoint_void.
Referenced by llvm::CallGraphNode::addCalledFunction(), buildCGN(), DeleteBasicBlock(), and llvm::CallGraph::populateCallGraphNode().
isOverloaded()
bool llvm::Intrinsic::isOverloaded (ID id)
Returns true if the intrinsic can be overloaded.
Definition at line 1229 of file Function.cpp.
Referenced by getName(), getName(), LLVMIntrinsicIsOverloaded(), and llvm::Function::lookupIntrinsicID().
lookupLLVMIntrinsicByName()
int llvm::Intrinsic::lookupLLVMIntrinsicByName (ArrayRef< const char * > NameTable, StringRef Name)
Looks up Name in NameTable via binary search.
NameTable must be sorted and all entries must start with "llvm.". If NameTable contains an exact match for Name or a prefix of Name followed by a dot, its index in NameTable is returned. Otherwise, -1 is returned.
Definition at line 61 of file IntrinsicInst.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), High, Name, llvm::StringRef::npos, and llvm::StringRef::size().
Referenced by isCoroutineIntrinsicName(), and llvm::Function::lookupIntrinsicID().
matchIntrinsicSignature()
Intrinsic::MatchIntrinsicTypesResult llvm::Intrinsic::matchIntrinsicSignature (FunctionType * FTy, ArrayRef< IITDescriptor > & Infos, SmallVectorImpl< Type * > & ArgTys)
Match the specified function type with the type constraints specified by the .td file.
If the given type is an overloaded type it is pushed to the ArgTys vector.
Returns false if the given type matches with the constraints, true otherwise.
Definition at line 1496 of file Function.cpp.
References E, llvm::FunctionType::getReturnType(), I, matchIntrinsicType(), MatchIntrinsicTypes_Match, MatchIntrinsicTypes_NoMatchArg, MatchIntrinsicTypes_NoMatchRet, llvm::FunctionType::params(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by getIntrinsicSignature().
matchIntrinsicVarArg()
bool llvm::Intrinsic::matchIntrinsicVarArg (bool isVarArg, ArrayRef< IITDescriptor > & Infos)
Verify if the intrinsic has variable arguments.
This method is intended to be called after all the fixed arguments have been matched first.
This method returns true on error.
Definition at line 1522 of file Function.cpp.
References D, llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by getIntrinsicSignature().
remangleIntrinsicFunction()
Optional< Function * > llvm::Intrinsic::remangleIntrinsicFunction (Function * F)
Definition at line 1562 of file Function.cpp.
References assert(), F, getDeclaration(), getIntrinsicSignature(), getName(), Name, and llvm::None.
Referenced by UpgradeIntrinsicFunction1().
Variable Documentation
NoAliasScopeDeclScopeArg
const int llvm::Intrinsic::NoAliasScopeDeclScopeArg = 0 static
Definition at line 38 of file Intrinsics.h.
Referenced by llvm::NoAliasScopeDeclInst::getScopeList(), and llvm::NoAliasScopeDeclInst::setScopeList().