LLVM: lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp File Reference
NVPTXTargetTransformInfo.cpp File Reference
#include "NVPTXTargetTransformInfo.h"
#include "NVPTXUtilities.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "NVPTXtti"
Functions
static bool readsThreadIndex (const IntrinsicInst *II)
static bool readsLaneId (const IntrinsicInst *II)
static bool isNVVMAtomic (const IntrinsicInst *II)
static Instruction * simplifyNvvmIntrinsic (IntrinsicInst *II, InstCombiner &IC)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "NVPTXtti"
Definition at line 21 of file NVPTXTargetTransformInfo.cpp.
Function Documentation
isNVVMAtomic()
static bool isNVVMAtomic (const IntrinsicInst * II) static
Definition at line 39 of file NVPTXTargetTransformInfo.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().
readsLaneId()
static bool readsLaneId (const IntrinsicInst * II) static
Definition at line 34 of file NVPTXTargetTransformInfo.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().
readsThreadIndex()
static bool readsThreadIndex (const IntrinsicInst * II) static
Definition at line 24 of file NVPTXTargetTransformInfo.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by llvm::NVPTXTTIImpl::isSourceOfDivergence().
simplifyNvvmIntrinsic()
static Instruction * simplifyNvvmIntrinsic (IntrinsicInst * II, InstCombiner & IC) static
Definition at line 115 of file NVPTXTargetTransformInfo.cpp.
References llvm::CallBase::arg_operands(), llvm::Intrinsic::ceil, llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::Intrinsic::fabs, llvm::Intrinsic::floor, llvm::Intrinsic::fma, llvm::ConstantFP::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Function::getFnAttribute(), llvm::Instruction::getFunction(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Value::getType(), llvm::Attribute::getValueAsString(), llvm::DenormalMode::IEEE, llvm_unreachable, llvm::Intrinsic::maxnum, llvm::Intrinsic::minnum, llvm::parseDenormalFPAttribute(), llvm::Intrinsic::round, llvm::Intrinsic::sqrt, and llvm::Intrinsic::trunc.
Referenced by llvm::NVPTXTTIImpl::instCombineIntrinsic().