LLVM: lib/Transforms/ObjCARC/ObjCARCContract.cpp File Reference
ObjCARCContract.cpp File Reference
This file defines late ObjC ARC optimizations.
#include "ARCRuntimeEntryPoints.h"
#include "DependencyAnalysis.h"
#include "ObjCARC.h"
#include "ProvenanceAnalysis.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/ObjCARC.h"
Macros
#define DEBUG_TYPE "objc-arc-contract"
Functions
STATISTIC (NumPeeps, "Number of calls peephole-optimized")
STATISTIC (NumStoreStrongs, "Number objc_storeStrong calls formed")
static StoreInst * findSafeStoreForStoreStrongContraction (LoadInst *Load, Instruction *Release, ProvenanceAnalysis &PA, AAResults *AA)
static Instruction * findRetainForStoreStrongContraction (Value *New, StoreInst *Store, Instruction *Release, ProvenanceAnalysis &PA)
static CallInst * createCallInst (FunctionType *FTy, Value *Func, ArrayRef< Value * > Args, const Twine &NameStr, Instruction *InsertBefore, const DenseMap< BasicBlock *, ColorVector > &BlockColors)
Create a call instruction with the correct funclet token.
static CallInst * createCallInst (FunctionCallee Func, ArrayRef< Value * > Args, const Twine &NameStr, Instruction *InsertBefore, const DenseMap< BasicBlock *, ColorVector > &BlockColors)
INITIALIZE_PASS_BEGIN (ObjCARCContractLegacyPass, "objc-arc-contract", "ObjC ARC contraction", false, false) INITIALIZE_PASS_END(ObjCARCContractLegacyPass
Variables
objc arc contract
objc arc ObjC ARC contraction
objc arc ObjC ARC false
Detailed Description
This file defines late ObjC ARC optimizations.
ARC stands for Automatic Reference Counting and is a system for managing reference counts for objects in Objective C.
This specific file mainly deals with `‘contracting’' multiple lower level operations into singular higher level operations through pattern matching.
WARNING: This file knows about certain library functions. It recognizes them by name, and hardwires knowledge of their semantics.
WARNING: This file knows about how certain Objective-C library functions are used. Naive LLVM IR transformations which would otherwise be behavior-preserving may break these assumptions.
Definition in file ObjCARCContract.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "objc-arc-contract"
Definition at line 49 of file ObjCARCContract.cpp.
Function Documentation
createCallInst() [1/2]
static CallInst * createCallInst (FunctionCallee Func, ArrayRef< Value * > Args, const Twine & NameStr, Instruction * InsertBefore, const DenseMap< BasicBlock *, ColorVector > & BlockColors) static
Definition at line 326 of file ObjCARCContract.cpp.
References createCallInst().
createCallInst() [2/2]
static CallInst * createCallInst (FunctionType * FTy, Value * Func, ArrayRef< Value * > Args, const Twine & NameStr, Instruction * InsertBefore, const DenseMap< BasicBlock *, ColorVector > & BlockColors) static
Create a call instruction with the correct funclet token.
Should be used instead of calling CallInst::Create directly.
Definition at line 310 of file ObjCARCContract.cpp.
References assert(), llvm::CallInst::Create(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::TinyPtrVector< EltTy >::front(), llvm::Instruction::getParent(), llvm::Instruction::isEHPad(), and llvm::TinyPtrVector< EltTy >::size().
Referenced by createCallInst().
findRetainForStoreStrongContraction()
static Instruction * findRetainForStoreStrongContraction (Value * New, StoreInst * Store, Instruction * Release, ProvenanceAnalysis & PA) static
Definition at line 283 of file ObjCARCContract.cpp.
References llvm::objcarc::CanDecrementRefCount(), llvm::objcarc::GetArgRCIdentityRoot(), llvm::objcarc::GetBasicARCInstKind(), I, llvm::Release, and Retain.
findSafeStoreForStoreStrongContraction()
static StoreInst * findSafeStoreForStoreStrongContraction (LoadInst * Load, Instruction * Release, ProvenanceAnalysis & PA, AAResults * AA) static
Definition at line 196 of file ObjCARCContract.cpp.
References llvm::objcarc::CanUse(), llvm::dyn_cast(), E, llvm::MemoryLocation::get(), llvm::objcarc::GetBasicARCInstKind(), llvm::AAResults::getModRefInfo(), I, llvm::isModSet(), llvm::objcarc::IsRetain(), and llvm::Release.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ObjCARCContractLegacyPass , "objc-arc-contract" , "ObjC ARC contraction" , false , false)
STATISTIC() [1/2]
STATISTIC (NumPeeps , "Number of calls peephole-optimized")
STATISTIC() [2/2]
STATISTIC (NumStoreStrongs , "Number objc_storeStrong calls formed")
References Changed.
Variable Documentation
contract
objc arc contract
Definition at line 730 of file ObjCARCContract.cpp.
contraction
objc arc ObjC ARC contraction
Definition at line 731 of file ObjCARCContract.cpp.
false
objc arc ObjC ARC false
Definition at line 731 of file ObjCARCContract.cpp.