LLVM: lib/IR/OptBisect.cpp File Reference
OptBisect.cpp File Reference
This file implements support for a bisecting optimizations based on a command line option.
#include "llvm/IR/OptBisect.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <limits>
#include <string>
Functions
static void printPassMessage (const StringRef &Name, int PassNum, StringRef TargetDesc, bool Running)
Variables
static cl::opt< int > OptBisectLimit ("opt-bisect-limit", cl::Hidden, cl::init(std::numeric_limits< int >::max()), cl::Optional, cl::desc("Maximum optimization to perform"))
Detailed Description
This file implements support for a bisecting optimizations based on a command line option.
Definition in file OptBisect.cpp.
Function Documentation
printPassMessage()
static void printPassMessage (const StringRef & Name, int PassNum, StringRef TargetDesc, bool Running) static
Definition at line 35 of file OptBisect.cpp.
References llvm::errs(), and Name.
Referenced by llvm::OptBisect::checkPass().
Variable Documentation
OptBisectLimit
cl::opt< int > OptBisectLimit("opt-bisect-limit", cl::Hidden, cl::init(std::numeric_limits< int >::max()), cl::Optional, cl::desc("Maximum optimization to perform")) ("opt-bisect-limit" , cl::Hidden , cl::init(std::numeric_limits< int >::max()) , cl::Optional , cl::desc("Maximum optimization to perform")) static
Referenced by llvm::OptBisect::checkPass(), and llvm::OptBisect::OptBisect().