LLVM: lib/ExecutionEngine/Orc/OrcABISupport.cpp File Reference
OrcABISupport.cpp File Reference
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::orc
Macros
#define DEBUG_TYPE "orc"
Functions
template<typename ORCABI >
bool stubAndPointerRangesOk (JITTargetAddress StubBlockAddr, JITTargetAddress PointerBlockAddr, unsigned NumStubs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 14 of file OrcABISupport.cpp.
Function Documentation
stubAndPointerRangesOk()
template<typename ORCABI > bool stubAndPointerRangesOk (JITTargetAddress StubBlockAddr, JITTargetAddress PointerBlockAddr, unsigned NumStubs)
Definition at line 19 of file OrcABISupport.cpp.
Referenced by llvm::orc::OrcAArch64::writeIndirectStubsBlock(), llvm::orc::OrcI386::writeIndirectStubsBlock(), llvm::orc::OrcMips32_Base::writeIndirectStubsBlock(), llvm::orc::OrcMips64::writeIndirectStubsBlock(), and llvm::orc::OrcX86_64_Base::writeIndirectStubsBlock().