LLVM: lib/Transforms/IPO/PassManagerBuilder.cpp File Reference
PassManagerBuilder.cpp File Reference
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm-c/Transforms/PassManagerBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CFLAndersAliasAnalysis.h"
#include "llvm/Analysis/CFLSteensAliasAnalysis.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Transforms/AggressiveInstCombine/AggressiveInstCombine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/Attributor.h"
#include "llvm/Transforms/IPO/ForceFunctionAttrs.h"
#include "llvm/Transforms/IPO/FunctionAttrs.h"
#include "llvm/Transforms/IPO/InferFunctionAttrs.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/InstSimplifyPass.h"
#include "llvm/Transforms/Scalar/LICM.h"
#include "llvm/Transforms/Scalar/LoopUnrollPass.h"
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Vectorize.h"
#include "llvm/Transforms/Vectorize/LoopVectorize.h"
#include "llvm/Transforms/Vectorize/SLPVectorizer.h"
#include "llvm/Transforms/Vectorize/VectorCombine.h"
Enumerations
enum class CFLAAType { None , Steensgaard , Andersen , Both }
Functions
static bool GlobalExtensionsNotEmpty ()
Check if GlobalExtensions is constructed and not empty.
LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate ()
See llvm::PassManagerBuilder.
void LLVMPassManagerBuilderDispose (LLVMPassManagerBuilderRef PMB)
void LLVMPassManagerBuilderSetOptLevel (LLVMPassManagerBuilderRef PMB, unsigned OptLevel)
See llvm::PassManagerBuilder::OptLevel.
void LLVMPassManagerBuilderSetSizeLevel (LLVMPassManagerBuilderRef PMB, unsigned SizeLevel)
See llvm::PassManagerBuilder::SizeLevel.
void LLVMPassManagerBuilderSetDisableUnitAtATime (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnitAtATime.
void LLVMPassManagerBuilderSetDisableUnrollLoops (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableUnrollLoops.
void LLVMPassManagerBuilderSetDisableSimplifyLibCalls (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
See llvm::PassManagerBuilder::DisableSimplifyLibCalls.
void LLVMPassManagerBuilderUseInlinerWithThreshold (LLVMPassManagerBuilderRef PMB, unsigned Threshold)
See llvm::PassManagerBuilder::Inliner.
void LLVMPassManagerBuilderPopulateFunctionPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateFunctionPassManager.
void LLVMPassManagerBuilderPopulateModulePassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
See llvm::PassManagerBuilder::populateModulePassManager.
void LLVMPassManagerBuilderPopulateLTOPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM, LLVMBool Internalize, LLVMBool RunInliner)
See llvm::PassManagerBuilder::populateLTOPassManager.
Variables
cl::opt< bool > RunPartialInlining ("enable-partial-inlining", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("Run Partial inlinining pass"))
static cl::opt< bool > UseGVNAfterVectorization ("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes"))
cl::opt< bool > ExtraVectorizerPasses ("extra-vectorizer-passes", cl::init(false), cl::Hidden, cl::desc("Run cleanup optimization passes after vectorization."))
static cl::opt< bool > RunLoopRerolling ("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass"))
cl::opt< bool > RunNewGVN ("enable-newgvn", cl::init(false), cl::Hidden, cl::desc("Run the NewGVN pass"))
static cl::opt<::CFLAAType > UseCFLAA ("use-cfl-aa", cl::init(::CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis"), cl::values(clEnumValN(::CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(::CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(::CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(::CFLAAType::Both, "both", "Enable both variants of CFL-AA")))
static cl::opt< bool > EnableLoopInterchange ("enable-loopinterchange", cl::init(false), cl::Hidden, cl::desc("Enable the new, experimental LoopInterchange Pass"))
cl::opt< bool > EnableUnrollAndJam ("enable-unroll-and-jam", cl::init(false), cl::Hidden, cl::desc("Enable Unroll And Jam Pass"))
cl::opt< bool > EnableLoopFlatten ("enable-loop-flatten", cl::init(false), cl::Hidden, cl::desc("Enable the LoopFlatten Pass"))
static cl::opt< bool > EnablePrepareForThinLTO ("prepare-for-thinlto", cl::init(false), cl::Hidden, cl::desc("Enable preparation for ThinLTO."))
static cl::opt< bool > EnablePerformThinLTO ("perform-thinlto", cl::init(false), cl::Hidden, cl::desc("Enable performing ThinLTO."))
cl::opt< bool > EnableHotColdSplit ("hot-cold-split", cl::init(false), cl::ZeroOrMore, cl::desc("Enable hot-cold splitting pass"))
cl::opt< bool > EnableIROutliner ("ir-outliner", cl::init(false), cl::Hidden, cl::desc("Enable ir outliner pass"))
static cl::opt< bool > UseLoopVersioningLICM ("enable-loop-versioning-licm", cl::init(false), cl::Hidden, cl::desc("Enable the experimental Loop Versioning LICM pass"))
cl::opt< bool > DisablePreInliner ("disable-preinline", cl::init(false), cl::Hidden, cl::desc("Disable pre-instrumentation inliner"))
cl::opt< int > PreInlineThreshold ("preinline-threshold", cl::Hidden, cl::init(75), cl::ZeroOrMore, cl::desc("Control the amount of inlining in pre-instrumentation inliner " "(default = 75)"))
cl::opt< bool > EnableGVNHoist ("enable-gvn-hoist", cl::init(false), cl::ZeroOrMore, cl::desc("Enable the GVN hoisting pass (default = off)"))
static cl::opt< bool > DisableLibCallsShrinkWrap ("disable-libcalls-shrinkwrap", cl::init(false), cl::Hidden, cl::desc("Disable shrink-wrap library calls"))
static cl::opt< bool > EnableSimpleLoopUnswitch ("enable-simple-loop-unswitch", cl::init(false), cl::Hidden, cl::desc("Enable the simple loop unswitch pass. Also enables independent " "cleanup passes integrated into the loop pass manager pipeline."))
cl::opt< bool > EnableGVNSink ("enable-gvn-sink", cl::init(false), cl::ZeroOrMore, cl::desc("Enable the GVN sinking pass (default = off)"))
cl::opt< bool > EnableCHR ("enable-chr", cl::init(true), cl::Hidden, cl::desc("Enable control height reduction optimization (CHR)"))
cl::opt< bool > FlattenedProfileUsed ("flattened-profile-used", cl::init(false), cl::Hidden, cl::desc("Indicate the sample profile being used is flattened, i.e., " "no inline hierachy exists in the profile. "))
cl::opt< bool > EnableOrderFileInstrumentation ("enable-order-file-instrumentation", cl::init(false), cl::Hidden, cl::desc("Enable order file instrumentation (default = off)"))
cl::opt< bool > EnableMatrix ("enable-matrix", cl::init(false), cl::Hidden, cl::desc("Enable lowering of the matrix intrinsics"))
cl::opt< bool > EnableConstraintElimination ("enable-constraint-elimination", cl::init(false), cl::Hidden, cl::desc("Enable pass to eliminate conditions based on linear constraints."))
cl::opt< AttributorRunOption > AttributorRun ("attributor-enable", cl::Hidden, cl::init(AttributorRunOption::NONE), cl::desc("Enable the attributor inter-procedural deduction pass."), cl::values(clEnumValN(AttributorRunOption::ALL, "all", "enable all attributor runs"), clEnumValN(AttributorRunOption::MODULE, "module", "enable module-wide attributor runs"), clEnumValN(AttributorRunOption::CGSCC, "cgscc", "enable call graph SCC attributor runs"), clEnumValN(AttributorRunOption::NONE, "none", "disable attributor runs")))
cl::opt< bool > EnableKnowledgeRetention
static ManagedStatic< SmallVector< std::tuple< PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn, PassManagerBuilder::GlobalExtensionID >, 8 > > GlobalExtensions
Set of global extensions, automatically added as part of the standard set.
static PassManagerBuilder::GlobalExtensionID GlobalExtensionsCounter
Enumeration Type Documentation
CFLAAType
enum class CFLAAType strong
Enumerator
None
Steensgaard
Andersen
Both
Definition at line 75 of file PassManagerBuilder.cpp.
Function Documentation
GlobalExtensionsNotEmpty()
static bool GlobalExtensionsNotEmpty () static
Check if GlobalExtensions is constructed and not empty.
Since GlobalExtensions is a managed static, calling 'empty()' will trigger the construction of the object.
Definition at line 230 of file PassManagerBuilder.cpp.
References GlobalExtensions.
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
Variable Documentation
AttributorRun
cl::opt< AttributorRunOption > AttributorRun("attributor-enable", cl::Hidden, cl::init(AttributorRunOption::NONE), cl::desc("Enable the attributor inter-procedural deduction pass."), cl::values(clEnumValN(AttributorRunOption::ALL, "all", "enable all attributor runs"), clEnumValN(AttributorRunOption::MODULE, "module", "enable module-wide attributor runs"), clEnumValN(AttributorRunOption::CGSCC, "cgscc", "enable call graph SCC attributor runs"), clEnumValN(AttributorRunOption::NONE, "none", "disable attributor runs"))) ("attributor-enable" , cl::Hidden , cl::init(AttributorRunOption::NONE) , cl::desc("Enable the attributor inter-procedural deduction pass.") , cl::values(clEnumValN(AttributorRunOption::ALL, "all", "enable all attributor runs"), clEnumValN(AttributorRunOption::MODULE, "module", "enable module-wide attributor runs"), clEnumValN(AttributorRunOption::CGSCC, "cgscc", "enable call graph SCC attributor runs"), clEnumValN(AttributorRunOption::NONE, "none", "disable attributor runs")))
DisableLibCallsShrinkWrap
cl::opt< bool > DisableLibCallsShrinkWrap("disable-libcalls-shrinkwrap", cl::init(false), cl::Hidden, cl::desc("Disable shrink-wrap library calls")) ("disable-libcalls-shrinkwrap" , cl::init(false) , cl::Hidden , cl::desc("Disable shrink-wrap library calls")) static
DisablePreInliner
cl::opt< bool > DisablePreInliner("disable-preinline", cl::init(false), cl::Hidden, cl::desc("Disable pre-instrumentation inliner")) ("disable-preinline" , cl::init(false) , cl::Hidden , cl::desc("Disable pre-instrumentation inliner"))
EnableCHR
cl::opt< bool > EnableCHR("enable-chr", cl::init(true), cl::Hidden, cl::desc("Enable control height reduction optimization (CHR)")) ("enable-chr" , cl::init(true) , cl::Hidden , cl::desc("Enable control height reduction optimization (CHR)"))
EnableConstraintElimination
cl::opt< bool > EnableConstraintElimination("enable-constraint-elimination", cl::init(false), cl::Hidden, cl::desc("Enable pass to eliminate conditions based on linear constraints.")) ("enable-constraint-elimination" , cl::init(false) , cl::Hidden , cl::desc("Enable pass to eliminate conditions based on linear constraints."))
EnableGVNHoist
cl::opt< bool > EnableGVNHoist("enable-gvn-hoist", cl::init(false), cl::ZeroOrMore, cl::desc("Enable the GVN hoisting pass (default = off)")) ("enable-gvn-hoist" , cl::init(false) , cl::ZeroOrMore , cl::desc("Enable the GVN hoisting pass (default = off)"))
EnableGVNSink
cl::opt< bool > EnableGVNSink("enable-gvn-sink", cl::init(false), cl::ZeroOrMore, cl::desc("Enable the GVN sinking pass (default = off)")) ("enable-gvn-sink" , cl::init(false) , cl::ZeroOrMore , cl::desc("Enable the GVN sinking pass (default = off)"))
EnableHotColdSplit
cl::opt< bool > EnableHotColdSplit("hot-cold-split", cl::init(false), cl::ZeroOrMore, cl::desc("Enable hot-cold splitting pass")) ("hot-cold-split" , cl::init(false) , cl::ZeroOrMore , cl::desc("Enable hot-cold splitting pass"))
EnableIROutliner
cl::opt< bool > EnableIROutliner("ir-outliner", cl::init(false), cl::Hidden, cl::desc("Enable ir outliner pass")) ("ir-outliner" , cl::init(false) , cl::Hidden , cl::desc("Enable ir outliner pass"))
EnableKnowledgeRetention
cl::opt<bool> EnableKnowledgeRetention extern
EnableLoopFlatten
cl::opt< bool > EnableLoopFlatten("enable-loop-flatten", cl::init(false), cl::Hidden, cl::desc("Enable the LoopFlatten Pass")) ("enable-loop-flatten" , cl::init(false) , cl::Hidden , cl::desc("Enable the LoopFlatten Pass"))
EnableLoopInterchange
cl::opt< bool > EnableLoopInterchange("enable-loopinterchange", cl::init(false), cl::Hidden, cl::desc("Enable the new, experimental LoopInterchange Pass")) ("enable-loopinterchange" , cl::init(false) , cl::Hidden , cl::desc("Enable the new, experimental LoopInterchange Pass")) static
EnableMatrix
cl::opt< bool > EnableMatrix("enable-matrix", cl::init(false), cl::Hidden, cl::desc("Enable lowering of the matrix intrinsics")) ("enable-matrix" , cl::init(false) , cl::Hidden , cl::desc("Enable lowering of the matrix intrinsics"))
EnableOrderFileInstrumentation
cl::opt< bool > EnableOrderFileInstrumentation("enable-order-file-instrumentation", cl::init(false), cl::Hidden, cl::desc("Enable order file instrumentation (default = off)")) ("enable-order-file-instrumentation" , cl::init(false) , cl::Hidden , cl::desc("Enable order file instrumentation (default = off)"))
EnablePerformThinLTO
cl::opt< bool > EnablePerformThinLTO("perform-thinlto", cl::init(false), cl::Hidden, cl::desc("Enable performing ThinLTO.")) ("perform-thinlto" , cl::init(false) , cl::Hidden , cl::desc("Enable performing ThinLTO.")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
EnablePrepareForThinLTO
cl::opt< bool > EnablePrepareForThinLTO("prepare-for-thinlto", cl::init(false), cl::Hidden, cl::desc("Enable preparation for ThinLTO.")) ("prepare-for-thinlto" , cl::init(false) , cl::Hidden , cl::desc("Enable preparation for ThinLTO.")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
EnableSimpleLoopUnswitch
cl::opt< bool > EnableSimpleLoopUnswitch("enable-simple-loop-unswitch", cl::init(false), cl::Hidden, cl::desc("Enable the simple loop unswitch pass. Also enables independent " "cleanup passes integrated into the loop pass manager pipeline.")) ("enable-simple-loop-unswitch" , cl::init(false) , cl::Hidden , cl::desc("Enable the simple loop unswitch pass. Also enables independent " "cleanup passes integrated into the loop pass manager pipeline.")) static
EnableUnrollAndJam
cl::opt< bool > EnableUnrollAndJam("enable-unroll-and-jam", cl::init(false), cl::Hidden, cl::desc("Enable Unroll And Jam Pass")) ("enable-unroll-and-jam" , cl::init(false) , cl::Hidden , cl::desc("Enable Unroll And Jam Pass"))
ExtraVectorizerPasses
cl::opt< bool > ExtraVectorizerPasses("extra-vectorizer-passes", cl::init(false), cl::Hidden, cl::desc("Run cleanup optimization passes after vectorization.")) ("extra-vectorizer-passes" , cl::init(false) , cl::Hidden , cl::desc("Run cleanup optimization passes after vectorization."))
FlattenedProfileUsed
cl::opt< bool > FlattenedProfileUsed("flattened-profile-used", cl::init(false), cl::Hidden, cl::desc("Indicate the sample profile being used is flattened, i.e., " "no inline hierachy exists in the profile. ")) ("flattened-profile-used" , cl::init(false) , cl::Hidden , cl::desc("Indicate the sample profile being used is flattened, i.e., " "no inline hierachy exists in the profile. "))
GlobalExtensions
ManagedStatic< SmallVector<std::tuple<PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn, PassManagerBuilder::GlobalExtensionID>, 8> > GlobalExtensions static
Set of global extensions, automatically added as part of the standard set.
Definition at line 224 of file PassManagerBuilder.cpp.
Referenced by llvm::PassManagerBuilder::addGlobalExtension(), GlobalExtensionsNotEmpty(), and llvm::PassManagerBuilder::removeGlobalExtension().
GlobalExtensionsCounter
PassManagerBuilder::GlobalExtensionID GlobalExtensionsCounter static
Definition at line 225 of file PassManagerBuilder.cpp.
Referenced by llvm::PassManagerBuilder::addGlobalExtension().
PreInlineThreshold
cl::opt< int > PreInlineThreshold("preinline-threshold", cl::Hidden, cl::init(75), cl::ZeroOrMore, cl::desc("Control the amount of inlining in pre-instrumentation inliner " "(default = 75)")) ("preinline-threshold" , cl::Hidden , cl::init(75) , cl::ZeroOrMore , cl::desc("Control the amount of inlining in pre-instrumentation inliner " "(default = 75)"))
RunLoopRerolling
cl::opt< bool > RunLoopRerolling("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass")) ("reroll-loops" , cl::Hidden , cl::desc("Run the loop rerolling pass")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
RunNewGVN
cl::opt< bool > RunNewGVN("enable-newgvn", cl::init(false), cl::Hidden, cl::desc("Run the NewGVN pass")) ("enable-newgvn" , cl::init(false) , cl::Hidden , cl::desc("Run the NewGVN pass"))
RunPartialInlining
cl::opt< bool > RunPartialInlining("enable-partial-inlining", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("Run Partial inlinining pass")) ("enable-partial-inlining" , cl::init(false) , cl::Hidden , cl::ZeroOrMore , cl::desc("Run Partial inlinining pass"))
UseCFLAA
cl::opt<::CFLAAType > UseCFLAA("use-cfl-aa", cl::init(::CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis"), cl::values(clEnumValN(::CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(::CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(::CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(::CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) ("use-cfl-aa" , cl::init(::CFLAAType::None) , cl::Hidden , cl::desc("Enable the new, experimental CFL alias analysis") , cl::values(clEnumValN(::CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(::CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(::CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(::CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) static
UseGVNAfterVectorization
cl::opt< bool > UseGVNAfterVectorization("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes")) ("use-gvn-after-vectorization" , cl::init(false) , cl::Hidden , cl::desc("Run GVN instead of Early CSE after vectorization passes")) static
UseLoopVersioningLICM
cl::opt< bool > UseLoopVersioningLICM("enable-loop-versioning-licm", cl::init(false), cl::Hidden, cl::desc("Enable the experimental Loop Versioning LICM pass")) ("enable-loop-versioning-licm" , cl::init(false) , cl::Hidden , cl::desc("Enable the experimental Loop Versioning LICM pass")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().