LLVM: lib/CodeGen/PostRASchedulerList.cpp File Reference
PostRASchedulerList.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/AntiDepBreaker.h"
#include "llvm/CodeGen/LatencyPriorityQueue.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/ScheduleDAGInstrs.h"
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "post-RA-sched"
Functions
STATISTIC (NumNoops, "Number of noops inserted")
STATISTIC (NumStalls, "Number of pipeline stalls")
STATISTIC (NumFixedAnti, "Number of fixed anti-dependencies")
INITIALIZE_PASS (PostRAScheduler, DEBUG_TYPE, "Post RA top-down list latency scheduler", false, false) SchedulePostRATDList
Variables
static cl::opt< bool > EnablePostRAScheduler ("post-RA-scheduler", cl::desc("Enable scheduling after register allocation"), cl::init(false), cl::Hidden)
static cl::opt< std::string > EnableAntiDepBreaking ("break-anti-dependencies", cl::desc("Break post-RA scheduling anti-dependencies: " "\"critical\", \"all\", or \"none\""), cl::init("none"), cl::Hidden)
static cl::opt< int > DebugDiv ("postra-sched-debugdiv", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden)
static cl::opt< int > DebugMod ("postra-sched-debugmod", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "post-RA-sched"
Definition at line 46 of file PostRASchedulerList.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (PostRAScheduler , DEBUG_TYPE , "Post RA top-down list latency scheduler" , false , false)
Definition at line 201 of file PostRASchedulerList.cpp.
References assert(), llvm::createAggressiveAntiDepBreaker(), llvm::createCriticalAntiDepBreaker(), and MRI.
STATISTIC() [1/3]
STATISTIC (NumFixedAnti , "Number of fixed anti-dependencies")
STATISTIC() [2/3]
STATISTIC (NumNoops , "Number of noops inserted")
STATISTIC() [3/3]
STATISTIC (NumStalls , "Number of pipeline stalls")
Variable Documentation
DebugDiv
cl::opt< int > DebugDiv("postra-sched-debugdiv", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden) ("postra-sched-debugdiv" , cl::desc("Debug control MBBs that are scheduled") , cl::init(0) , cl::Hidden) static
DebugMod
cl::opt< int > DebugMod("postra-sched-debugmod", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden) ("postra-sched-debugmod" , cl::desc("Debug control MBBs that are scheduled") , cl::init(0) , cl::Hidden) static
EnableAntiDepBreaking
cl::opt< std::string > EnableAntiDepBreaking("break-anti-dependencies", cl::desc("Break post-RA scheduling anti-dependencies: " "\"critical\", \"all\", or \"none\""), cl::init("none"), cl::Hidden) ("break-anti-dependencies" , cl::desc("Break post-RA scheduling anti-dependencies: " "\"critical\", \"all\", or \"none\"") , cl::init("none") , cl::Hidden) static
EnablePostRAScheduler
cl::opt< bool > EnablePostRAScheduler("post-RA-scheduler", cl::desc("Enable scheduling after register allocation"), cl::init(false), cl::Hidden) ("post-RA-scheduler" , cl::desc("Enable scheduling after register allocation") , cl::init(false) , cl::Hidden) static