LLVM: lib/Transforms/IPO/PruneEH.cpp File Reference
PruneEH.cpp File Reference
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/CallGraphUpdater.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "prune-eh"
Functions
STATISTIC (NumRemoved, "Number of invokes removed")
STATISTIC (NumUnreach, "Number of noreturn calls optimized")
static bool SimplifyFunction (Function *F, CallGraphUpdater &CGU)
static void DeleteBasicBlock (BasicBlock *BB, CallGraphUpdater &CGU)
DeleteBasicBlock - remove the specified basic block from the program, updating the callgraph to reflect any now-obsolete edges due to calls that exist in the BB.
INITIALIZE_PASS_BEGIN (PruneEH, "prune-eh", "Remove unused exception handling info", false, false) INITIALIZE_PASS_END(PruneEH
static bool runImpl (CallGraphUpdater &CGU, SetVector< Function * > &Functions)
Variables
prune eh
prune Remove unused exception handling info
prune Remove unused exception handling false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "prune-eh"
Definition at line 37 of file PruneEH.cpp.
Function Documentation
DeleteBasicBlock()
static void DeleteBasicBlock (BasicBlock * BB, CallGraphUpdater & CGU) static
DeleteBasicBlock - remove the specified basic block from the program, updating the callgraph to reflect any now-obsolete edges due to calls that exist in the BB.
Definition at line 227 of file PruneEH.cpp.
References assert(), llvm::BasicBlock::begin(), Call, Callee, llvm::changeToUnreachable(), llvm::dyn_cast(), E, llvm::BasicBlock::end(), llvm::BasicBlock::eraseFromParent(), llvm::UndefValue::get(), llvm::CallBase::getCalledFunction(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), I, llvm::Intrinsic::isLeaf(), llvm::Instruction::isTerminator(), llvm::pred_empty(), llvm::CallGraphUpdater::removeCallSite(), llvm::succ_begin(), and llvm::succ_end().
Referenced by SimplifyFunction().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PruneEH , "prune-eh" , "Remove unused exception handling info" , false , false)
runImpl()
static bool runImpl (CallGraphUpdater & CGU, SetVector< Function * > & Functions) static
Definition at line 65 of file PruneEH.cpp.
References assert(), Callee, llvm::SetVector< T, Vector, Set >::contains(), llvm::dyn_cast(), F, I, llvm::isa(), llvm::Instruction::mayThrow(), and SimplifyFunction().
SimplifyFunction()
static bool SimplifyFunction (Function * F, CallGraphUpdater & CGU) static
Definition at line 184 of file PruneEH.cpp.
References llvm::canSimplifyInvokeNoUnwind(), DeleteBasicBlock(), llvm::dyn_cast(), E, F, I, llvm::isa(), llvm::pred_empty(), and llvm::removeUnwindEdge().
Referenced by runImpl().
STATISTIC() [1/2]
STATISTIC (NumRemoved , "Number of invokes removed")
STATISTIC() [2/2]
STATISTIC (NumUnreach , "Number of noreturn calls optimized")
Variable Documentation
eh
prune eh
Definition at line 60 of file PruneEH.cpp.
false
prune Remove unused exception handling false
Definition at line 61 of file PruneEH.cpp.
info
prune Remove unused exception handling info
Definition at line 61 of file PruneEH.cpp.