LLVM: lib/Transforms/Scalar/Reg2Mem.cpp File Reference
Reg2Mem.cpp File Reference
#include "llvm/Transforms/Scalar/Reg2Mem.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <list>
Macros
#define DEBUG_TYPE "reg2mem"
Functions
STATISTIC (NumRegsDemoted, "Number of registers demoted")
STATISTIC (NumPhisDemoted, "Number of phi-nodes demoted")
static bool valueEscapes (const Instruction &Inst)
static bool runPass (Function &F)
INITIALIZE_PASS_BEGIN (RegToMemLegacy, "reg2mem", "Demote all values to stack slots", false, false) INITIALIZE_PASS_END(RegToMemLegacy
Variables
reg2mem
Demote all values to stack slots
Demote all values to stack false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "reg2mem"
Definition at line 39 of file Reg2Mem.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (RegToMemLegacy , "reg2mem" , "Demote all values to stack slots" , false , false)
runPass()
static bool runPass (Function & F) static
Definition at line 54 of file Reg2Mem.cpp.
References assert(), llvm::BasicBlock::begin(), llvm::cast(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), F, llvm::Constant::getNullValue(), I, instructions, llvm::isa(), llvm::pred_empty(), and valueEscapes().
Referenced by llvm::RegToMemPass::run().
STATISTIC() [1/2]
STATISTIC (NumPhisDemoted , "Number of phi-nodes demoted")
STATISTIC() [2/2]
STATISTIC (NumRegsDemoted , "Number of registers demoted")
valueEscapes()
static bool valueEscapes (const Instruction & Inst) static
Definition at line 44 of file Reg2Mem.cpp.
References llvm::cast(), llvm::Instruction::getParent(), llvm::isa(), and llvm::Value::users().
Referenced by runPass().
Variable Documentation
false
Demote all values to stack false
Definition at line 135 of file Reg2Mem.cpp.
reg2mem
reg2mem
Definition at line 134 of file Reg2Mem.cpp.
slots
Demote all values to stack slots
Definition at line 135 of file Reg2Mem.cpp.