LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.h File Reference
RegisterEHFrames.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/TargetProcessControlTypes.h"
#include "llvm/Support/Error.h"
#include <vector>
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::orc
Functions
Error llvm::orc::registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Error llvm::orc::deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
llvm::orc::tpctypes::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (uint8_t *Data, uint64_t Size)
llvm::orc::tpctypes::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (uint8_t *Data, uint64_t Size)
Function Documentation
llvm_orc_deregisterEHFrameSectionWrapper()
llvm::orc::tpctypes::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (uint8_t * Data, uint64_t Size)
Definition at line 185 of file RegisterEHFrames.cpp.
References llvm::cantFail(), llvm::Data, llvm::orc::deregisterEHFrameSection(), llvm::jitTargetAddressToPointer(), llvm::BinaryStreamReader::readInteger(), llvm::orc::tpctypes::WrapperFunctionResult::release(), Size, and llvm::toString().
llvm_orc_registerEHFrameSectionWrapper()
llvm::orc::tpctypes::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (uint8_t * Data, uint64_t Size)
Definition at line 159 of file RegisterEHFrames.cpp.
References llvm::cantFail(), llvm::Data, llvm::jitTargetAddressToPointer(), llvm::BinaryStreamReader::readInteger(), llvm::orc::registerEHFrameSection(), llvm::orc::tpctypes::WrapperFunctionResult::release(), Size, and llvm::toString().