LLVM: lib/Target/RISCV/RISCVCleanupVSETVLI.cpp File Reference
RISCVCleanupVSETVLI.cpp File Reference
#include "RISCV.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "riscv-cleanup-vsetvli"
#define RISCV_CLEANUP_VSETVLI_NAME "RISCV Cleanup VSETVLI pass"
Functions
INITIALIZE_PASS (RISCVCleanupVSETVLI, DEBUG_TYPE, RISCV_CLEANUP_VSETVLI_NAME, false, false) bool RISCVCleanupVSETVLI
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-cleanup-vsetvli"
Definition at line 19 of file RISCVCleanupVSETVLI.cpp.
RISCV_CLEANUP_VSETVLI_NAME
#define RISCV_CLEANUP_VSETVLI_NAME "RISCV Cleanup VSETVLI pass"
Definition at line 20 of file RISCVCleanupVSETVLI.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVCleanupVSETVLI , DEBUG_TYPE , RISCV_CLEANUP_VSETVLI_NAME , false , false)
Definition at line 52 of file RISCVCleanupVSETVLI.cpp.
References llvm::MachineBasicBlock::begin(), Changed, llvm::MachineBasicBlock::end(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), if(), MBB, and MI.