LLVM: lib/Transforms/Utils/ScalarEvolutionExpander.cpp File Reference
ScalarEvolutionExpander.cpp File Reference
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Namespaces
namespace llvm
This class represents lattice values for constants.
Functions
static bool FactorOutConstant (const SCEV *&S, const SCEV *&Remainder, const SCEV *Factor, ScalarEvolution &SE, const DataLayout &DL)
FactorOutConstant - Test if S is divisible by Factor, using signed division.
static void SimplifyAddOperands (SmallVectorImpl< const SCEV * > &Ops, Type *Ty, ScalarEvolution &SE)
SimplifyAddOperands - Sort and simplify a list of add operands.
static void SplitAddRecs (SmallVectorImpl< const SCEV * > &Ops, Type *Ty, ScalarEvolution &SE)
SplitAddRecs - Flatten a list of add operands, moving addrec start values out to the top level.
static const Loop * PickMostRelevantLoop (const Loop *A, const Loop *B, DominatorTree &DT)
PickMostRelevantLoop - Given two loops pick the one that's most relevant for SCEV expansion.
static void ExposePointerBase (const SCEV *&Base, const SCEV *&Rest, ScalarEvolution &SE)
Move parts of Base into Rest to leave Base with the minimal expression that provides a pointer operand suitable for a GEP expansion.
static bool canBeCheaplyTransformed (ScalarEvolution &SE, const SCEVAddRecExpr *Phi, const SCEVAddRecExpr *Requested, bool &InvertStep)
Check whether we can cheaply express the requested SCEV in terms of the available PHI SCEV by truncation and/or inversion of the step.
static bool IsIncrementNSW (ScalarEvolution &SE, const SCEVAddRecExpr *AR)
static bool IsIncrementNUW (ScalarEvolution &SE, const SCEVAddRecExpr *AR)
template<typename T >
static int costAndCollectOperands (const SCEVOperand &WorkItem, const TargetTransformInfo &TTI, TargetTransformInfo::TargetCostKind CostKind, SmallVectorImpl< SCEVOperand > &Worklist)
bool llvm::isSafeToExpand (const SCEV *S, ScalarEvolution &SE)
Return true if the given expression is safe to expand in the sense that all materialized values are safe to speculate anywhere their operands are defined.
bool llvm::isSafeToExpandAt (const SCEV *S, const Instruction *InsertionPoint, ScalarEvolution &SE)
Return true if the given expression is safe to expand in the sense that all materialized values are defined and safe to speculate at the specified location and their operands are defined at this location.
Function Documentation
canBeCheaplyTransformed()
static bool canBeCheaplyTransformed (ScalarEvolution & SE, const SCEVAddRecExpr * Phi, const SCEVAddRecExpr * Requested, bool & InvertStep) static
Check whether we can cheaply express the requested SCEV in terms of the available PHI SCEV by truncation and/or inversion of the step.
Definition at line 1120 of file ScalarEvolutionExpander.cpp.
References llvm::dyn_cast(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::Type::getIntegerBitWidth(), llvm::ScalarEvolution::getNegativeSCEV(), llvm::SCEVAddRecExpr::getStart(), llvm::ScalarEvolution::getTruncateOrNoop(), and llvm::SCEVNAryExpr::getType().
costAndCollectOperands()
template<typename T > static int costAndCollectOperands (const SCEVOperand & WorkItem, const TargetTransformInfo & TTI, TargetTransformInfo::TargetCostKind CostKind, SmallVectorImpl< SCEVOperand > & Worklist) static
Definition at line 2182 of file ScalarEvolutionExpander.cpp.
References assert(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::cast(), CostKind, llvm::count_if(), llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm_unreachable, llvm::CmpInst::makeCmpResultType(), llvm::max(), llvm::min(), llvm::TargetTransformInfo::None, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, and llvm::scZeroExtend.
ExposePointerBase()
static void ExposePointerBase (const SCEV *& Base, const SCEV *& Rest, ScalarEvolution & SE) static
Move parts of Base into Rest to leave Base with the minimal expression that provides a pointer operand suitable for a GEP expansion.
Definition at line 902 of file ScalarEvolutionExpander.cpp.
References A, llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::dyn_cast(), ExposePointerBase(), llvm::SCEV::FlagNW, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), and llvm::ScalarEvolution::getConstant().
Referenced by ExposePointerBase().
FactorOutConstant()
static bool FactorOutConstant (const SCEV *& S, const SCEV *& Remainder, const SCEV * Factor, ScalarEvolution & SE, const DataLayout & DL) static
FactorOutConstant - Test if S is divisible by Factor, using signed division.
If so, update S with Factor divided out and return true. S need not be evenly divisible if a reasonable remainder can be computed.
Definition at line 269 of file ScalarEvolutionExpander.cpp.
References A, C, DL, llvm::dyn_cast(), FactorOutConstant(), llvm::SCEV::FlagNW, llvm::ConstantInt::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEV::getType(), llvm::SCEV::isOne(), llvm::ConstantInt::isZero(), and llvm::SCEV::isZero().
Referenced by FactorOutConstant().
IsIncrementNSW()
static bool IsIncrementNSW (ScalarEvolution & SE, const SCEVAddRecExpr * AR) static
Definition at line 1151 of file ScalarEvolutionExpander.cpp.
References llvm::BitWidth, llvm::cast(), llvm::IntegerType::get(), llvm::ScalarEvolution::getAddExpr(), llvm::Type::getContext(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVNAryExpr::getType(), and llvm::isa().
IsIncrementNUW()
static bool IsIncrementNUW (ScalarEvolution & SE, const SCEVAddRecExpr * AR) static
Definition at line 1165 of file ScalarEvolutionExpander.cpp.
References llvm::BitWidth, llvm::cast(), llvm::IntegerType::get(), llvm::ScalarEvolution::getAddExpr(), llvm::Type::getContext(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVNAryExpr::getType(), llvm::ScalarEvolution::getZeroExtendExpr(), and llvm::isa().
PickMostRelevantLoop()
static const Loop * PickMostRelevantLoop (const Loop * A, const Loop * B, DominatorTree & DT) static
PickMostRelevantLoop - Given two loops pick the one that's most relevant for SCEV expansion.
If they are nested, this is the most nested. If they are neighboring, pick the later.
Definition at line 632 of file ScalarEvolutionExpander.cpp.
References A, B, and llvm::DominatorTree::dominates().
SimplifyAddOperands()
static void SimplifyAddOperands (SmallVectorImpl< const SCEV * > & Ops, Type * Ty, ScalarEvolution & SE) static
SimplifyAddOperands - Sort and simplify a list of add operands.
NumAddRecs is the number of SCEVAddRecExprs present, which are kept at the end of the list.
Definition at line 342 of file ScalarEvolutionExpander.cpp.
References llvm::Add, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getConstant(), llvm::isa(), llvm::SCEV::isZero(), and Ops.
Referenced by SplitAddRecs().
SplitAddRecs()
static void SplitAddRecs (SmallVectorImpl< const SCEV * > & Ops, Type * Ty, ScalarEvolution & SE) static
SplitAddRecs - Flatten a list of add operands, moving addrec start values out to the top level.
For example, convert {a + b,+,c} to a, b, {0,+,d}. This helps expose more opportunities for folding parts of the expressions into GEP indices.
Definition at line 371 of file ScalarEvolutionExpander.cpp.
References A, llvm::Add, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SCEV::FlagNW, llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), Ops, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and SimplifyAddOperands().