LLVM: lib/Target/AMDGPU/SIFoldOperands.cpp File Reference
SIFoldOperands.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "si-fold-operands"
Functions
static unsigned macToMad (unsigned Opc)
static bool isInlineConstantIfFolded (const SIInstrInfo *TII, const MachineInstr &UseMI, unsigned OpNo, const MachineOperand &OpToFold)
static bool frameIndexMayFold (const SIInstrInfo *TII, const MachineInstr &UseMI, int OpNo, const MachineOperand &OpToFold)
static bool updateOperand (FoldCandidate &Fold, const SIInstrInfo &TII, const TargetRegisterInfo &TRI, const GCNSubtarget &ST)
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr *MI)
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *FoldOp, bool Commuted=false, int ShrinkOp=-1)
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *OpToFold, const SIInstrInfo *TII)
static bool isUseSafeToFold (const SIInstrInfo *TII, const MachineInstr &MI, const MachineOperand &UseMO)
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned > > &Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo *TII, const MachineRegisterInfo &MRI)
static bool tryToFoldACImm (const SIInstrInfo *TII, const MachineOperand &OpToFold, MachineInstr *UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > &FoldList)
static bool evalBinaryInstruction (unsigned Opcode, int32_t &Result, uint32_t LHS, uint32_t RHS)
static unsigned getMovOpc (bool IsScalar)
static void stripExtraCopyOperands (MachineInstr &MI)
Remove any leftover implicit operands from mutating the instruction.
static void mutateCopyOp (MachineInstr &MI, const MCInstrDesc &NewDesc)
static MachineOperand * getImmOrMaterializedImm (MachineRegisterInfo &MRI, MachineOperand &Op)
static bool tryConstantFoldOp (MachineRegisterInfo &MRI, const SIInstrInfo *TII, MachineInstr *MI, MachineOperand *ImmOp)
static bool tryFoldInst (const SIInstrInfo *TII, MachineInstr *MI)
static bool hasOneNonDBGUseInst (const MachineRegisterInfo &MRI, unsigned Reg)
static int getOModValue (unsigned Opc, int64_t Val)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-fold-operands"
Definition at line 18 of file SIFoldOperands.cpp.
Function Documentation
appendFoldCandidate()
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * FoldOp, bool Commuted = false, int ShrinkOp = -1) static
Definition at line 326 of file SIFoldOperands.cpp.
References llvm::dbgs(), LLVM_DEBUG, MI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by tryAddToFoldList(), and tryToFoldACImm().
evalBinaryInstruction()
static bool evalBinaryInstruction (unsigned Opcode, int32_t & Result, uint32_t LHS, uint32_t RHS) static
Definition at line 927 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp().
frameIndexMayFold()
static bool frameIndexMayFold (const SIInstrInfo * TII, const MachineInstr & UseMI, int OpNo, const MachineOperand & OpToFold) static
Definition at line 168 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineOperand::isFI(), TII, and UseMI.
getImmOrMaterializedImm()
static MachineOperand * getImmOrMaterializedImm (MachineRegisterInfo & MRI, MachineOperand & Op) static
Definition at line 1015 of file SIFoldOperands.cpp.
References llvm::MachineOperand::isImm(), and MRI.
Referenced by tryConstantFoldOp().
getMovOpc()
static unsigned getMovOpc (bool IsScalar) static
Definition at line 993 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp(), and tryFoldInst().
getOModValue()
static int getOModValue (unsigned Opc, int64_t Val) static
Definition at line 1383 of file SIFoldOperands.cpp.
References llvm::SIOutMods::DIV2, llvm_unreachable, llvm::SIOutMods::MUL2, llvm::SIOutMods::MUL4, and llvm::SIOutMods::NONE.
getRegSeqInit()
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned > > & Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo * TII, const MachineRegisterInfo & MRI) static
Definition at line 490 of file SIFoldOperands.cpp.
References assert(), E, llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), I, llvm::MachineOperand::isReg(), MRI, TII, and UseReg().
Referenced by tryToFoldACImm().
hasOneNonDBGUseInst()
static bool hasOneNonDBGUseInst (const MachineRegisterInfo & MRI, unsigned Reg) static
Definition at line 1346 of file SIFoldOperands.cpp.
References llvm::Count, E, I, and MRI.
isInlineConstantIfFolded()
static bool isInlineConstantIfFolded (const SIInstrInfo * TII, const MachineInstr & UseMI, unsigned OpNo, const MachineOperand & OpToFold) static
Definition at line 144 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), macToMad(), llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, TII, and UseMI.
isUseMIInFoldList()
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr * MI) static
Definition at line 317 of file SIFoldOperands.cpp.
References MI.
Referenced by tryAddToFoldList().
isUseSafeToFold()
static bool isUseSafeToFold (const SIInstrInfo * TII, const MachineInstr & MI, const MachineOperand & UseMO) static
Definition at line 469 of file SIFoldOperands.cpp.
References llvm::MachineOperand::isUndef(), MI, and TII.
macToMad()
static unsigned macToMad (unsigned Opc) static
Definition at line 126 of file SIFoldOperands.cpp.
Referenced by isInlineConstantIfFolded(), and tryAddToFoldList().
mutateCopyOp()
static void mutateCopyOp (MachineInstr & MI, const MCInstrDesc & NewDesc) static
Definition at line 1010 of file SIFoldOperands.cpp.
References MI, and stripExtraCopyOperands().
Referenced by tryConstantFoldOp(), and tryFoldInst().
stripExtraCopyOperands()
static void stripExtraCopyOperands (MachineInstr & MI) static
Remove any leftover implicit operands from mutating the instruction.
e.g. if we replace an s_and_b32 with a copy, we don't need the implicit scc def anymore.
Definition at line 1000 of file SIFoldOperands.cpp.
References llvm::MCInstrDesc::getNumImplicitDefs(), llvm::MCInstrDesc::getNumImplicitUses(), llvm::MCInstrDesc::getNumOperands(), I, and MI.
Referenced by mutateCopyOp(), and tryConstantFoldOp().
tryAddToFoldList()
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * OpToFold, const SIInstrInfo * TII) static
Definition at line 339 of file SIFoldOperands.cpp.
References appendFoldCandidate(), assert(), llvm::TargetInstrInfo::CommuteAnyOperandIndex, llvm::MCInstrDesc::getNumOperands(), llvm::MachineOperand::getReg(), llvm::AMDGPU::getVOPe32(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), isUseMIInFoldList(), macToMad(), MI, MRI, llvm::SIRegisterInfo::opCanUseInlineConstant(), llvm::MCInstrDesc::OpInfo, TII, and tryAddToFoldList().
Referenced by tryAddToFoldList().
tryConstantFoldOp()
static bool tryConstantFoldOp (MachineRegisterInfo & MRI, const SIInstrInfo * TII, MachineInstr * MI, MachineOperand * ImmOp) static
Definition at line 1036 of file SIFoldOperands.cpp.
References evalBinaryInstruction(), llvm::MachineOperand::getImm(), getImmOrMaterializedImm(), getMovOpc(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineOperand::isImm(), MI, MRI, mutateCopyOp(), stripExtraCopyOperands(), std::swap(), TII, and TRI.
tryFoldInst()
static bool tryFoldInst (const SIInstrInfo * TII, MachineInstr * MI) static
Definition at line 1137 of file SIFoldOperands.cpp.
References llvm::dbgs(), getMovOpc(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineOperand::isReg(), LLVM_DEBUG, MI, mutateCopyOp(), and TII.
tryToFoldACImm()
static bool tryToFoldACImm (const SIInstrInfo * TII, const MachineOperand & OpToFold, MachineInstr * UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > & FoldList) static
Definition at line 523 of file SIFoldOperands.cpp.
References llvm::any_of(), appendFoldCandidate(), llvm::MachineOperand::ChangeToImmediate(), E, llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegSeqInit(), I, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), MRI, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FIRST, llvm::AMDGPU::OPERAND_REG_INLINE_AC_LAST, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::SmallVectorBase< Size_T >::size(), TII, UseMI, and UseReg().
updateOperand()
static bool updateOperand (FoldCandidate & Fold, const SIInstrInfo & TII, const TargetRegisterInfo & TRI, const GCNSubtarget & ST) static
Definition at line 195 of file SIFoldOperands.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::dbgs(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), I, llvm::MachineOperand::isDef(), llvm::AMDGPU::isFoldableLiteralV216(), llvm::SIInstrFlags::IsMAI, llvm::SIInstrFlags::IsPacked, llvm::MachineOperand::isReg(), llvm::isUInt< 16 >(), llvm::RegState::Kill, LLVM_DEBUG, llvm::MachineBasicBlock::LQR_Dead, MBB, MI, llvm::Mod, MRI, llvm::SISrcMods::OP_SEL_0, llvm::SISrcMods::OP_SEL_1, llvm::AMDGPU::OPERAND_REG_IMM_V2FP16, llvm::AMDGPU::OPERAND_REG_IMM_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT16, llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), llvm::MachineOperand::substVirtReg(), TII, and TRI.