LLVM: lib/Support/SourceMgr.cpp File Reference
SourceMgr.cpp File Reference
#include "llvm/Support/SourceMgr.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/Locale.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <limits>
#include <memory>
#include <string>
#include <utility>
Functions
template<typename T >
static std::vector< T > & GetOrCreateOffsetCache (void *&OffsetCache, MemoryBuffer *Buffer)
static void buildFixItLine (std::string &CaretLine, std::string &FixItLine, ArrayRef< SMFixIt > FixIts, ArrayRef< char > SourceLine)
static void printSourceLine (raw_ostream &S, StringRef LineContents)
static bool isNonASCII (char c)
Variables
static const size_t TabStop = 8
Function Documentation
buildFixItLine()
static void buildFixItLine (std::string & CaretLine, std::string & FixItLine, ArrayRef< SMFixIt > FixIts, ArrayRef< char > SourceLine) static
Definition at line 378 of file SourceMgr.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::sys::locale::columnWidth(), llvm::copy(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), and llvm::StringRef::npos.
Referenced by llvm::SMDiagnostic::print().
GetOrCreateOffsetCache()
template<typename T > static std::vector< T > & GetOrCreateOffsetCache (void *& OffsetCache, MemoryBuffer * Buffer) static
Definition at line 72 of file SourceMgr.cpp.
References assert(), llvm::MemoryBuffer::getBuffer(), llvm::MemoryBuffer::getBufferSize(), and N.
isNonASCII()
static bool isNonASCII (char c) static
Definition at line 471 of file SourceMgr.cpp.
Referenced by llvm::SMDiagnostic::print().
printSourceLine()
static void printSourceLine (raw_ostream & S, StringRef LineContents) static
Definition at line 447 of file SourceMgr.cpp.
References llvm::StringRef::drop_front(), llvm::StringRef::find(), llvm::StringRef::npos, llvm::StringRef::size(), llvm::StringRef::slice(), and TabStop.
Referenced by llvm::SMDiagnostic::print().
Variable Documentation
TabStop
const size_t TabStop = 8 static
Definition at line 38 of file SourceMgr.cpp.
Referenced by llvm::SMDiagnostic::print(), and printSourceLine().