LLVM: lib/Target/Sparc/SparcRegisterInfo.cpp File Reference
SparcRegisterInfo.cpp File Reference
#include "SparcRegisterInfo.h"
#include "Sparc.h"
#include "SparcMachineFunctionInfo.h"
#include "SparcSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "SparcGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static void replaceFI (MachineFunction &MF, MachineBasicBlock::iterator II, MachineInstr &MI, const DebugLoc &dl, unsigned FIOperandNum, int Offset, unsigned FramePtr)
Variables
static cl::opt< bool > ReserveAppRegisters ("sparc-reserve-app-registers", cl::Hidden, cl::init(false), cl::desc("Reserve application registers (%g2-%g4)"))
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 29 of file SparcRegisterInfo.cpp.
Function Documentation
replaceFI()
static void replaceFI (MachineFunction & MF, MachineBasicBlock::iterator II, MachineInstr & MI, const DebugLoc & dl, unsigned FIOperandNum, int Offset, unsigned FramePtr) static
Definition at line 111 of file SparcRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), FramePtr, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), llvm::HI22(), llvm::HIX22(), llvm::LO10(), llvm::LOX10(), MI, Offset, and TII.
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex(), and llvm::VERegisterInfo::eliminateFrameIndex().
Variable Documentation
ReserveAppRegisters
cl::opt< bool > ReserveAppRegisters("sparc-reserve-app-registers", cl::Hidden, cl::init(false), cl::desc("Reserve application registers (%g2-%g4)")) ("sparc-reserve-app-registers" , cl::Hidden , cl::init(false) , cl::desc("Reserve application registers (%g2-%g4)")) static
Referenced by llvm::SparcRegisterInfo::getReservedRegs().