LLVM: lib/Transforms/Utils/StripGCRelocates.cpp File Reference
StripGCRelocates.cpp File Reference
#include "llvm/Transforms/Utils/StripGCRelocates.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool stripGCRelocates (Function &F)
Function Documentation
stripGCRelocates()
static bool stripGCRelocates (Function & F) static
Definition at line 28 of file StripGCRelocates.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::Value::getType(), I, instructions, llvm::isa(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::StripGCRelocates::run().