LLVM: llvm::TileInfo Struct Reference
llvm::TileInfo Struct Reference
A helper struct to create IR loop nests for tiling in IR of the following form: for CurrentColumn = 0..NumColumns for CurrentRow = 0..NumRows for CurrentInner = 0..NumInner.
#include "llvm/Transforms/Utils/MatrixUtils.h"
Public Member Functions
TileInfo (unsigned NumRows, unsigned NumColumns, unsigned NumInner, unsigned TileSize)
BasicBlock * CreateTiledLoops (BasicBlock *Start, BasicBlock *End, IRBuilderBase &B, DomTreeUpdater &DTU, LoopInfo &LI)
Creates an IR loop nests for tiling of the form below.
Public Attributes
unsigned NumRows
Number of rows of the matrix.
unsigned NumColumns
Number of columns of the matrix.
unsigned NumInner
Number of columns of the first matrix of a multiply / number of rows of the second matrix of a multiply.
unsigned TileSize = -1
Number of rows/columns in a tile.
Value * CurrentRow
Start row of the current tile to compute.
Value * CurrentCol
Start column of the current tile to compute.
Value * CurrentK
Current tile offset during the tile computation.
BasicBlock * ColumnLoopHeader = nullptr
Header of the outermost loop iterating from 0..NumColumns.
BasicBlock * RowLoopHeader = nullptr
Header of the second loop iterating from 0..NumRows.
BasicBlock * RowLoopLatch = nullptr
Latch of the second loop iterating from 0..NumRows.
BasicBlock * InnerLoopHeader = nullptr
Header of the innermost loop iterating from 0..NumInner.
BasicBlock * InnerLoopLatch = nullptr
Latch of the innermost loop iterating from 0..NumInner.
Detailed Description
A helper struct to create IR loop nests for tiling in IR of the following form: for CurrentColumn = 0..NumColumns for CurrentRow = 0..NumRows for CurrentInner = 0..NumInner.
Definition at line 31 of file MatrixUtils.h.
Constructor & Destructor Documentation
TileInfo()
llvm::TileInfo::TileInfo (unsigned NumRows, unsigned NumColumns, unsigned NumInner, unsigned TileSize) inline
Definition at line 66 of file MatrixUtils.h.
Member Function Documentation
CreateTiledLoops()
BasicBlock * TileInfo::CreateTiledLoops (BasicBlock * Start, BasicBlock * End, IRBuilderBase & B, DomTreeUpdater & DTU, LoopInfo & LI)
Creates an IR loop nests for tiling of the form below.
Returns the block for the inner loop body and sets {Column,Row,Inner}LoopHeader/Latch fields.
for CurrentColumn = 0..NumColumns for CurrentRow = 0..NumRows for CurrentInner = 0..NumInner
Definition at line 70 of file MatrixUtils.cpp.
References llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), B, llvm::BasicBlock::begin(), ColumnLoopHeader, CurrentCol, CurrentK, CurrentRow, llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getSingleSuccessor(), InnerLoopHeader, InnerLoopLatch, NumColumns, NumInner, NumRows, RowLoopHeader, RowLoopLatch, and TileSize.
Member Data Documentation
ColumnLoopHeader
BasicBlock* llvm::TileInfo::ColumnLoopHeader = nullptr
Header of the outermost loop iterating from 0..NumColumns.
Definition at line 55 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
CurrentCol
Value* llvm::TileInfo::CurrentCol
Start column of the current tile to compute.
Definition at line 49 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
CurrentK
Value* llvm::TileInfo::CurrentK
Current tile offset during the tile computation.
Definition at line 52 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
CurrentRow
Value* llvm::TileInfo::CurrentRow
Start row of the current tile to compute.
Definition at line 46 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
InnerLoopHeader
BasicBlock* llvm::TileInfo::InnerLoopHeader = nullptr
Header of the innermost loop iterating from 0..NumInner.
Definition at line 62 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
InnerLoopLatch
BasicBlock* llvm::TileInfo::InnerLoopLatch = nullptr
Latch of the innermost loop iterating from 0..NumInner.
Definition at line 64 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
NumColumns
unsigned llvm::TileInfo::NumColumns
Number of columns of the matrix.
Definition at line 36 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
NumInner
unsigned llvm::TileInfo::NumInner
Number of columns of the first matrix of a multiply / number of rows of the second matrix of a multiply.
Definition at line 40 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
NumRows
unsigned llvm::TileInfo::NumRows
Number of rows of the matrix.
Definition at line 33 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
RowLoopHeader
BasicBlock* llvm::TileInfo::RowLoopHeader = nullptr
Header of the second loop iterating from 0..NumRows.
Definition at line 58 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
RowLoopLatch
BasicBlock* llvm::TileInfo::RowLoopLatch = nullptr
Latch of the second loop iterating from 0..NumRows.
Definition at line 60 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
TileSize
unsigned llvm::TileInfo::TileSize = -1
Number of rows/columns in a tile.
Definition at line 43 of file MatrixUtils.h.
Referenced by CreateTiledLoops().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Utils/MatrixUtils.h
lib/Transforms/Utils/MatrixUtils.cpp