LLVM: llvm::ms_demangle::TypeNode Struct Reference
llvm::ms_demangle::TypeNode Struct Reference abstract
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
TypeNode (NodeKind K)
virtual void outputPre (OutputStream &OS, OutputFlags Flags) const =0
virtual void outputPost (OutputStream &OS, OutputFlags Flags) const =0
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
Qualifiers Quals = Q_None
Detailed Description
Definition at line 298 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
TypeNode()
llvm::ms_demangle::TypeNode::TypeNode (NodeKind K) inline explicit
Definition at line 299 of file MicrosoftDemangleNodes.h.
Member Function Documentation
output()
void llvm::ms_demangle::TypeNode::output (OutputStream & OS, OutputFlags Flags) const inline override virtual
Implements llvm::ms_demangle::Node.
Definition at line 304 of file MicrosoftDemangleNodes.h.
References outputPost(), and outputPre().
Referenced by llvm::ms_demangle::ConversionOperatorIdentifierNode::output().
outputPost()
virtual void llvm::ms_demangle::TypeNode::outputPost (OutputStream & OS, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::ArrayTypeNode, llvm::ms_demangle::CustomTypeNode, llvm::ms_demangle::FunctionSignatureNode, llvm::ms_demangle::PointerTypeNode, llvm::ms_demangle::PrimitiveTypeNode, llvm::ms_demangle::TagTypeNode, and llvm::ms_demangle::ThunkSignatureNode.
Referenced by output(), llvm::ms_demangle::ArrayTypeNode::outputPost(), llvm::ms_demangle::FunctionSignatureNode::outputPost(), and llvm::ms_demangle::PointerTypeNode::outputPost().
outputPre()
virtual void llvm::ms_demangle::TypeNode::outputPre (OutputStream & OS, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::ArrayTypeNode, llvm::ms_demangle::CustomTypeNode, llvm::ms_demangle::FunctionSignatureNode, llvm::ms_demangle::PointerTypeNode, llvm::ms_demangle::PrimitiveTypeNode, llvm::ms_demangle::TagTypeNode, and llvm::ms_demangle::ThunkSignatureNode.
Referenced by output(), llvm::ms_demangle::ArrayTypeNode::outputPre(), llvm::ms_demangle::FunctionSignatureNode::outputPre(), and llvm::ms_demangle::PointerTypeNode::outputPre().
Member Data Documentation
Quals
Qualifiers llvm::ms_demangle::TypeNode::Quals = Q_None
Definition at line 309 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::FunctionSignatureNode::outputPost(), llvm::ms_demangle::ArrayTypeNode::outputPre(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::ms_demangle::PrimitiveTypeNode::outputPre(), and llvm::ms_demangle::TagTypeNode::outputPre().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/MicrosoftDemangleNodes.h