LLVM: llvm::detail::zip_common< ZipType, Iters > Struct Template Reference
llvm::detail::zip_common< ZipType, Iters > Struct Template Reference
#include "llvm/ADT/STLExtras.h"
Public Types
using Base = zip_traits<ZipType, Iters...>
using value_type = typename Base::value_type
Public Member Functions
zip_common (Iters &&... ts)
value_type operator* ()
const value_type operator* () const
ZipType & operator++ ()
ZipType & operator-- ()
Public Member Functions inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
DerivedT operator+ (DifferenceTypeT n) const
DerivedT operator- (DifferenceTypeT n) const
DerivedT & operator++ ()
DerivedT operator++ (int)
DerivedT & operator-- ()
DerivedT operator-- (int)
bool operator!= (const DerivedT &RHS) const
bool operator> (const DerivedT &RHS) const
bool operator<= (const DerivedT &RHS) const
bool operator>= (const DerivedT &RHS) const
PointerT operator-> ()
PointerT operator-> () const
ReferenceProxy operator[] (DifferenceTypeT n)
ReferenceProxy operator[] (DifferenceTypeT n) const
Public Attributes
std::tuple< Iters... > iterators
Protected Member Functions
template<size_t... Ns>
value_type deref (std::index_sequence< Ns... >) const
template<size_t... Ns>
decltype(iterators) tup_inc (std::index_sequence< Ns... >) const
template<size_t... Ns>
decltype(iterators) tup_dec (std::index_sequence< Ns... >) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
enum { IsRandomAccess , IsBidirectional }
Detailed Description
template<typename ZipType, typename... Iters>
struct llvm::detail::zip_common< ZipType, Iters >
Definition at line 621 of file STLExtras.h.
Member Typedef Documentation
Base
template<typename ZipType , typename... Iters> using llvm::detail::zip_common< ZipType, Iters >::Base = zip_traits<ZipType, Iters...>
Definition at line 622 of file STLExtras.h.
value_type
template<typename ZipType , typename... Iters> using llvm::detail::zip_common< ZipType, Iters >::value_type = typename Base::value_type
Definition at line 623 of file STLExtras.h.
Constructor & Destructor Documentation
zip_common()
template<typename ZipType , typename... Iters> llvm::detail::zip_common< ZipType, Iters >::zip_common (Iters &&... ts) inline
Definition at line 643 of file STLExtras.h.
Member Function Documentation
deref()
template<typename ZipType , typename... Iters> template<size_t... Ns> value_type llvm::detail::zip_common< ZipType, Iters >::deref (std::index_sequence< Ns... >) const inline protected
Definition at line 628 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::iterators.
Referenced by llvm::detail::zip_common< ZipType, Iters >::operator*(), and llvm::detail::zip_common< ZipType, Iters >::operator*().
operator*() [1/2]
template<typename ZipType , typename... Iters> value_type llvm::detail::zip_common< ZipType, Iters >::operator* () inline
Definition at line 645 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::deref().
operator*() [2/2]
template<typename ZipType , typename... Iters> const value_type llvm::detail::zip_common< ZipType, Iters >::operator* () const inline
Definition at line 647 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::deref().
operator++()
template<typename ZipType , typename... Iters> ZipType & llvm::detail::zip_common< ZipType, Iters >::operator++ () inline
Definition at line 651 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::iterators, and llvm::detail::zip_common< ZipType, Iters >::tup_inc().
operator--()
template<typename ZipType , typename... Iters> ZipType & llvm::detail::zip_common< ZipType, Iters >::operator-- () inline
Definition at line 656 of file STLExtras.h.
References llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::IsBidirectional, llvm::detail::zip_common< ZipType, Iters >::iterators, and llvm::detail::zip_common< ZipType, Iters >::tup_dec().
tup_dec()
template<typename ZipType , typename... Iters> template<size_t... Ns> decltype(iterators) llvm::detail::zip_common< ZipType, Iters >::tup_dec (std::index_sequence< Ns... >) const inline protected
Definition at line 638 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::iterators.
Referenced by llvm::detail::zip_common< ZipType, Iters >::operator--().
tup_inc()
template<typename ZipType , typename... Iters> template<size_t... Ns> decltype(iterators) llvm::detail::zip_common< ZipType, Iters >::tup_inc (std::index_sequence< Ns... >) const inline protected
Definition at line 633 of file STLExtras.h.
References llvm::detail::zip_common< ZipType, Iters >::iterators.
Referenced by llvm::detail::zip_common< ZipType, Iters >::operator++().
Member Data Documentation
iterators
template<typename ZipType , typename... Iters> std::tuple<Iters...> llvm::detail::zip_common< ZipType, Iters >::iterators
Definition at line 625 of file STLExtras.h.
Referenced by llvm::detail::zip_common< ZipType, Iters >::deref(), llvm::detail::zip_common< ZipType, Iters >::operator++(), llvm::detail::zip_common< ZipType, Iters >::operator--(), llvm::detail::zip_first< Iters >::operator==(), llvm::detail::zip_common< ZipType, Iters >::tup_dec(), and llvm::detail::zip_common< ZipType, Iters >::tup_inc().
The documentation for this struct was generated from the following file:
include/llvm/ADT/STLExtras.h