LLVM: llvm::ms_demangle::ArrayTypeNode Struct Reference
llvm::ms_demangle::ArrayTypeNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
ArrayTypeNode ()
void outputPre (OutputStream &OS, OutputFlags Flags) const override
void outputPost (OutputStream &OS, OutputFlags Flags) const override
void outputDimensionsImpl (OutputStream &OS, OutputFlags Flags) const
void outputOneDimension (OutputStream &OS, OutputFlags Flags, Node *N) const
Public Member Functions inherited from llvm::ms_demangle::TypeNode
TypeNode (NodeKind K)
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
NodeArrayNode * Dimensions = nullptr
TypeNode * ElementType = nullptr
Public Attributes inherited from llvm::ms_demangle::TypeNode
Qualifiers Quals = Q_None
Detailed Description
Definition at line 484 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
ArrayTypeNode()
llvm::ms_demangle::ArrayTypeNode::ArrayTypeNode () inline
Definition at line 485 of file MicrosoftDemangleNodes.h.
Member Function Documentation
outputDimensionsImpl()
void ArrayTypeNode::outputDimensionsImpl (OutputStream & OS, OutputFlags Flags) const
Definition at line 555 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::NodeArrayNode::Count, Dimensions, I, llvm::ms_demangle::NodeArrayNode::Nodes, and outputOneDimension().
Referenced by outputPost().
outputOneDimension()
void ArrayTypeNode::outputOneDimension (OutputStream & OS, OutputFlags Flags, Node * N) const
Definition at line 547 of file MicrosoftDemangleNodes.cpp.
References assert(), llvm::ms_demangle::IntegerLiteral, N, llvm::ms_demangle::IntegerLiteralNode::output(), and llvm::ms_demangle::IntegerLiteralNode::Value.
Referenced by outputDimensionsImpl().
outputPost()
void ArrayTypeNode::outputPost (OutputStream & OS, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Definition at line 567 of file MicrosoftDemangleNodes.cpp.
References ElementType, outputDimensionsImpl(), and llvm::ms_demangle::TypeNode::outputPost().
outputPre()
void ArrayTypeNode::outputPre (OutputStream & OS, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Definition at line 542 of file MicrosoftDemangleNodes.cpp.
References ElementType, llvm::ms_demangle::TypeNode::outputPre(), outputQualifiers(), and llvm::ms_demangle::TypeNode::Quals.
Member Data Documentation
Dimensions
NodeArrayNode* llvm::ms_demangle::ArrayTypeNode::Dimensions = nullptr
Definition at line 494 of file MicrosoftDemangleNodes.h.
Referenced by outputDimensionsImpl().
ElementType
TypeNode* llvm::ms_demangle::ArrayTypeNode::ElementType = nullptr
Definition at line 497 of file MicrosoftDemangleNodes.h.
Referenced by outputPost(), and outputPre().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp