LLVM: llvm::ms_demangle::VariableSymbolNode Struct Reference
llvm::ms_demangle::VariableSymbolNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
VariableSymbolNode ()
void output (OutputStream &OS, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::SymbolNode
SymbolNode (NodeKind K)
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
StorageClass SC = StorageClass::None
TypeNode * Type = nullptr
Public Attributes inherited from llvm::ms_demangle::SymbolNode
QualifiedNameNode * Name = nullptr
Detailed Description
Definition at line 609 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
VariableSymbolNode()
llvm::ms_demangle::VariableSymbolNode::VariableSymbolNode () inline
Definition at line 610 of file MicrosoftDemangleNodes.h.
Member Function Documentation
output()
void VariableSymbolNode::output (OutputStream & OS, OutputFlags Flags) const override virtual
Reimplemented from llvm::ms_demangle::SymbolNode.
Definition at line 586 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::SymbolNode::Name, llvm::ms_demangle::OF_NoAccessSpecifier, llvm::ms_demangle::OF_NoMemberType, llvm::ms_demangle::QualifiedNameNode::output(), outputSpaceIfNecessary(), llvm::ms_demangle::PrivateStatic, llvm::ms_demangle::ProtectedStatic, llvm::ms_demangle::PublicStatic, and SC.
Referenced by llvm::ms_demangle::DynamicStructorIdentifierNode::output().
Member Data Documentation
SC
StorageClass llvm::ms_demangle::VariableSymbolNode::SC = StorageClass::None
Definition at line 614 of file MicrosoftDemangleNodes.h.
Referenced by output().
Type
TypeNode* llvm::ms_demangle::VariableSymbolNode::Type = nullptr
Definition at line 615 of file MicrosoftDemangleNodes.h.
Referenced by synthesizeVariable().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp