LLVM: llvm::lowertypetests::BitSetBuilder Struct Reference
llvm::lowertypetests::BitSetBuilder Struct Reference
#include "llvm/Transforms/IPO/LowerTypeTests.h"
Public Member Functions
BitSetBuilder ()=default
void addOffset (uint64_t Offset)
BitSetInfo build ()
Public Attributes
SmallVector< uint64_t, 16 > Offsets
uint64_t Min = std::numeric_limits<uint64_t>::max()
uint64_t Max = 0
Detailed Description
Definition at line 61 of file LowerTypeTests.h.
Constructor & Destructor Documentation
BitSetBuilder()
llvm::lowertypetests::BitSetBuilder::BitSetBuilder () default
Member Function Documentation
addOffset()
void llvm::lowertypetests::BitSetBuilder::addOffset (uint64_t Offset) inline
Definition at line 68 of file LowerTypeTests.h.
References Max, Min, Offset, Offsets, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
build()
BitSetInfo BitSetBuilder::build ()
Definition at line 149 of file LowerTypeTests.cpp.
References llvm::lowertypetests::BitSetInfo::AlignLog2, llvm::lowertypetests::BitSetInfo::Bits, llvm::lowertypetests::BitSetInfo::BitSize, llvm::lowertypetests::BitSetInfo::ByteOffset, llvm::countTrailingZeros(), Max, Min, Offset, Offsets, and llvm::ZB_Undefined.
Member Data Documentation
Max
uint64_t llvm::lowertypetests::BitSetBuilder::Max = 0
Definition at line 64 of file LowerTypeTests.h.
Referenced by addOffset(), and build().
Min
uint64_t llvm::lowertypetests::BitSetBuilder::Min = std::numeric_limits<uint64_t>::max()
Definition at line 63 of file LowerTypeTests.h.
Referenced by addOffset(), and build().
Offsets
SmallVector<uint64_t, 16> llvm::lowertypetests::BitSetBuilder::Offsets
Definition at line 62 of file LowerTypeTests.h.
Referenced by addOffset(), and build().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/LowerTypeTests.h
lib/Transforms/IPO/LowerTypeTests.cpp