LLVM: llvm::wholeprogramdevirt::VirtualCallTarget Struct Reference
llvm::wholeprogramdevirt::VirtualCallTarget Struct Reference
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
Public Member Functions
VirtualCallTarget (Function *Fn, const TypeMemberInfo *TM)
VirtualCallTarget (const TypeMemberInfo *TM, bool IsBigEndian)
uint64_t minBeforeBytes () const
uint64_t minAfterBytes () const
uint64_t allocatedBeforeBytes () const
uint64_t allocatedAfterBytes () const
void setBeforeBit (uint64_t Pos)
void setAfterBit (uint64_t Pos)
void setBeforeBytes (uint64_t Pos, uint8_t Size)
void setAfterBytes (uint64_t Pos, uint8_t Size)
Public Attributes
Function * Fn
const TypeMemberInfo * TM
uint64_t RetVal
bool IsBigEndian
bool WasDevirt
Detailed Description
Definition at line 119 of file WholeProgramDevirt.h.
Constructor & Destructor Documentation
VirtualCallTarget() [1/2]
VirtualCallTarget::VirtualCallTarget (Function * Fn, const TypeMemberInfo * TM)
Definition at line 293 of file WholeProgramDevirt.cpp.
VirtualCallTarget() [2/2]
llvm::wholeprogramdevirt::VirtualCallTarget::VirtualCallTarget (const TypeMemberInfo * TM, bool IsBigEndian) inline
Definition at line 123 of file WholeProgramDevirt.h.
Member Function Documentation
allocatedAfterBytes()
uint64_t llvm::wholeprogramdevirt::VirtualCallTarget::allocatedAfterBytes () const inline
Definition at line 164 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::VTableBits::After, llvm::wholeprogramdevirt::TypeMemberInfo::Bits, llvm::wholeprogramdevirt::AccumBitVector::Bytes, minAfterBytes(), and TM.
allocatedBeforeBytes()
uint64_t llvm::wholeprogramdevirt::VirtualCallTarget::allocatedBeforeBytes () const inline
Definition at line 158 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::VTableBits::Before, llvm::wholeprogramdevirt::TypeMemberInfo::Bits, llvm::wholeprogramdevirt::AccumBitVector::Bytes, minBeforeBytes(), and TM.
minAfterBytes()
uint64_t llvm::wholeprogramdevirt::VirtualCallTarget::minAfterBytes () const inline
Definition at line 154 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::TypeMemberInfo::Bits, llvm::wholeprogramdevirt::VTableBits::ObjectSize, llvm::wholeprogramdevirt::TypeMemberInfo::Offset, and TM.
Referenced by allocatedAfterBytes(), setAfterBit(), and setAfterBytes().
minBeforeBytes()
uint64_t llvm::wholeprogramdevirt::VirtualCallTarget::minBeforeBytes () const inline
Definition at line 147 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::TypeMemberInfo::Offset, and TM.
Referenced by allocatedBeforeBytes(), setBeforeBit(), and setBeforeBytes().
setAfterBit()
void llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBit (uint64_t Pos) inline
Definition at line 175 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::VTableBits::After, assert(), llvm::wholeprogramdevirt::TypeMemberInfo::Bits, minAfterBytes(), RetVal, llvm::wholeprogramdevirt::AccumBitVector::setBit(), and TM.
setAfterBytes()
void llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes (uint64_t Pos, uint8_t Size) inline
Definition at line 192 of file WholeProgramDevirt.h.
References llvm::wholeprogramdevirt::VTableBits::After, assert(), llvm::wholeprogramdevirt::TypeMemberInfo::Bits, IsBigEndian, minAfterBytes(), RetVal, llvm::wholeprogramdevirt::AccumBitVector::setBE(), llvm::wholeprogramdevirt::AccumBitVector::setLE(), Size, and TM.
setBeforeBit()
void llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBit (uint64_t Pos) inline
Definition at line 169 of file WholeProgramDevirt.h.
References assert(), llvm::wholeprogramdevirt::VTableBits::Before, llvm::wholeprogramdevirt::TypeMemberInfo::Bits, minBeforeBytes(), RetVal, llvm::wholeprogramdevirt::AccumBitVector::setBit(), and TM.
setBeforeBytes()
void llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes (uint64_t Pos, uint8_t Size) inline
Definition at line 183 of file WholeProgramDevirt.h.
References assert(), llvm::wholeprogramdevirt::VTableBits::Before, llvm::wholeprogramdevirt::TypeMemberInfo::Bits, IsBigEndian, minBeforeBytes(), RetVal, llvm::wholeprogramdevirt::AccumBitVector::setBE(), llvm::wholeprogramdevirt::AccumBitVector::setLE(), Size, and TM.
Member Data Documentation
Fn
Function* llvm::wholeprogramdevirt::VirtualCallTarget::Fn
Definition at line 127 of file WholeProgramDevirt.h.
IsBigEndian
bool llvm::wholeprogramdevirt::VirtualCallTarget::IsBigEndian
Definition at line 138 of file WholeProgramDevirt.h.
Referenced by setAfterBytes(), and setBeforeBytes().
RetVal
uint64_t llvm::wholeprogramdevirt::VirtualCallTarget::RetVal
Definition at line 135 of file WholeProgramDevirt.h.
Referenced by setAfterBit(), setAfterBytes(), setBeforeBit(), and setBeforeBytes().
TM
const TypeMemberInfo* llvm::wholeprogramdevirt::VirtualCallTarget::TM
Definition at line 131 of file WholeProgramDevirt.h.
Referenced by allocatedAfterBytes(), allocatedBeforeBytes(), minAfterBytes(), minBeforeBytes(), setAfterBit(), setAfterBytes(), setBeforeBit(), and setBeforeBytes().
WasDevirt
bool llvm::wholeprogramdevirt::VirtualCallTarget::WasDevirt
Definition at line 141 of file WholeProgramDevirt.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/WholeProgramDevirt.h
lib/Transforms/IPO/WholeProgramDevirt.cpp