LLVM: llvm::VFShape Struct Reference
llvm::VFShape Struct Reference
Contains the information about the kind of vectorization available.
#include "llvm/Analysis/VectorUtils.h"
Public Member Functions
bool operator== (const VFShape &Other) const
void updateParam (VFParameter P)
Update the parameter in position P.ParamPos to P.
bool hasValidParameterList () const
Sanity check on the Parameters in the VFShape.
Static Public Member Functions
static VFShape getScalarShape (const CallInst &CI)
static VFShape get (const CallInst &CI, ElementCount EC, bool HasGlobalPred)
Public Attributes
unsigned VF
bool IsScalable
SmallVector< VFParameter, 8 > Parameters
Detailed Description
Contains the information about the kind of vectorization available.
This object in independent on the paradigm used to represent vector functions. in particular, it is not attached to any target-specific ABI.
Definition at line 82 of file VectorUtils.h.
Member Function Documentation
get()
static VFShape llvm::VFShape::get (const CallInst & CI, ElementCount EC, bool HasGlobalPred) inline static
Definition at line 110 of file VectorUtils.h.
References llvm::CallBase::arg_size(), llvm::GlobalPredicate, I, Parameters, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Vector.
Referenced by getScalarShape(), llvm::LoopVectorizationCostModel::getVectorCallCost(), getVectorCallCosts(), and llvm::InnerLoopVectorizer::widenCallInstruction().
getScalarShape()
static VFShape llvm::VFShape::getScalarShape (const CallInst & CI) inline static
Definition at line 101 of file VectorUtils.h.
References get(), and llvm::LinearPolySize< ElementCount >::getFixed().
Referenced by llvm::VFDatabase::getVectorizedFunction().
hasValidParameterList()
bool VFShape::hasValidParameterList () const
Sanity check on the Parameters in the VFShape.
Definition at line 1336 of file VectorUtils.cpp.
References assert(), llvm::GlobalPredicate, llvm::OMP_Linear, llvm::OMP_LinearPos, llvm::OMP_LinearRef, llvm::OMP_LinearRefPos, llvm::OMP_LinearUVal, llvm::OMP_LinearUValPos, llvm::OMP_LinearVal, llvm::OMP_LinearValPos, llvm::OMP_Uniform, and Parameters.
Referenced by updateParam().
operator==()
bool llvm::VFShape::operator== (const VFShape & Other) const inline
Definition at line 87 of file VectorUtils.h.
References IsScalable, llvm::Other, Parameters, and VF.
updateParam()
void llvm::VFShape::updateParam (VFParameter P) inline
Update the parameter in position P.ParamPos to P.
Definition at line 93 of file VectorUtils.h.
References assert(), hasValidParameterList(), P, and Parameters.
Member Data Documentation
IsScalable
bool llvm::VFShape::IsScalable
Definition at line 84 of file VectorUtils.h.
Referenced by operator==().
Parameters
SmallVector<VFParameter, 8> llvm::VFShape::Parameters
Definition at line 85 of file VectorUtils.h.
Referenced by get(), hasValidParameterList(), operator==(), and updateParam().
VF
unsigned llvm::VFShape::VF
Definition at line 83 of file VectorUtils.h.
Referenced by operator==().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/VectorUtils.h
lib/Analysis/VectorUtils.cpp