LLVM: lib/Testing/Support/SupportHelpers.cpp File Reference
SupportHelpers.cpp File Reference
#include "llvm/Testing/Support/SupportHelpers.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "gtest/gtest.h"
Functions
static std::pair< bool, SmallString< 128 > > findSrcDirMap (StringRef Argv0)
Function Documentation
findSrcDirMap()
static std::pair< bool, SmallString< 128 > > findSrcDirMap (StringRef Argv0) static
Definition at line 16 of file SupportHelpers.cpp.
References llvm::sys::path::append(), llvm::sys::fs::is_regular_file(), llvm::sys::fs::make_absolute(), and llvm::sys::path::parent_path().
Referenced by llvm::unittest::getInputFileDirectory().