LLVM: lib/DebugInfo/PDB/Native/TpiHashing.cpp File Reference
TpiHashing.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/TpiHashing.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/PDB/Native/Hash.h"
#include "llvm/Support/CRC.h"
Functions
static bool isAnonymous (StringRef Name)
static uint32_t getHashForUdt (const TagRecord &Rec, ArrayRef< uint8_t > FullRecord)
template<typename T >
static Expected< uint32_t > getHashForUdt (const CVType &Rec)
template<typename T >
static Expected< TagRecordHash > getTagRecordHashForUdt (const CVType &Rec)
template<typename T >
static Expected< uint32_t > getSourceLineHash (const CVType &Rec)
Function Documentation
getHashForUdt() [1/2]
template<typename T > static Expected< uint32_t > getHashForUdt (const CVType & Rec) static
Definition at line 43 of file TpiHashing.cpp.
References llvm::codeview::CVRecord< Kind >::data(), llvm::codeview::TypeDeserializer::deserializeAs(), E, and getHashForUdt().
getHashForUdt() [2/2]
static uint32_t getHashForUdt (const TagRecord & Rec, ArrayRef< uint8_t > FullRecord) static
Definition at line 27 of file TpiHashing.cpp.
References llvm::codeview::TagRecord::getName(), llvm::codeview::TagRecord::getOptions(), llvm::codeview::TagRecord::getUniqueName(), llvm::pdb::hashBufferV8(), llvm::pdb::hashStringV1(), llvm::codeview::HasUniqueName, isAnonymous(), and llvm::codeview::Scoped.
Referenced by getHashForUdt(), getTagRecordHashForUdt(), and llvm::pdb::hashTypeRecord().
getSourceLineHash()
template<typename T > static Expected< uint32_t > getSourceLineHash (const CVType & Rec) static
Definition at line 78 of file TpiHashing.cpp.
References llvm::codeview::TypeDeserializer::deserializeAs(), E, llvm::pdb::hashStringV1(), and llvm::support::endian::write32le().
Referenced by llvm::pdb::hashTypeRecord().
getTagRecordHashForUdt()
template<typename T > static Expected< TagRecordHash > getTagRecordHashForUdt (const CVType & Rec) static
Definition at line 52 of file TpiHashing.cpp.
References llvm::codeview::CVRecord< Kind >::data(), llvm::codeview::TypeDeserializer::deserializeAs(), E, getHashForUdt(), llvm::pdb::hashStringV1(), and llvm::codeview::Scoped.
Referenced by llvm::pdb::hashTagRecord().
isAnonymous()
static bool isAnonymous (StringRef Name) static
Definition at line 20 of file TpiHashing.cpp.
References Name.
Referenced by getHashForUdt().