LLVM: lib/IR/Value.cpp File Reference
Value.cpp File Reference
#include "llvm/IR/Value.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DerivedUser.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include "llvm/IR/Value.def"
#include "llvm/IR/Instruction.def"
Macros
#define HANDLE_VALUE(Name)
#define HANDLE_MEMORY_VALUE(Name)
#define HANDLE_CONSTANT(Name)
#define HANDLE_INSTRUCTION(Name)
#define HANDLE_INST(N, OPC, CLASS)
#define HANDLE_USER_INST(N, OPC, CLASS)
Functions
static Type * checkType (Type *Ty)
static bool isUnDroppableUser (const User *U)
static bool getSymTab (Value *V, ValueSymbolTable *&ST)
static bool contains (SmallPtrSetImpl< ConstantExpr * > &Cache, ConstantExpr *Expr, Constant *C)
static bool contains (Value *Expr, Value *V)
Variables
static cl::opt< unsigned > NonGlobalValueMaxNameSize ("non-global-value-max-name-size", cl::Hidden, cl::init(1024), cl::desc("Maximum size for the name of non-global values."))
Macro Definition Documentation
HANDLE_CONSTANT
#define HANDLE_CONSTANT (Name)
Value:
  case Value::Name##Val:                                                       \
    llvm_unreachable("constants should be destroyed with destroyConstant");    \
    break;
HANDLE_INST
#define HANDLE_INST (N, OPC, CLASS)
Value:
  case Value::InstructionVal + Instruction::OPC:                               \
    delete static_cast<CLASS *>(this);                                         \
    break;
HANDLE_INSTRUCTION
#define HANDLE_INSTRUCTION (Name)
Value:
/* nothing */
HANDLE_MEMORY_VALUE
#define HANDLE_MEMORY_VALUE (Name)
Value:
  case Value::Name##Val:                                                       \
    static_cast<DerivedUser *>(this)->DeleteValue(                             \
        static_cast<DerivedUser *>(this));                                     \
    break;
HANDLE_USER_INST
#define HANDLE_USER_INST (N, OPC, CLASS)
HANDLE_VALUE
#define HANDLE_VALUE (Name)
Value:
  case Value::Name##Val:                                                       \
    delete static_cast<Name *>(this);                                          \
    break;
Function Documentation
checkType()
static Type * checkType (Type * Ty) inline static
Definition at line 48 of file Value.cpp.
References assert().
contains() [1/2]
static bool contains (SmallPtrSetImpl< ConstantExpr * > & Cache, ConstantExpr * Expr, Constant * C) static
Definition at line 458 of file Value.cpp.
References C, contains(), llvm::dyn_cast(), and llvm::User::operands().
Referenced by llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::X86Operand::addGR16orGR32orGR64Operands(), llvm::X86Operand::addGR32orGR64Operands(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::breakPartialRegDependency(), CheckBaseRegAndIndexRegAndScale(), computeCalleeSaveRegisterPairs(), contains(), contains(), llvm::RegionBase< Tr >::contains(), llvm::RegionBase< RegionTraits< MachineFunction > >::contains(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARCInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::AVRInstrInfo::copyPhysReg(), llvm::BPFInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::LanaiInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::R600InstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Thumb2InstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), llvm::X86InstrInfo::describeLoadedValue(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::SystemZFrameLowering::determineCalleeSaves(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::RegionBase< Tr >::getBBNode(), llvm::ValueLatticeElement::getCompare(), llvm::HexagonInstrInfo::getCompoundCandidateGroup(), llvm::HexagonInstrInfo::getDuplexCandidateGroup(), llvm::RegionBase< Tr >::getEnteringBlock(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::LoopBase< BasicBlock, Loop >::getExitEdges(), llvm::RegionBase< Tr >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::RegionBase< Tr >::getExitingBlocks(), llvm::RegionBase< Tr >::getExpandedRegion(), getHexagonRegisterPair(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), getMFHiLoOpc(), getNextRegister(), llvm::RegionBase< Tr >::getNode(), getPairedGPR(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), getRC32(), getRegClassFromGRPhysReg(), llvm::SystemZFrameLowering::getRegSpillOffset(), llvm::SIRegisterInfo::getReservedRegs(), getSVECalleeSaveSlotRange(), llvm::LoopBase< BlockT, LoopT >::hasDedicatedExits(), llvm::LoopBase< BasicBlock, Loop >::hasNoExitBlocks(), indirectCopyToAGPR(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), llvm::SITargetLowering::insertCopiesSplitCSR(), is16BitMemOperand(), isCSRestore(), isEvenReg(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::X86Operand::isGR16orGR32orGR64(), llvm::X86Operand::isGR32orGR64(), llvm::SystemZ::isHighReg(), llvm::X86Operand::isVectorReg(), llvm::SITargetLowering::LowerReturn(), lowerRISCVVMachineInstrToMCInst(), mapArgRegToOffsetAIX(), narrowSDivOrSRem(), nextReg(), llvm::RegionBase< Tr >::outermostLoopInRegion(), printAsmMRegister(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), printAsmVRegister(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::AArch64RegisterInfo::regNeedsCFI(), llvm::Value::replaceUsesOutsideBlock(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::AVRRegisterInfo::splitReg(), and llvm::Function::viewCFG().
contains() [2/2]
static bool contains (Value * Expr, Value * V) static
Definition at line 475 of file Value.cpp.
References C, contains(), and llvm::dyn_cast().
getSymTab()
static bool getSymTab (Value * V, ValueSymbolTable *& ST) static
Definition at line 245 of file Value.cpp.
References A, assert(), llvm::dyn_cast(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), I, llvm::isa(), and P.
Referenced by llvm::SymbolTableListTraits< ValueSubClass >::addNodeToList(), llvm::SymbolTableListTraits< ValueSubClass >::removeNodeFromList(), llvm::SymbolTableListTraits< ValueSubClass >::setSymTabObject(), and llvm::Value::takeName().
isUnDroppableUser()
static bool isUnDroppableUser (const User * U) static
Definition at line 162 of file Value.cpp.
Referenced by llvm::Value::hasNUndroppableUses(), and llvm::Value::hasNUndroppableUsesOrMore().
Variable Documentation
NonGlobalValueMaxNameSize
cl::opt< unsigned > NonGlobalValueMaxNameSize("non-global-value-max-name-size", cl::Hidden, cl::init(1024), cl::desc("Maximum size for the name of non-global values.")) ("non-global-value-max-name-size" , cl::Hidden , cl::init(1024) , cl::desc("Maximum size for the name of non-global values.")) static