LLVM: lib/Target/X86/X86InstCombineIntrinsic.cpp File Reference
X86InstCombineIntrinsic.cpp File Reference
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
#include "X86TargetTransformInfo.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
Macros
#define DEBUG_TYPE "x86tti"
Functions
static Constant * getNegativeIsTrueBoolVec (Constant *V)
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
static Value * getBoolVecFromMask (Value *Mask)
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
static Instruction * simplifyX86MaskedLoad (IntrinsicInst &II, InstCombiner &IC)
static bool simplifyX86MaskedStore (IntrinsicInst &II, InstCombiner &IC)
static Value * simplifyX86immShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86varShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86pack (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsSigned)
static Value * simplifyX86movmsk (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86addcarry (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86insertps (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86extrq (IntrinsicInst &II, Value *Op0, ConstantInt *CILength, ConstantInt *CIIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86insertq (IntrinsicInst &II, Value *Op0, Value *Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86pshufb (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert pshufb* to shufflevector if the mask is constant.
static Value * simplifyX86vpermilvar (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
static Value * simplifyX86vpermv (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Detailed Description
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
It uses the target's detailed information to provide more precise answers to certain TTI queries, while letting the target independent and default TTI implementations handle the rest.
Definition in file X86InstCombineIntrinsic.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86tti"
Definition at line 24 of file X86InstCombineIntrinsic.cpp.
Function Documentation
getBoolVecFromMask()
static Value * getBoolVecFromMask (Value * Mask) static
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
Definition at line 38 of file X86InstCombineIntrinsic.cpp.
References llvm::dyn_cast(), getNegativeIsTrueBoolVec(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyX86MaskedLoad(), and simplifyX86MaskedStore().
getNegativeIsTrueBoolVec()
static Constant * getNegativeIsTrueBoolVec (Constant * V) static
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
Definition at line 28 of file X86InstCombineIntrinsic.cpp.
References llvm::cast(), llvm::ConstantExpr::getBitCast(), llvm::ConstantExpr::getICmp(), llvm::Constant::getNullValue(), and llvm::CmpInst::ICMP_SGT.
Referenced by getBoolVecFromMask(), and llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86addcarry()
static Value * simplifyX86addcarry (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 534 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::Type::getStructElementType(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_ZeroInt(), and llvm::Intrinsic::uadd_with_overflow.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86extrq()
static Value * simplifyX86extrq (IntrinsicInst & II, Value * Op0, ConstantInt * CILength, ConstantInt * CIIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 620 of file X86InstCombineIntrinsic.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), F, llvm::ConstantAggregateZero::get(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::Constant::getAggregateElement(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), llvm::ConstantInt::isZero(), llvm::APInt::lshrInPlace(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86immShift()
static Value * simplifyX86immShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 119 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::BitWidth, llvm::cast(), llvm::computeKnownBits(), llvm::Count, llvm::dyn_cast(), llvm::ConstantAggregateZero::get(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::APInt::getBitsSet(), llvm::Module::getDataLayout(), llvm::IntrinsicInst::getIntrinsicID(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::Instruction::getModule(), llvm::APInt::getOneBitSet(), llvm::APInt::isNullValue(), llvm::KnownBits::isZero(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertps()
static Value * simplifyX86insertps (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 561 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), and llvm::Value::getType().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertq()
static Value * simplifyX86insertq (IntrinsicInst & II, Value * Op0, Value * Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 711 of file X86InstCombineIntrinsic.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), F, llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::Constant::getAggregateElement(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::IntrinsicInst::getIntrinsicID(), llvm::APInt::getLowBitsSet(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), Index, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::APInt::shl(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedLoad()
static Instruction * simplifyX86MaskedLoad (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 56 of file X86InstCombineIntrinsic.cpp.
References Align, llvm::InstCombiner::Builder, llvm::cast(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedLoad(), getBoolVecFromMask(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Value::getType(), llvm::isa(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedStore()
static bool simplifyX86MaskedStore (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 86 of file X86InstCombineIntrinsic.cpp.
References Align, llvm::InstCombiner::Builder, llvm::cast(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::InstCombiner::eraseInstFromFunction(), getBoolVecFromMask(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::isa().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86movmsk()
static Value * simplifyX86movmsk (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 504 of file X86InstCombineIntrinsic.cpp.
References Arg, llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::Type::getIntNTy(), llvm::Constant::getNullValue(), llvm::Value::getType(), and llvm::isa().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pack()
static Value * simplifyX86pack (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsSigned) static
Definition at line 438 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::Constant::getIntegerValue(), llvm::APInt::getLowBitsSet(), llvm::APInt::getNullValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::sext().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pshufb()
static Value * simplifyX86pshufb (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert pshufb* to shufflevector if the mask is constant.
Definition at line 804 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), I, Index, llvm::isa(), and llvm::makeArrayRef().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86varShift()
static Value * simplifyX86varShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 301 of file X86InstCombineIntrinsic.cpp.
References llvm::all_of(), assert(), llvm::BitWidth, llvm::cast(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::Module::getDataLayout(), llvm::APInt::getHighBitsSet(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::Value::getType(), llvm::APInt::getZExtValue(), I, llvm::isa_and_nonnull(), llvm_unreachable, llvm::Log2_32(), llvm::MaskedValueIsZero(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::uge().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermilvar()
static Value * simplifyX86vpermilvar (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
Definition at line 849 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::APInt::getLoBits(), llvm::Value::getType(), I, llvm::isa(), llvm::APInt::lshrInPlace(), llvm::makeArrayRef(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermv()
static Value * simplifyX86vpermv (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Definition at line 896 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), I, Index, llvm::isa(), llvm::makeArrayRef(), and Size.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().