LLVM: llvm::FixedStreamArray< T > Class Template Reference
llvm::FixedStreamArray< T > Class Template Reference
FixedStreamArray is similar to VarStreamArray, except with each record having a fixed-length.
#include "llvm/Support/BinaryStreamArray.h"
Public Types
typedef FixedStreamArrayIterator< T > Iterator
Public Member Functions
FixedStreamArray ()=default
FixedStreamArray (BinaryStreamRef Stream)
bool operator== (const FixedStreamArray< T > &Other) const
bool operator!= (const FixedStreamArray< T > &Other) const
FixedStreamArray (const FixedStreamArray &)=default
FixedStreamArray & operator= (const FixedStreamArray &)=default
const T & operator[] (uint32_t Index) const
uint32_t size () const
bool empty () const
FixedStreamArrayIterator< T > begin () const
FixedStreamArrayIterator< T > end () const
const T & front () const
const T & back () const
BinaryStreamRef getUnderlyingStream () const
Friends
class FixedStreamArrayIterator< T >
Detailed Description
template<typename T>
class llvm::FixedStreamArray< T >
FixedStreamArray is similar to VarStreamArray, except with each record having a fixed-length.
As with VarStreamArray, there is no upfront cost associated with building or copying a FixedStreamArray, as the memory for each element is not read from the backing stream until that element is iterated.
Definition at line 259 of file BinaryStreamArray.h.
Member Typedef Documentation
Iterator
template<typename T > FixedStreamArrayIterator<T> llvm::FixedStreamArray< T >::Iterator
Definition at line 263 of file BinaryStreamArray.h.
Constructor & Destructor Documentation
FixedStreamArray() [1/3]
template<typename T > llvm::FixedStreamArray< T >::FixedStreamArray () default
FixedStreamArray() [2/3]
template<typename T > llvm::FixedStreamArray< T >::FixedStreamArray (BinaryStreamRef Stream) inline explicit
Definition at line 266 of file BinaryStreamArray.h.
References assert(), and llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
FixedStreamArray() [3/3]
template<typename T > llvm::FixedStreamArray< T >::FixedStreamArray (const FixedStreamArray< T > &) default
Member Function Documentation
back()
template<typename T > const T & llvm::FixedStreamArray< T >::back () const inline
Definition at line 308 of file BinaryStreamArray.h.
References llvm::FixedStreamArray< T >::end(), and I.
begin()
template<typename T > FixedStreamArrayIterator< T > llvm::FixedStreamArray< T >::begin () const inline
Definition at line 299 of file BinaryStreamArray.h.
References llvm::FixedStreamArray< T >::FixedStreamArrayIterator< T >.
Referenced by llvm::codeview::DebugSymbolRVASubsectionRef::begin(), llvm::pdb::GSIHashTable::begin(), and llvm::FixedStreamArray< T >::front().
empty()
template<typename T > bool llvm::FixedStreamArray< T >::empty () const inline
Definition at line 297 of file BinaryStreamArray.h.
References llvm::FixedStreamArray< T >::size().
Referenced by llvm::pdb::TpiStream::buildHashMap().
end()
template<typename T > FixedStreamArrayIterator< T > llvm::FixedStreamArray< T >::end () const inline
Definition at line 303 of file BinaryStreamArray.h.
References llvm::FixedStreamArray< T >::FixedStreamArrayIterator< T >, and llvm::FixedStreamArray< T >::size().
Referenced by llvm::FixedStreamArray< T >::back(), llvm::codeview::DebugSymbolRVASubsectionRef::end(), and llvm::pdb::GSIHashTable::end().
front()
template<typename T > const T & llvm::FixedStreamArray< T >::front () const inline
Definition at line 307 of file BinaryStreamArray.h.
References llvm::FixedStreamArray< T >::begin().
getUnderlyingStream()
template<typename T > BinaryStreamRef llvm::FixedStreamArray< T >::getUnderlyingStream () const inline
Definition at line 313 of file BinaryStreamArray.h.
operator!=()
template<typename T > bool llvm::FixedStreamArray< T >::operator!= (const FixedStreamArray< T > & Other) const inline
Definition at line 274 of file BinaryStreamArray.h.
References llvm::Other.
operator=()
template<typename T > FixedStreamArray & llvm::FixedStreamArray< T >::operator= (const FixedStreamArray< T > &) default
operator==()
template<typename T > bool llvm::FixedStreamArray< T >::operator== (const FixedStreamArray< T > & Other) const inline
Definition at line 270 of file BinaryStreamArray.h.
References llvm::Other.
operator[]()
template<typename T > const T & llvm::FixedStreamArray< T >::operator[] (uint32_t Index) const inline
Definition at line 281 of file BinaryStreamArray.h.
References assert(), llvm::consumeError(), llvm::Data, llvm::isAddrAligned(), llvm::Align::Of(), llvm::BinaryStreamRef::readBytes(), llvm::FixedStreamArray< T >::size(), and T.
size()
template<typename T > uint32_t llvm::FixedStreamArray< T >::size () const inline
Definition at line 295 of file BinaryStreamArray.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and T.
Referenced by llvm::FixedStreamArray< T >::empty(), llvm::FixedStreamArray< T >::end(), llvm::pdb::GlobalsStream::findRecordsByName(), llvm::pdb::PDBStringTable::getIDForString(), and llvm::FixedStreamArray< T >::operator[]().
Friends And Related Symbol Documentation
FixedStreamArrayIterator< T >
template<typename T > friend class FixedStreamArrayIterator< T > friend
Definition at line 249 of file BinaryStreamArray.h.
Referenced by llvm::FixedStreamArray< T >::begin(), and llvm::FixedStreamArray< T >::end().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryStreamArray.h