LLVM: llvm::IndexedMap< T, ToIndexT > Class Template Reference
llvm::IndexedMap< T, ToIndexT > Class Template Reference
#include "llvm/ADT/IndexedMap.h"
Public Member Functions
IndexedMap ()
IndexedMap (const T &val)
StorageT::reference operator[] (IndexT n)
StorageT::const_reference operator[] (IndexT n) const
void reserve (typename StorageT::size_type s)
void resize (typename StorageT::size_type s)
void clear ()
void grow (IndexT n)
bool inBounds (IndexT n) const
StorageT::size_type size () const
Detailed Description
template<typename T, typename ToIndexT = identity<unsigned>>
class llvm::IndexedMap< T, ToIndexT >
Definition at line 30 of file IndexedMap.h.
Constructor & Destructor Documentation
IndexedMap() [1/2]
template<typename T , typename ToIndexT = identity<unsigned>> llvm::IndexedMap< T, ToIndexT >::IndexedMap () inline
Definition at line 42 of file IndexedMap.h.
IndexedMap() [2/2]
template<typename T , typename ToIndexT = identity<unsigned>> llvm::IndexedMap< T, ToIndexT >::IndexedMap (const T & val) inline explicit
Definition at line 44 of file IndexedMap.h.
Member Function Documentation
clear()
template<typename T , typename ToIndexT = identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::clear () inline
Definition at line 64 of file IndexedMap.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by LiveDebugValues::MLocTracker::clear(), llvm::VirtRegMap::clearAllVirt(), llvm::MachineRegisterInfo::clearSimpleHint(), llvm::MachineRegisterInfo::clearVirtRegTypes(), and llvm::MachineRegisterInfo::setRegAllocationHint().
grow()
template<typename T , typename ToIndexT = identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::grow (IndexT n) inline
Definition at line 68 of file IndexedMap.h.
References llvm::IndexedMap< T, ToIndexT >::resize(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::LiveIntervals::createEmptyInterval(), LiveDebugValues::MLocTracker::getOrTrackSpillLoc(), llvm::object::GOFFObjectFile::GOFFObjectFile(), llvm::MachineRegisterInfo::insertVRegByName(), llvm::MachineRegisterInfo::setType(), llvm::SystemZELFFrameLowering::SystemZELFFrameLowering(), llvm::SystemZXPLINKFrameLowering::SystemZXPLINKFrameLowering(), and LiveDebugValues::MLocTracker::trackRegister().
inBounds()
template<typename T , typename ToIndexT = identity<unsigned>> bool llvm::IndexedMap< T, ToIndexT >::inBounds (IndexT n) const inline
Definition at line 74 of file IndexedMap.h.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::MachineRegisterInfo::getVRegName(), and llvm::LiveIntervals::hasInterval().
operator[]() [1/2]
template<typename T , typename ToIndexT = identity<unsigned>> StorageT::reference llvm::IndexedMap< T, ToIndexT >::operator[] (IndexT n) inline
Definition at line 46 of file IndexedMap.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
operator[]() [2/2]
template<typename T , typename ToIndexT = identity<unsigned>> StorageT::const_reference llvm::IndexedMap< T, ToIndexT >::operator[] (IndexT n) const inline
Definition at line 51 of file IndexedMap.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
reserve()
template<typename T , typename ToIndexT = identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::reserve (typename StorageT::size_type s) inline
Definition at line 56 of file IndexedMap.h.
References llvm::SmallVectorImpl< T >::reserve().
resize()
template<typename T , typename ToIndexT = identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::resize (typename StorageT::size_type s) inline
Definition at line 60 of file IndexedMap.h.
References llvm::SmallVectorImpl< T >::resize().
Referenced by llvm::IndexedMap< T, ToIndexT >::grow(), and llvm::LiveRangeCalc::resetLiveOutMap().
size()
template<typename T , typename ToIndexT = identity<unsigned>> StorageT::size_type llvm::IndexedMap< T, ToIndexT >::size () const inline
Definition at line 78 of file IndexedMap.h.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by LiveDebugValues::MLocTracker::end(), LiveDebugValues::MLocTracker::getNumLocs(), LiveDebugValues::MLocTracker::getOrTrackSpillLoc(), llvm::MachineRegisterInfo::getRegAllocationHint(), llvm::object::GOFFObjectFile::moveSymbolNext(), LiveDebugValues::MLocTracker::readMLoc(), LiveDebugValues::MLocTracker::setMLoc(), and LiveDebugValues::MLocTracker::trackRegister().
The documentation for this class was generated from the following file:
include/llvm/ADT/IndexedMap.h